### ISSUE TITLE
特殊字符处理问题？

### ISSUE THREAD

**Issue by remiliacn** [Mrs4s/go-cqhttp#10]
我有个测试机器人是否死机的命令会让机器人回复`¿?¿?`
但是机器人对命令进行处理的时候出现了下面的报错
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x8c3381]

goroutine 87 [running]:
github.com/xujiajun/nutsdb.(*Tx).getTxID(0xc00040c880, 0xc00040c880, 0x20, 0x37d0413a)
        /go/pkg/mod/github.com/xujiajun/nutsdb@v0.5.0/tx.go:112 +0x31
github.com/xujiajun/nutsdb.newTx(0x0, 0x1, 0x20, 0xc037d0413a, 0xc00007f9b8)
        /go/pkg/mod/github.com/xujiajun/nutsdb@v0.5.0/tx.go:100 +0x9b
github.com/xujiajun/nutsdb.(*DB).Begin(0x0, 0x1, 0x11, 0xc000266478, 0xb4e7e0)
        /go/pkg/mod/github.com/xujiajun/nutsdb@v0.5.0/tx.go:74 +0x3f
github.com/xujiajun/nutsdb.(*DB).managed(0x0, 0xc00004df01, 0xc00007fa40, 0x7, 0xc00014a208)
        /go/pkg/mod/github.com/xujiajun/nutsdb@v0.5.0/db.go:847 +0x3f
github.com/xujiajun/nutsdb.(*DB).Update(...)
        /go/pkg/mod/github.com/xujiajun/nutsdb@v0.5.0/db.go:262
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).InsertGroupMessage(0xc0003c9ae0, 0xc0000addb0, 0xc00007fbe8)
        /github/workspace/coolq/bot.go:139 +0x430
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).SendGroupMessage(0xc0003c9ae0, 0x3c11d49f, 0xc00007fbe8, 0x30)
        /github/workspace/coolq/bot.go:106 +0x127
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendGroupMessage(0xc0003c9ae0, 0x3c11d49f, 0xc5e500, 0xc0005b1d78, 0x0)
        /github/workspace/coolq/api.go:104 +0x7be
github.com/Mrs4s/go-cqhttp/server.glob..func8(0xc0003c9ae0, 0x5, 0xc0002f601e, 0x7d, 0x0, 0x0, 0x0, 0x1e, 0x6)
        /github/workspace/server/websocket.go:331 +0x3fa
github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenApi(0xc00040c740, 0xc00053c3f0, 0xc0000cfa00)
        /github/workspace/server/websocket.go:169 +0x54b
created by github.com/Mrs4s/go-cqhttp/server.(*websocketClient).connectApi
        /github/workspace/server/websocket.go:102 +0x5ec
```

**Comment by remiliacn** [comment]
恩？use_db=True的时候就好了。怪

**Comment by Mrs4s** [comment]
> 恩？use_db=True的时候就好了。怪

出这个问题的时候是没有开数据库吗

**Comment by remiliacn** [comment]
对，开了以后就不出这个问题了。

**Comment by remiliacn** [comment]
出错时的config
```
{
  "uin": 123123,
  "password": "xxx",
  "enable_db": false,
  "access_token": "",
  "relogin": false,
  "relogin_delay": 0,
  "http_config": {
    "enabled": true,
    "host": "[::]",
    "port": 5700,
    "post_urls": {}
  },
  "ws_config": {
    "enabled": false,
    "host": "127.0.0.1",
    "port": 6700
  },
  "ws_reverse_servers": [
    {
      "enabled": true,
      "reverse_url": "",
      "reverse_api_url": "ws://127.0.0.1:5700/ws/api/",
      "reverse_event_url": "ws://127.0.0.1:5700/ws/event/",
      "reverse_reconnect_interval": 3000
    }
  ],
  "debug": false
}
```
