### ISSUE TITLE
获取合并转发报错panic on decoder MultiMsg.ApplyDown

### ISSUE THREAD

**Issue by assassingyk** [Mrs4s/go-cqhttp#1007]
**环境信息**

go-cqhttp版本: v1.0.0-beta5
运行环境: centOS 7，Windows10
连接方式: 反向ws
使用协议: iPad

**在最新的release版本中能否复现**
最新版v1.0.0-beta5，多次重启仍复现
**bug内容**
get_forward_msg获取合并转发消息时报错panic on decoder MultiMsg.ApplyDown，linux与Windows双平台多次重启均复现
```
[2021-08-14 19:06:43] [DEBUG]: WS接收到API调用: get_forward_msg 参数: {"message_id": "rEgVWVdo2+QUrbQddj+d35vIXUNK0ojUn//v6+U8lEu8l91TGM7pRVDC+lCfzl82\" m_fileName=\"6996240876102393282\" tSum=\"4\" sourceMsgId=\"0\" url=\"\" flag=\"3\" adverSign=\"0\" multiMsgFlag=\"0\"><item layout=\"1\" advertiser_id=\"0\" aid=\"0\"><title size=\"34\" maxLines=\"2\" lineSpace=\"12\">\u7fa4\u804a\u7684\u804a\u5929\u8bb0\u5f55</title><title size=\"26\" color=\"#777777\" maxLines=\"2\" lineSpace=\"12\">\u6211\u4eec\u7231\u79d1\u5b66:  \u6d4b\u8bd5\u4e00\u4e0b\u8f6c\u53d1\u6d88\u606f</title><title size=\"26\" color=\"#777777\" maxLines=\"2\" lineSpace=\"12\">\u6211\u4eec\u7231\u79d1\u5b66:  1</title><title size=\"26\" color=\"#777777\" maxLines=\"2\" lineSpace=\"12\">\u6211\u4eec\u7231\u79d1\u5b66:  2</title><title size=\"26\" color=\"#777777\" maxLines=\"2\" lineSpace=\"12\">\u6211\u4eec\u7231\u79d1\u5b66:  3</title><hr hidden=\"false\" style=\"0\" /><summary size=\"26\" color=\"#777777\">\u67e5\u770b4\u6761\u8f6c\u53d1\u6d88\u606f</summary></item><source name=\"\u804a\u5929\u8bb0\u5f55\" icon=\"\" action=\"\" appid=\"-1"}
[2021-08-14 19:06:43] [DEBUG]: Protocol -> rev pkt: PbMessageSvc.PbMsgReadedReport seq: 13906
[2021-08-14 19:06:43] [DEBUG]: Protocol -> rev pkt: MultiMsg.ApplyDown seq: 13907
[2021-08-14 19:06:43] [ERROR]: Protocol -> panic on decoder MultiMsg.ApplyDown : runtime error: index out of range [0] with length 0
goroutine 169 [running]:
runtime/debug.Stack(0xc0004d3b40, 0xe72b60, 0xc000032258)
        runtime/debug/stack.go:24 +0xa5
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1(0xc0004b4000, 0xc000374820)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/network.go:204 +0x78
panic(0xe72b60, 0xc000032258)
        runtime/panic.go:965 +0x1c7
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse.func1(0xc0002127e0, 0xc000518000, 0x342, 0x101fa40)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/multimsg.go:101 +0x17d
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse(0xc0004b4000, 0xc0002d6120, 0xc000166e00, 0x342, 0x342, 0xc000068001, 0xc000051f48, 0x15ef8a0, 0xc0004c39f0)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/multimsg.go:102 +0x172
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0004b4000, 0xc000374820)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/network.go:211 +0x198
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/network.go:201 +0x3d7

[2021-08-14 19:06:54] [DEBUG]: Protocol -> rev pkt: Heartbeat.Alive seq: 13908
[2021-08-14 19:06:58] [DEBUG]: Protocol -> rev pkt: MultiMsg.ApplyDown seq: 13907
[2021-08-14 19:06:58] [ERROR]: Protocol -> panic on decoder MultiMsg.ApplyDown : runtime error: index out of range [0] with length 0
goroutine 157 [running]:
runtime/debug.Stack(0xc0004d3b40, 0xe72b60, 0xc00048a0c0)
        runtime/debug/stack.go:24 +0xa5
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1(0xc0004b4000, 0xc0007240f0)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/network.go:204 +0x78
panic(0xe72b60, 0xc00048a0c0)
        runtime/panic.go:965 +0x1c7
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse.func1(0xc0000ee460, 0xc0002d03c0, 0x342, 0x101fa40)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/multimsg.go:101 +0x17d
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse(0xc0004b4000, 0xc0004a2080, 0xc0005c0000, 0x342, 0x342, 0x1, 0xc0000f9127, 0x19, 0x0)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/multimsg.go:102 +0x172
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0004b4000, 0xc0007240f0)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/network.go:211 +0x198
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20210726103104-1d68826cef0e/client/network.go:201 +0x3d7

```

**复现方法**

发送合并转发消息并调用get_forward_msg即复现

**Comment by wdvxdr1123** [comment]
duplicate of ##999

**Comment by fkx4-p** [comment]
草
