### ISSUE TITLE
使用环境变量 GCQ_LEVELDB=true 启动时报错

### ISSUE THREAD

**Issue by 502647092** [Mrs4s/go-cqhttp#1025]
**环境信息**
go-cqhttp版本: 1.0.0-b6
运行环境: linux
连接方式: ws
使用协议: ws

**在最新的release版本中能否复现**
能

**bug内容**
使用环境变量 GCQ_LEVELDB=true 启动时报错

**复现方法**
```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/Mrs4s/go-cqhttp/global/config.Get.func1()
        github.com/Mrs4s/go-cqhttp/global/config/config.go:178 +0x645
sync.(*Once).doSlow(0x159bbc0, 0xedf0b0)
        sync/once.go:68 +0xec
sync.(*Once).Do(...)
        sync/once.go:59
github.com/Mrs4s/go-cqhttp/global/config.Get(0xc00007c600)
        github.com/Mrs4s/go-cqhttp/global/config/config.go:149 +0x59
main.main()
        github.com/Mrs4s/go-cqhttp/main.go:76 +0x298
```

**Comment by Kyomotoi** [comment]
`GCQ_DATABASE_ENABLE` 这条在config相关处理逻辑中并未找到，相关：`GCQ_LEVELDB`

**Comment by 502647092** [comment]
> `GCQ_DATABASE_ENABLE` 这条在config相关处理逻辑中并未找到，相关：`GCQ_LEVELDB`

写错了 应该是 GCQ_LEVELDB
