### ISSUE TITLE
启动时出现error：无效内存地址或零指针解引用

### ISSUE THREAD

**Issue by 2938137849** [Mrs4s/go-cqhttp#1054]
**环境信息**

go-cqhttp版本: v1.0.0-beta6
运行环境: Linux 4.19.0-12-amd64 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
连接方式: 无
使用协议: 0

**在最新的release版本中能否复现**

**bug内容**

```log
[2021-09-15 22:27:36] [INFO]: 当前版本:v1.0.0-beta6 
[2021-09-15 22:27:36] [INFO]: 用户交流群: 721829413 
[2021-09-15 22:27:36] [WARNING]: 虚拟设备信息不存在, 将自动生成随机设备. 
[2021-09-15 22:27:36] [INFO]: 已生成设备信息并保存到 device.json 文件. 
[2021-09-15 22:27:36] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2021-09-15 22:27:41] [INFO]: 开始尝试登录并同步消息... 
[2021-09-15 22:27:41] [INFO]: 使用协议: iPad 
[2021-09-15 22:27:57] [INFO]: Protocol -> connect to server: 203.205.255.220:8080 
[2021-09-15 22:28:01] [INFO]: 登录成功 欢迎使用: new bot() 
[2021-09-15 22:28:01] [INFO]: 开始加载好友列表... 
[2021-09-15 22:28:01] [INFO]: 共加载 8 个好友. 
[2021-09-15 22:28:01] [INFO]: 开始加载群列表... 
[2021-09-15 22:28:02] [INFO]: 共加载 3 个群. 
[2021-09-15 22:28:02] [INFO]: 信息数据库初始化完成. 
[2021-09-15 22:28:02] [INFO]: 资源初始化完成, 开始处理信息. 
[2021-09-15 22:28:02] [INFO]: アトリは、高性能ですから! 
[2021-09-15 22:28:02] [INFO]: CQ WebSocket 服务器已启动: 0.0.0.0:6700 
[2021-09-15 22:28:02] [INFO]: 正在检查更新. 
[2021-09-15 22:28:02] [INFO]: 检查更新完成. 当前已运行最新版本. 
event error: runtime error: invalid memory address or nil pointer dereference
goroutine 109 [running]:
runtime/debug.Stack(0xc0005bf6b0, 0xd6b460, 0x154dc00)
        runtime/debug/stack.go:24 +0x9f
github.com/Mrs4s/MiraiGo/client.cover.func1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20210810070836-6614d2383adb/client/events.go:485 +0x76
runtime/debug.Stack(0xc0005bf6b0, 0xd6b460, 0x154dc00)
        runtime/debug/stack.go:24 +0x9f
github.com/Mrs4s/MiraiGo/client.cover.func1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20210810070836-6614d2383adb/client/events.go:485 +0x76
panic(0xd6b460, 0x154dc00)
        runtime/panic.go:965 +0x1b9
github.com/Mrs4s/go-cqhttp/coolq.ToArrayMessage(0xc000303380, 0x5, 0x8, 0x2766016b, 0x6dfb12daec4e63cc, 0x8, 0xd0a820)
[2021-09-15 22:28:02] [INFO]: 信息数据库初始化完成.
[2021-09-15 22:28:02] [INFO]: 资源初始化完成, 开始处理信息.
[2021-09-15 22:28:02] [INFO]: アトリは、高性能ですから!
[2021-09-15 22:28:02] [INFO]: CQ WebSocket 服务器已启动: 0.0.0.0:6700
[2021-09-15 22:28:02] [INFO]: 正在检查更新.
[2021-09-15 22:28:02] [INFO]: 收到群 () 内 () 的消息: 
[2021-09-15 22:28:02] [INFO]: 检查更新完成. 当前已运行最新版本.
[2021-09-15 22:28:04] [INFO]: 收到群 () 内 () 的消息: 
[2021-09-15 22:28:08] [INFO]: 收到群 () 内 () 的消息: 
[2021-09-15 22:28:11] [INFO]: 收到群 () 内 () 的消息:
event error: runtime error: invalid memory address or nil pointer dereference
goroutine 109 [running]:
runtime/debug.Stack(0xc0005bf6b0, 0xd6b460, 0x154dc00)
        runtime/debug/stack.go:24 +0x9f
github.com/Mrs4s/MiraiGo/client.cover.func1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20210810070836-6614d2383adb/client/events.go:485 +0x76
panic(0xd6b460, 0x154dc00)
        runtime/panic.go:965 +0x1b9
github.com/Mrs4s/go-cqhttp/coolq.ToArrayMessage(0xc000303380, 0x5, 0x8, 0x2766016b, 0x6dfb12daec4e63cc, 0x8, 0xd0a820)
        github.com/Mrs4s/go-cqhttp/coolq/cqcode.go:164 +0x1862
github.com/Mrs4s/go-cqhttp/coolq.ToFormattedMessage(0xc000303380, 0x5, 0x8, 0x2766016b, 0xc0005bfb7f, 0x1, 0x1, 0xc0004c4ff0, 0x2f)
        github.com/Mrs4s/go-cqhttp/coolq/event.go:31 +0xaf
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).formatGroupMessage(0xc00010c300, 0xc0005fcbe0, 0xec5140)
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:498 +0x228
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).groupMessageEvent(0xc00010c300, 0xc000308000, 0xc0005fcbe0)
        github.com/Mrs4s/go-cqhttp/coolq/event.go:103 +0x345
github.com/Mrs4s/MiraiGo/client.(*QQClient).dispatchGroupMessage.func1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20210810070836-6614d2383adb/client/events.go:206 +0x3a
github.com/Mrs4s/MiraiGo/client.cover(0xc0005bfe30)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210810070836-6614d2383adb/client/events.go:488 +0x49
github.com/Mrs4s/MiraiGo/client.(*QQClient).dispatchGroupMessage(0xc000308000, 0xc0005fcbe0)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210810070836-6614d2383adb/client/events.go:205 +0x9a
github.com/Mrs4s/MiraiGo/client.decodeGroupMessagePacket(0xc000308000, 0xc0002252c0, 0xc0002be5a0, 0x1c5, 0x1c5, 0xc000280001, 0xc000000004, 0xebcc3b, 0x23)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210810070836-6614d2383adb/client/group_msg.go:330 +0x555
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc000308000, 0xc000599c70)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210810070836-6614d2383adb/client/network.go:211 +0x194
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20210810070836-6614d2383adb/client/network.go:201 +0x3d7

```
**复现方法**

直接启动

**Comment by 2938137849** [comment]
就算一直报错, 但是群消息和事件接收还是正常, 但是我好像不能主动发送消息, 否则就会断线

**Comment by Ink-33** [comment]
已知bug，请在后续版本中验证是否正确
