### ISSUE TITLE
发送消息报错

### ISSUE THREAD

**Issue by Ailitonia** [Mrs4s/go-cqhttp#1114]
**环境信息**

go-cqhttp版本: 1.0.0-beta7-fix2
运行环境: windows server 2012r2
连接方式: 反向ws
使用协议: ipad

**在最新的release版本中能否复现**
不确定

**bug内容**

可在任意时刻发生，bot发送消息时报错，消息发送失败，表现为api调用超时，报错时发送的消息没有规律，报错似乎是随机出现的

日志：
```
[2021-10-15 19:50:46] [DEBUG]: WS接收到API调用: send_msg 参数: {"user_id": ****, "group_id": ****, "message_type": "group", "message": [{"type": "text", "data": {"text": "****"}}]} 
[2021-10-15 19:50:46] [DEBUG]: Protocol -> rev pkt: MultiMsg.ApplyUp seq: 13923 
[2021-10-15 19:50:46] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbSendMsg seq: 13924 
[2021-10-15 19:50:47] [DEBUG]: Protocol -> rev pkt: OnlinePush.PbPushGroupMsg seq: 30565 
[2021-10-15 19:50:47] [DEBUG]: 向WS服务器 127.0.0.1:**** 推送Event: {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":****,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":55,"packet_sent":48,"packet_lost":0,"message_received":1,"message_sent":1,"disconnect_times":1,"lost_times":0,"last_message_time":1634298639}},"time":1634298647}
 
[2021-10-15 19:50:47] [DEBUG]: Protocol -> rev pkt: MultiMsg.ApplyDown seq: 13925 
[2021-10-15 19:50:47] [ERROR]: Protocol -> panic on decoder MultiMsg.ApplyDown : runtime error: invalid memory address or nil pointer dereference
goroutine 190 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
	github.com/Mrs4s/MiraiGo@v0.0.0-20210916113136-0238b2382b82/client/network.go:223 +0x5d
panic({0xbf2320, 0x1408ef0})
	runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/utils.HttpGetBytes.func1()
	github.com/Mrs4s/MiraiGo@v0.0.0-20210916113136-0238b2382b82/utils/http.go:23 +0x1c
github.com/Mrs4s/MiraiGo/utils.HttpGetBytes({0xc000634480, 0x4}, {0x0, 0x2})
	github.com/Mrs4s/MiraiGo@v0.0.0-20210916113136-0238b2382b82/utils/http.go:25 +0xb4
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse(0xc000080900, 0x228, {0xc000080900, 0x228, 0x228})
	github.com/Mrs4s/MiraiGo@v0.0.0-20210916113136-0238b2382b82/client/multimsg.go:103 +0x1bc
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc000544a50)
	github.com/Mrs4s/MiraiGo@v0.0.0-20210916113136-0238b2382b82/client/network.go:233 +0x1cb
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
	github.com/Mrs4s/MiraiGo@v0.0.0-20210916113136-0238b2382b82/client/network.go:220 +0x525
```

**复现方法**

可在任意时刻发生，调用 send_group_msg 发送任意消息，随机出现，出现后就会一直持续不断

**Comment by Mrs4s** [comment]
在服务器上输入 curl https://ssl.htdata.qq.com 试试

**Comment by Mrs4s** [comment]
> ![image](https://user-images.githubusercontent.com/41713304/137488195-268fb1bb-ba48-4702-9f8d-982d671d8d2c.png)
> 
> 手动更换 DNS 后

再试试会不会报错？

**Comment by Ailitonia** [comment]
> 再试试会不会报错？

![image](https://user-images.githubusercontent.com/41713304/137489954-86fd0cb7-200f-4bef-ac2f-146220eb01f0.png)

一样还是502

**Comment by Mrs4s** [comment]
> > 再试试会不会报错？
> 
> ![image](https://user-images.githubusercontent.com/41713304/137489954-86fd0cb7-200f-4bef-ac2f-146220eb01f0.png)
> 
> 一样还是502

我说发消息…

**Comment by Ailitonia** [comment]
> 我说发消息…

小学语文了😂

目前看起来暂时没有问题，先 close 了
