### ISSUE TITLE
处置WS命令时发生无法恢复的异常

### ISSUE THREAD

**Issue by xxyy3130** [Mrs4s/go-cqhttp#1141]
**环境信息**

go-cqhttp版本: v1.0.0-beta7-fix2
运行环境: amd64
连接方式: ws
使用协议: 企点

**在最新的release版本中能否复现**
偶尔出现
**bug内容**

发送长消息时偶尔出现，WS会断开
![image](https://user-images.githubusercontent.com/61443746/140553434-7276afe0-43ae-4aa9-9889-4e01e9c2a9f4.png)

**复现方法**

**Comment by clacknya** [comment]
这里刚好也出现了，看上去在某些操作超时时会出现

<details>
<summary>CQHTTP LOG</summary>
<pre>
[2021-11-06 06:32:12] [WARNING]: 警告: 群 ********* 消息图片上传失败: Packet timed out
[2021-11-06 06:32:42] [ERROR]: Protocol -> upload long message error: Packet timed out
[2021-11-06 06:32:42] [INFO]: 处置WS命令时发生无法恢复的异常：runtime error: invalid memory address or nil pointer dereference
goroutine 13310 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/go-cqhttp/server.(*webSocketConn).handleRequest.func1()
        github.com/Mrs4s/go-cqhttp/server/websocket.go:372 +0x45
panic({0xbd4f40, 0x13d4090})
        runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/message.(*ServiceElement).Pack(0x0)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210916113136-0238b2382b82/message/pack.go:84 +0x2e
github.com/Mrs4s/MiraiGo/message.ToProtoElems({0xc00035f070, 0x1, 0xc0002799c0}, 0x1)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210916113136-0238b2382b82/message/message.go:283 +0x595
github.com/Mrs4s/MiraiGo/client.(*QQClient).buildGroupSendingPacket(0xc0001e8000, 0x35b707b0, 0x4421596a, 0x1, 0x0, 0x0, 0x0, {0xc00035f070, 0x1, 0x1})
        github.com/Mrs4s/MiraiGo@v0.0.0-20210916113136-0238b2382b82/client/group_msg.go:246 +0x1a6
github.com/Mrs4s/MiraiGo/client.(*QQClient).sendGroupMessage(0xc0001e8000, 0x35b707b0, 0x0, 0xc000789198)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210916113136-0238b2382b82/client/group_msg.go:129 +0x2f3
github.com/Mrs4s/MiraiGo/client.(*QQClient).SendGroupMessage(0xc0001e8000, 0xc0001ff320, 0xc000789450, {0xc000789237, 0xc0007892f8, 0x3})
        github.com/Mrs4s/MiraiGo@v0.0.0-20210916113136-0238b2382b82/client/group_msg.go:55 +0x25f
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).SendGroupMessage(0xc0003ca2d0, 0x2, 0xc000789450)
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:299 +0x158
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendGroupMessage(0xc0003ca2d0, 0xcdc75c, {0x5, {0xc00034e069, 0x178}, {0x0, 0x0}, 0x0, 0x4b}, 0x0)
        github.com/Mrs4s/go-cqhttp/coolq/api.go:428 +0x292
github.com/Mrs4s/go-cqhttp/server.sendMSG(0xbc7a80, {0xde94a0, 0xc0005afdc0})
        github.com/Mrs4s/go-cqhttp/server/api.go:71 +0x73e
github.com/Mrs4s/go-cqhttp/server.(*apiCaller).callAPI(0xc0000666c0, {0xc00034e00b, 0x8}, {0xde94a0, 0xc0005afdc0})
        github.com/Mrs4s/go-cqhttp/server/api.go:440 +0x314
github.com/Mrs4s/go-cqhttp/server.(*webSocketConn).handleRequest(0xc00034bbf0, 0xc0003ca2d0, {0xc00034e000, 0x1f8, 0x798})
        github.com/Mrs4s/go-cqhttp/server/websocket.go:379 +0x5f3
github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI.func2(0xc0003d7780)
        github.com/Mrs4s/go-cqhttp/server/websocket.go:226 +0x95
created by github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI
        github.com/Mrs4s/go-cqhttp/server/websocket.go:224 +0x19d

[2021-11-06 06:32:42] [WARNING]: 监听反向WS API时出现错误: read tcp 127.0.0.1:60552->127.0.0.1:9223: use of closed network connection
[2021-11-06 06:32:44] [WARNING]: 向WS服务器 127.0.0.1:9223 推送Event时出现错误: write tcp 127.0.0.1:60552->127.0.0.1:9223: use of closed network connection
[2021-11-06 06:32:47] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:9223/ws/
</pre>
</details>

<details>
<summary>BOT LOG</summary>
<pre>
[2021-11-06 06:32:42,719 pulipuli] ERROR: <class 'aiocqhttp.exceptions.NetworkError'> occured when pulipuli handling message -2044146281.
[2021-11-06 06:32:42,720 pulipuli] ERROR: WebSocket API call timeout
Traceback (most recent call last):
  File "/opt/pyenv/versions/3.9.6/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError
<br>
The above exception was the direct cause of the following exception:
<br>
Traceback (most recent call last):
  File "/home/HoshinoBot/.local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 104, in fetch
    return await asyncio.wait_for(future, timeout_sec)
  File "/opt/pyenv/versions/3.9.6/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
<br>
During handling of the above exception, another exception occurred:
<br>
Traceback (most recent call last):
  File "/home/HoshinoBot/HoshinoBot/hoshino/service.py", line 192, in wrapper
    return await func(self.bot, ctx)
  File "/home/HoshinoBot/HoshinoBot/hoshino/modules/pulipuli/pulipuli.py", line 139, in pulipuli
    await bot.send(event, reply)
  File "/home/HoshinoBot/.local/lib/python3.9/site-packages/aiocqhttp/__init__.py", line 271, in send
    return await self.send_msg(**params)
  File "/home/HoshinoBot/.local/lib/python3.9/site-packages/aiocqhttp/__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "/home/HoshinoBot/.local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/home/HoshinoBot/.local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 153, in call_action
    return _handle_api_result(await
  File "/home/HoshinoBot/.local/lib/python3.9/site-packages/aiocqhttp/api_impl.py", line 108, in fetch
    raise NetworkError('WebSocket API call timeout')
aiocqhttp.exceptions.NetworkError: WebSocket API call timeout
</pre>
</details>
