### ISSUE TITLE
[Bug]: 调用send_msg时出现panic on decoder MultiMsg.ApplyDown : runtime error: invalid memory address or nil pointer dereference报错

### ISSUE THREAD

**Issue by assassingyk** [Mrs4s/go-cqhttp#1177]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [x] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [x] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta7-fix2

### 运行环境

CentOS

### 运行架构

AMD

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 在最新的 Release 版本中能否复现

- [ ] 能

### 重现步骤

同一账号保持登录一段时间后调用send_msg

### 期望的结果是什么？

正常回复

### 实际的结果是什么？

没有回复，报错panic on decoder MultiMsg.ApplyDown : runtime error: invalid memory address or nil pointer dereference

### 日志记录（可选）

```golang
[2021-11-18 09:38:03] [DEBUG]: WS接收到API调用: send_msg 参数: {"group_id": ***, "message_type": "group", "user_id": ***, "message": "\u306f\u3044\uff01\u79c1\u306f\u3044\u3064\u3082\u8cb4\u65b9\u306e\u5074\u306b\u3044\u307e\u3059\u3088\uff01"}
[2021-11-18 09:38:03] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbSendMsg seq: 13966
[2021-11-18 09:38:06] [DEBUG]: 向WS服务器 127.0.0.1:18088 推送Event: {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":***,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":136,"packet_sent":99,"packet_lost":0,"message_received":31,"message_sent":0,"disconnect_times":1,"lost_times":0,"last_message_time":1637199483}},"time":1637199486}

[2021-11-18 09:38:08] [DEBUG]: Protocol -> rev pkt: OidbSvc.0x88d_0 seq: 13967
[2021-11-18 09:38:08] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbGetGroupMsg seq: 13968
[2021-11-18 09:38:08] [DEBUG]: Protocol -> rev pkt: OnlinePush.PbPushGroupMsg seq: 6960

[2021-11-18 09:38:08] [DEBUG]: Protocol -> rev pkt: MultiMsg.ApplyDown seq: 13969
[2021-11-18 09:38:08] [ERROR]: Protocol -> panic on decoder MultiMsg.ApplyDown : runtime error: invalid memory address or nil pointer dereference
goroutine 397 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20210916113136-0238b2382b82/client/network.go:223 +0x5d
panic({0xbd4f40, 0x13d4090})
        runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/utils.HttpGetBytes.func1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20210916113136-0238b2382b82/utils/http.go:23 +0x1c
github.com/Mrs4s/MiraiGo/utils.HttpGetBytes({0xc000680900, 0x4}, {0x0, 0x2})
        github.com/Mrs4s/MiraiGo@v0.0.0-20210916113136-0238b2382b82/utils/http.go:25 +0xb4
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse(0xc00026a6c0, 0x23b, {0xc00026a6c0, 0x23b, 0x23b})
        github.com/Mrs4s/MiraiGo@v0.0.0-20210916113136-0238b2382b82/client/multimsg.go:103 +0x1bc
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0002b0a00)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210916113136-0238b2382b82/client/network.go:233 +0x1cb
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20210916113136-0238b2382b82/client/network.go:220 +0x525
```

### 补充说明（可选）

似乎和session有关，同一账号发生问题后多次重启仍稳定复现，删除session切换账号后无法复现，重新切换回原账号后也无法再复现

**Comment by Ink-33** [comment]
不用理会那个issue bot。更新了issue上报模板但是这个bot还没更新

**Comment by assassingyk** [comment]
换了个号挂了这有十几个小时吧又开始重新出现这个问题了，不过这次是只有报错，但消息实际上是成功发送出来了。

试了下在不动session文件的前提下换其他版本的go，发现beta5和beta6能复现，beta8-fix1没有复现……

**Comment by Mrs4s** [comment]
如果使用的是腾讯云服务器, 请修改DNS到114.114.114.114, 这个问题是因为DNS被污染导致的, 我们没办法解决
