### ISSUE TITLE
[Bug]: 反向websocket，在websocket意外断开后不能重新连接

### ISSUE THREAD

**Issue by felinae98** [Mrs4s/go-cqhttp#1236]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix1

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 在最新的 Release 版本中能否复现

- [ ] 能

### 重现步骤

websocket出现意外关闭后不能正确重启
**版本 v1.0.0-beta8-fix2**

### 期望的结果是什么？

websocket意外关闭后重启启动一个websocket

### 实际的结果是什么？

websocket意外关闭后并没有重新启动，消息一只推送到已经关闭的websocket中。

### 日志记录（可选）

```golang
[2021-12-10 06:08:13] [INFO]: 收到群 会客厅(xxxxx) 内 xxxx(29xxxxxxxxx) 的消息: [生气] (187xxxxxx) 
[2021-12-10 06:08:14] [INFO]: 收到群 会客厅(xxxxx) 内 队友呢在交火时有没有人可不可以来帮一下(xxxxxxx) 的消息: [CQ:image,file=22aa82dc502cdfde6dfxxxxxxxxxxx.image,subType=1] (xxxxxxx) 
[2021-12-10 06:08:17] [INFO]: 收到群 会客厅(867920571) 内 亚可(B》(xxxxxxx) 的消息: [CQ:reply,id=xxxxxxx][CQ:at,qq=xxxxxxx] [CQ:at,qq=xxxxxxx] 我超 (xxxxxxxx) 

[2021-12-10 06:08:18] [INFO]: 处置WS命令时发生无法恢复的异常：interface conversion: interface {} is nil, not uint32
goroutine 51005 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest.func1()
        /build/server/websocket.go:449 +0x45
panic({0xac0960, 0xc000291b30})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).ConvertContentMessage(0xac3ce0, {0xc0001d7bc0, 0x4, 0x8}, 0x0)
        /build/coolq/cqcode.go:816 +0x11a8
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQGetMessage(0x3, 0x3cc02f)
        /build/coolq/api.go:1486 +0x8f1
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).call(0xc0002eb400, {0xc0003cc00c, 0x7}, {0xc7baa0, 0xc000920820})
        /build/modules/api/api.go:158 +0x1a5
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).Call(0xc0002eb400, {0xc0003cc00c, 0x7}, {0xc7baa0, 0xc000920820})
        /build/modules/api/caller.go:34 +0xaa
github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest(0xc00033c930, 0xc0003281b0, {0xc0003cc000, 0x53, 0xda18})
        /build/server/websocket.go:456 +0x525
github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI.func2(0xc00034a240)
        /build/server/websocket.go:303 +0x95
created by github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI
        /build/server/websocket.go:301 +0x1b2

2021-12-10 06:08:18] [WARNING]: 监听反向WS Universal时出现错误: read tcp 172.18.0.10:33666->172.18.0.11:8080: use of closed network connection 
[2021-12-10 06:08:20] [WARNING]: 向反向WS Universal服务器推送 Event 时出现错误: write tcp 172.18.0.10:33666->172.18.0.11:8080: use of closed network connection 
[2021-12-10 06:08:25] [WARNING]: 向反向WS Universal服务器推送 Event 时出现错误: write tcp 172.18.0.10:33666->172.18.0.11:8080: use of closed network connection 
[2021-12-10 06:08:30] [WARNING]: 向反向WS Universal服务器推送 Event 时出现错误: write tcp 172.18.0.10:33666->172.18.0.11:8080: use of closed network connection 
[2021-12-10 06:08:35] [WARNING]: 向反向WS Universal服务器推送 Event 时出现错误: write tcp 172.18.0.10:33666->172.18.0.11:8080: use of closed network connection 
[2021-12-10 06:08:40] [WARNING]: 向反向WS Universal服务器推送 Event 时出现错误: write tcp 172.18.0.10:33666->172.18.0.11:8080: use of closed network connection 
[2021-12-10 06:08:45] [WARNING]: 向反向WS Universal服务器推送 Event 时出现错误: write tcp 172.18.0.10:33666->172.18.0.11:8080: use of closed network connection 
[2021-12-10 06:08:50] [WARNING]: 向反向WS Universal服务器推送 Event 时出现错误: write tcp 172.18.0.10:33666->172.18.0.11:8080: use of closed network connection 
[2021-12-10 06:08:55] [WARNING]: 向反向WS Universal服务器推送 Event 时出现错误: write tcp 172.18.0.10:33666->172.18.0.11:8080: use of closed network connection 
[2021-12-10 06:09:00] [WARNING]: 向反向WS Universal服务器推送 Event 时出现错误: write tcp 172.18.0.10:33666->172.18.0.11:8080: use of closed network connection
```

### 补充说明（可选）

在业务端没有看到对应websocket报错（可能是因为log等级不够）

**Comment by felinae98** [comment]
另，另一个bot出现了以下问题然后退出，原因不明：
```
panic: runtime error: makeslice: len out of range

goroutine 112 [running]:
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211208080234-25c67a3ee1c1/binary/reader.go:40
github.com/Mrs4s/MiraiGo/internal/packets.parseSsoFrame({0xc0002f5907, 0xc00000ea40, 0xc0004cda40}, 0x1)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211208080234-25c67a3ee1c1/internal/packets/global.go:145 +0x1a7
github.com/Mrs4s/MiraiGo/internal/packets.ParseIncomingPacket({0xc000349b80, 0xc000324480, 0x0}, {0xc0004cda40, 0x10, 0x10})
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211208080234-25c67a3ee1c1/internal/packets/global.go:136 +0x38f
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0xc0000a8480)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:296 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:121 +0x307
```

**Comment by felinae98** [comment]
在rc3中依旧会出现
