### ISSUE TITLE
[bug]get_forward_msg 不能正常使用

### ISSUE THREAD

**Issue by gitlsl** [Mrs4s/go-cqhttp#1251]
get_forward_msg?id=%2FJACq%2B719gmOMMAoIzCioSgJpO5nVM34%2B562MllIUZKh1ggcjzt6ub7RXiCGld1p

github 用模板 反馈问题 一直报错,  只能这样写了 

不管id 填的 对不对, 都是过好几秒返回 消息不存在
````
[2021-12-14 10:47:59] [ERROR]: Protocol -> panic on decoder MultiMsg.ApplyDown : runtime error: index out of range [0] with length 0
goroutine 1974 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:326 +0x5d
panic({0x114d500, 0xc0001ec150})
        runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse.func1(0xc0003d6270, 0x4)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/multimsg.go:102 +0x105
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse(0xc0003d6270, 0x9, {0xc0003d6270, 0x9, 0x9})
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/multimsg.go:103 +0x125
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc000386370)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:336 +0x1cb
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:323 +0x6c5
````

**Comment by Declarcall** [comment]
我 Ubuntu 18.04 x86_64 平台，问题跟楼上一样
```
GET get_forward_msg?message_id=1B8Cu9hAQTfqHmGcsAvWhPL9rMjknJdfzVdO7JNXAN7HXf+eijApY1TL75LiM+2b
```
panic 信息如下:
```
[2021-12-29 00:17:40] [ERROR]: Protocol -> panic on decoder MultiMsg.ApplyDown : runtime error: index out of range [0] with length 0
goroutine 1178 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
	github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:326 +0x5d
panic({0xb327a0, 0xc00060cb58})
	runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse.func1(0xc0006a3b10, 0x0)
	github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/multimsg.go:102 +0x105
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse(0xc0006a3b10, 0x9, {0xc0006a3b10, 0x9, 0x9})
	github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/multimsg.go:103 +0x125
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0002857c0)
	github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:336 +0x1cb
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
	github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:323 +0x6c5
```

**Comment by dannis999** [comment]
请问这个问题依旧没有解决吗，我现在用get_forward_msg获取消息依然提示 消息不存在

**Comment by sunzongzheng** [comment]
+1

**Comment by Happy2018new** [comment]
此问题无法再在 `1.1.0` 版本中复现。
