### ISSUE TITLE
[Bug]: 无法登录

### ISSUE THREAD

**Issue by RinChanNOWWW** [Mrs4s/go-cqhttp#1286]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix1

### 运行环境

Ubuntu

### 运行架构

x86

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

config.yaml:

```
# go-cqhttp 默认配置文件

account: # 账号相关
  uin: qq# QQ账号
  password: 'passwd' # 密码为空时使用扫码登录
  encrypt: false  # 是否开启密码加密
  status: 0      # 在线状态 请参考 https://docs.go-cqhttp.org/guide/config.html#在线状态
  relogin: # 重连设置
    delay: 3   # 首次重连延迟, 单位秒
    interval: 3   # 重连间隔
    max-times: 0  # 最大重连次数, 0为无限制

  # 是否使用服务器下发的新地址进行重连
  # 注意, 此设置可能导致在海外服务器上连接情况更差
  use-sso-address: true

heartbeat:
  # 心跳频率, 单位秒
  # -1 为关闭心跳
  interval: 5

message:
  # 上报数据类型
  # 可选: string,array
  post-format: array
  # 是否忽略无效的CQ码, 如果为假将原样发送
  ignore-invalid-cqcode: false
  # 是否强制分片发送消息
  # 分片发送将会带来更快的速度
  # 但是兼容性会有些问题
  force-fragment: false
  # 是否将url分片发送
  fix-url: false
  # 下载图片等请求网络代理
  proxy-rewrite: ''
  # 是否上报自身消息
  report-self-message: false
  # 移除服务端的Reply附带的At
  remove-reply-at: false
  # 为Reply附加更多信息
  extra-reply-data: false
  # 跳过 Mime 扫描, 忽略错误数据
  skip-mime-scan: false

output:
  # 日志等级 trace,debug,info,warn,error
  log-level: warn
  # 日志时效 单位天. 超过这个时间之前的日志将会被自动删除. 设置为 0 表示永久保留.
  log-aging: 15
  # 是否在每次启动时强制创建全新的文件储存日志. 为 false 的情况下将会在上次启动时创建的日志文件续写
  log-force-new: true
  # 是否启用日志颜色
  log-colorful: true
  # 是否启用 DEBUG
  debug: false # 开启调试模式

# 默认中间件锚点
default-middlewares: &default
  # 访问密钥, 强烈推荐在公网的服务器设置
  access-token: ''
  # 事件过滤器文件目录
  filter: ''
  # API限速设置
  # 该设置为全局生效
  # 原 cqhttp 虽然启用了 rate_limit 后缀, 但是基本没插件适配
  # 目前该限速设置为令牌桶算法, 请参考:
  # https://baike.baidu.com/item/%E4%BB%A4%E7%89%8C%E6%A1%B6%E7%AE%97%E6%B3%95/6597000?fr=aladdin
  rate-limit:
    enabled: false # 是否启用限速
    frequency: 1  # 令牌回复频率, 单位秒
    bucket: 1     # 令牌桶大小

database: # 数据库相关设置
  leveldb:
    # 是否启用内置leveldb数据库
    # 启用将会增加10-20MB的内存占用和一定的磁盘空间
    # 关闭将无法使用 撤回 回复 get_msg 等上下文相关功能
    enable: true

  # 媒体文件缓存， 删除此项则使用缓存文件(旧版行为)
  cache:
    image: data/image.db
    video: data/video.db

# 连接服务列表
servers:
  - http:
      host: 127.0.0.1
      port: 5700
      timeout: 5
      middlewares:
        <<: *default
  - ws-reverse:
      universal: ws://172.17.0.2:8080/cqhttp/ws # 这个是运行 bot 的 docker 容器的 ip
          # universal: ws://127.0.0.1:8080/cqhttp/ws
```

直接启动 

```bash
./go-cqhttp
```

### 期望的结果是什么？

成功登入

### 实际的结果是什么？

```
[2021-12-23 09:26:36] [INFO]: 当前版本:(devel) 
[2021-12-23 09:26:36] [INFO]: 用户交流群: 721829413 
[2021-12-23 09:26:36] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2021-12-23 09:26:36] [INFO]: 密码加密已启用, 请输入Key对密码进行解密以继续: (Enter 提交) 
[2021-12-23 09:26:40] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2021-12-23 09:26:45] [INFO]: 开始尝试登录并同步消息... 
[2021-12-23 09:26:45] [INFO]: 使用协议: iPad 
[2021-12-23 09:26:45] [INFO]: Protocol -> connect to server: 109.244.129.242:8080 
[2021-12-23 09:23:14] [ERROR]: Protocol -> decrypt payload error: unknown flag 
[2021-12-23 09:23:29] [ERROR]: Protocol -> decrypt payload error: unknown flag 
[2021-12-23 09:23:43] [FATAL]: 登录时发生致命错误: Packet timed out 
```

### 日志记录（可选）

```
[2021-12-22 01:07:44] [ERROR]: Protocol -> panic on decoder OnlinePush.ReqPush : runtime error: index out of range [0] with length 0
goroutine 300251 [running]:
runtime/debug.Stack()
    /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
    /home/rinchannow/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211122140519-ec4cd4a6f3fe/client/network.go:323 +0x5d
panic({0xc645c0, 0xc000036150})
    /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).readHead(...)
    /home/rinchannow/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211122140519-ec4cd4a6f3fe/binary/jce/reader.go:26
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).peakHead(...)
    /home/rinchannow/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211122140519-ec4cd4a6f3fe/binary/jce/reader.go:40
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).skipToTag(0xc00034a320, 0x0)
    /home/rinchannow/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211122140519-ec4cd4a6f3fe/binary/jce/reader.go:140 +0x16f
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).readMap(0xc00034a320, {0xbc8de0, 0xc0006ae630, 0xc00005ec38}, 0x40f765)
    /home/rinchannow/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211122140519-ec4cd4a6f3fe/binary/jce/reader.go:368 +0x73
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).ReadMap(0xc0004f6c00, {0xbc8de0, 0xc0006ae630}, 0xc00034a1ac)
    /home/rinchannow/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211122140519-ec4cd4a6f3fe/binary/jce/reader.go:364 +0xae
github.com/Mrs4s/MiraiGo/binary/jce.(*RequestDataVersion2).ReadFrom(...)
    /home/rinchannow/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211122140519-ec4cd4a6f3fe/binary/jce/structs.go:583
github.com/Mrs4s/MiraiGo/client.decodeOnlinePushReqPacket(0xc0002c1b00, 0xc00034a2c0, {0xc0002f4120, 0x119, 0x119})
    /home/rinchannow/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211122140519-ec4cd4a6f3fe/client/online_push.go:29 +0x17b
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc00060a190)
    /home/rinchannow/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211122140519-ec4cd4a6f3fe/client/network.go:333 +0x1cb
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
    /home/rinchannow/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20211122140519-ec4cd4a6f3fe/client/network.go:320 +0x652
```

### 补充说明（可选）

昨天上午还能使用，今天早上发现 bot 没有正常推送消息，查看日志发现昨天存在数组越界的 panic（之前也遇到过，重启解决）。今天再启动的时候就启动不了了，错误日志见上面。

**Comment by sam01101** [comment]
过分了，请自重，至少提供一些参考数据。
你这样实在是过分了。

**Comment by RinChanNOWWW** [comment]
> 过分了，请自重，至少提供一些参考数据。 你这样实在是过分了。

已更新。

不好意思，我以为按照 template 填好就行。

**Comment by sam01101** [comment]
> > 过分了，请自重，至少提供一些参考数据。 你这样实在是过分了。
> 
> 已更新。
> 
> 不好意思，我以为按照 template 填好就行。

![](https://user-images.githubusercontent.com/2220320/146894028-00810d65-45ad-4315-8975-94914c877179.jpg)

**Comment by RinChanNOWWW** [comment]
更新到 v1.0.0-beta8-fix2 修复了
