### ISSUE TITLE
[Bug]: Bot创建后被拉入的第一个群聊在bot端显示全员禁言

### ISSUE THREAD

**Issue by KafCoppelia** [Mrs4s/go-cqhttp#1300]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已知晓并同意，如果我不遵循以下格式提交 Issue，或者我使用的并非最新版本，或者我没有提供足够的环境信息，我的 Issue 可能会被无条件自动关闭或/并锁定。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix2

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

根据Nonebot2文档创建Bot后，被邀请进入一个设置为**不允许任何人加入且不会被群号查找**的群。

### 期望的结果是什么？

Bot可以正常群聊

### 实际的结果是什么？

在bot端QQ显示“全员禁言中”，但该群未被全员禁言。之后，Bot被邀请进的别的群聊一切正常，可以群聊。

### 简单的复现代码/链接（可选）

```golang
在出现上述问题的群聊内：
@bot_name /echo OK
```

### 日志记录（可选）

```golang
go-cqhttp端输出
[2021-12-26 10:33:01] [ERROR]: Protocol -> sendPacket msg error: 120  
[2021-12-26 10:33:06] [WARNING]: 群消息发送失败: 账号可能被风控.
Nonebot端输出：
12-26 10:33:06 [ERROR] nonebot | Running matcher <Matcher from nonebot.plugins.echo, type=message, priority=1, temp=False> failed.
Traceback (most recent call last):
  File "/root/anaconda3/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/anaconda3/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/anaconda3/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/anaconda3/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/nb_cli/__init__.py", line 46, in run
    run_bot(file, app)
  File "/root/anaconda3/lib/python3.9/site-packages/nb_cli/handlers.py", line 52, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/__init__.py", line 278, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 256, in run
    uvicorn.run(
  File "/root/anaconda3/lib/python3.9/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/root/anaconda3/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/root/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/message.py", line 128, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "/root/anaconda3/lib/python3.9/site-packages/nonebot/message.py", line 156, in _run_matcher
    await matcher.run(bot, event, state)
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/matcher.py", line 597, in run
    await handler(self, bot, event, self.state)
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/handler.py", line 64, in __call__
    await self.func(
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/plugins/echo.py", line 29, in echo_escape
    await bot.send(message=event.get_message(), event=event)
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 471, in send
    return await self.send_msg(**params)
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 416, in call_api
    return await super().call_api(api, **data)
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/adapters/_bot.py", line 172, in call_api
    raise exception
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/adapters/_bot.py", line 155, in call_api
    result = await self._call_api(api, **data)
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 363, in _call_api
    return _handle_api_result(await ResultStore.fetch(
  File "/root/anaconda3/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 192, in _handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.cqhttp.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 76}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
```

### 补充说明（可选）

登陆Bot的QQ号进入该出现问题的群聊显示全员禁言中

**Comment by KafCoppelia** [comment]
解决了，是群管理开启了全员禁言，但群里只有Bot是普通群友，其余全是管理员🤣
