### ISSUE TITLE
[Bug]: 处置WS命令时发生无法恢复的异常：runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by idanran** [Mrs4s/go-cqhttp#1357]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://github.com/Mrs4s/go-cqhttp/issues/633)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-beta8-fix2

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

随机出现

### 期望的结果是什么？

不报错

### 实际的结果是什么？

报错

### 日志记录（可选）

```golang
[INFO]: 处置WS命令时发生无法恢复的异常：runtime error: invalid memory address or nil pointer dereference
goroutine 639 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest.func1()
        github.com/Mrs4s/go-cqhttp/server/websocket.go:449 +0x45
panic({0x130f940, 0x19af050})
        runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/client.(*GuildService).SendGuildChannelMessage(0xc00008a280, 0x94e14ba9cf074c, 0x2f0ca7, 0xc000298680)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/guild_msg.go:88 +0x5d3
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).SendGuildChannelMessage(0xc000578090, 0x1, 0x79, 0xc000298680)
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:388 +0x11e
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendGuildChannelMessage(0xc000578090, 0x94e14ba9cf074c, 0xc000225b60, {0x3, {0xc00028806d, 0x7b}, {0xc00028806e, 0x79}, 0x0, 0x6d, ...}, ...)
        github.com/Mrs4s/go-cqhttp/coolq/api.go:707 +0x2d8
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).call(0xc000287300, {0xc00028800b, 0x16}, {0x14def40, 0xc000304b40})
        github.com/Mrs4s/go-cqhttp/modules/api/api.go:200 +0x7e4d
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).Call(0xc000287300, {0xc00028800b, 0x16}, {0x14def40, 0xc000304b40})
        github.com/Mrs4s/go-cqhttp/modules/api/caller.go:34 +0xaa
github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest(0xc0003023d8, 0x19c6f20, {0xc000288000, 0xc0003044b0, 0x0})
        github.com/Mrs4s/go-cqhttp/server/websocket.go:456 +0x525
github.com/Mrs4s/go-cqhttp/server.(*webSocketServer).listenAPI.func2(0xc0002c9a60)
        github.com/Mrs4s/go-cqhttp/server/websocket.go:438 +0x95
created by github.com/Mrs4s/go-cqhttp/server.(*webSocketServer).listenAPI
        github.com/Mrs4s/go-cqhttp/server/websocket.go:436 +0x16f
```

**Comment by wdvxdr1123** [comment]
duplicate of #1312
