### ISSUE TITLE
[Bug]: 登录报错

### ISSUE THREAD

**Issue by gaqwe767** [Mrs4s/go-cqhttp#1402]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

[2022-03-03 09:49:39] [INFO]: 扫码成功, 请在手机端确认登录.
panic: runtime error: makeslice: len out of range

goroutine 16 [running]:
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/reader.go:40
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).readSSOFrame(0x47534872554d2e66, 0xc000251090, {0xc0001f2607, 0x11c8, 0x11c8})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:62 +0x185
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).ReadResponse(0xc0000b4100, {0xc0001f0000, 0x11db, 0x11db})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:51 +0x2a9
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0xc0000ce000)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:295 +0x1b2
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:120 +0x307

[2022-03-03 10:01:32] [WARNING]: 账号密码未配置, 将使用二维码登录.
[2022-03-03 10:01:32] [WARNING]: 将在 5秒 后继续.
[2022-03-03 10:01:37] [INFO]: 当前版本:v1.0.0-rc1
[2022-03-03 10:01:37] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2022-03-03 10:01:37] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2022-03-03 10:01:42] [INFO]: 开始尝试登录并同步消息...
[2022-03-03 10:01:42] [INFO]: 使用协议: iPad
[2022-03-03 10:01:42] [INFO]: Protocol -> connect to server: 120.232.69XXXXX
[2022-03-03 10:01:43] [INFO]: 请使用手机QQ扫描二维码 (qrcode.png) :
[2022-03-03 10:02:09] [INFO]: 扫码成功, 请在手机端确认登录.
[2022-03-03 10:02:12] [ERROR]: Protocol -> parse incoming packet error: packet dropped
[2022-03-03 10:02:42] [ERROR]: Protocol -> sync channel error: Packet failed to sendPacket: connection closed
[2022-03-03 10:02:42] [INFO]: 登录成功 欢迎使用: 灵梦
[2022-03-03 10:02:42] [INFO]: 开始加载好友列表...
[2022-03-03 10:02:42] [FATAL]: 遇到错误: Packet failed to sendPacket: connection closed

[2022-03-03 10:05:00] [INFO]: 当前版本:v1.0.0-rc1
[2022-03-03 10:05:00] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2022-03-03 10:05:00] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2022-03-03 10:05:05] [INFO]: 开始尝试登录并同步消息...
[2022-03-03 10:05:05] [INFO]: 使用协议: iPad
[2022-03-03 10:05:05] [INFO]: Protocol -> connect to server: 120.232.69XXXXX
panic: runtime error: makeslice: len out of range
上面是扫码登陆报错

下面是帐号密码登陆报错
goroutine 100 [running]:
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/reader.go:40
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).readSSOFrame(0x687b2a57793f463d, 0xc000251130, {0xc000438a87, 0x9b8, 0x9b8})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:62 +0x185
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).ReadResponse(0xc000398060, {0xc0004e4000, 0x9cb, 0x9cb})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:51 +0x2a9
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0xc0003a8000)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:295 +0x1b2
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:120 +0x307

### 期望的结果是什么？

成功登陆

### 实际的结果是什么？

登陆报错

### 补充说明（可选）

退回v1.0.0-beta8-fix2登陆正常，还有v1.0.0-rc1有时又可以登陆，但不生成session.token，运行一段时间又会报错，无法自动重登，原因未知。用v1.0.0-beta8-fix2版本登陆一次后，然后再换回v1.0.0-rc1又可以登陆了。

**Comment by gaqwe767** [comment]
风控问题已经解决，是IP问题，重启一下路由器换了个IP就好了，不过奇怪的是其他框架没问题。至于登陆报错的不太清楚啥问题。

**Comment by gaqwe767** [comment]
但是过了一会又风控，现在换IP也不行，机器人号换了一个登陆依然如此。

**Comment by Yuki-Nagato** [comment]
同样的问题

**Comment by gaqwe767** [comment]
> 的问题全部



> 同样的问题

风控我挂几天就好了，或者 强制分片发送消息，但只能解决一部分问题，有一些还信息还是发不出去。你去帮助中心搜一下：分片 就可以看到了。

**Comment by Gingmzmzx** [comment]
我是一毛一样的报错，开了登陆保护验证再登陆还依然是报错

**Comment by 250king** [comment]
隔壁Mirai就不会出现这种问题，但因为不支持频道所以才跳坑到这边（
