### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hegu365** [Mrs4s/go-cqhttp#1409]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1 及 前面大部分版本

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

4 | 企点

### 重现步骤

登录

### 期望的结果是什么？

登录成功，并可以正常 加载好友列表完成并进行使用

### 实际的结果是什么？

[2022-03-06 11:56:08] [INFO]: 当前版本:v1.0.0-rc1
[2022-03-06 11:56:08] [WARNING]: 已开启Debug模式.
[2022-03-06 11:56:08] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2022-03-06 11:56:08] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2022-03-06 11:56:13] [INFO]: 开始尝试登录并同步消息...
[2022-03-06 11:56:13] [INFO]: 使用协议: 企点
[2022-03-06 11:56:14] [INFO]: Protocol -> connect to server: 49.7.253.220:8080
[2022-03-06 11:56:14] [DEBUG]: Protocol -> rev pkt: wtlogin.exchange_emp seq: 13878
[2022-03-06 11:56:14] [DEBUG]: Protocol -> decode pkt wtlogin.exchange_emp error: exchange_emp failed: 233
github.com/Mrs4s/MiraiGo/client.decodeExchangeEmpResponse
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/decoders.go:207
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:343
runtime.goexit
        runtime/asm_amd64.s:1581
[2022-03-06 11:56:14] [WARNING]: 恢复会话失败: exchange_emp failed: 233 , 尝试使用正常流程登录.
[2022-03-06 11:56:15] [DEBUG]: Protocol -> planned disconnect.
[2022-03-06 11:56:15] [INFO]: Protocol -> connect to server: 49.7.253.219:8080
[2022-03-06 11:56:16] [DEBUG]: Protocol -> rev pkt: wtlogin.login seq: 13878
[2022-03-06 11:56:16] [DEBUG]: Protocol -> rev pkt: StatSvc.register seq: 13879
[2022-03-06 11:56:16] [DEBUG]: Protocol -> rev pkt: ProfileService.Pb.ReqSystemMsgNew.Group seq: 13880
[2022-03-06 11:56:16] [DEBUG]: Protocol -> unknown group system msg: 0
[2022-03-06 11:56:16] [DEBUG]: Protocol -> unknown group system msg: 0
[2022-03-06 11:56:16] [DEBUG]: Protocol -> rev pkt: ProfileService.Pb.ReqSystemMsgNew.Group seq: 13881
[2022-03-06 11:56:16] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.GetMsgV2 seq: -1293579096
[2022-03-06 11:56:16] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.getOffMsg seq: 13882
[2022-03-06 11:56:16] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.PushParam seq: -1293579095
[2022-03-06 11:56:16] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.PbGetMsg seq: -1293579094
[2022-03-06 11:56:16] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.NoticeEnd seq: -1293579093
[2022-03-06 11:56:16] [DEBUG]: Protocol -> rev pkt: StatSvc.GetDevLoginInfo seq: 13884
[2022-03-06 11:56:16] [DEBUG]: Protocol -> rev pkt: qidianservice.69 seq: 13883
[2022-03-06 11:56:16] [DEBUG]: Protocol -> decode pkt qidianservice.69 error: login process resp is nil
github.com/Mrs4s/MiraiGo/client.decodeLoginExtraResponse
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/qidian.go:161
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:343
runtime.goexit
        runtime/asm_amd64.s:1581
[2022-03-06 11:56:16] [DEBUG]: Protocol -> rev pkt: HttpConn.0x6ff_501 seq: 13885
[2022-03-06 11:56:16] [DEBUG]: Protocol -> decode pkt HttpConn.0x6ff_501 error: please call login extra before
github.com/Mrs4s/MiraiGo/client.decodeConnKeyResponse
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/qidian.go:177
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:343
runtime.goexit
        runtime/asm_amd64.s:1581
[2022-03-06 11:56:17] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbGetMsg seq: 13886
[2022-03-06 11:56:17] [DEBUG]: Protocol -> rev pkt: trpc.group_pro.synclogic.SyncLogic.SyncFirstView seq: 13887
[2022-03-06 11:56:17] [DEBUG]: Protocol -> rev pkt: trpc.group_pro.synclogic.SyncLogic.PushFirstView seq: -1293578596
[2022-03-06 11:56:17] [DEBUG]: Protocol -> rev pkt: trpc.group_pro.synclogic.SyncLogic.PushFirstView seq: -1293578596
[2022-03-06 11:56:17] [DEBUG]: Protocol -> rev pkt: OidbSvcTrpcTcp.0xfc9_1 seq: 13888
[2022-03-06 11:56:17] [INFO]: 登录成功 欢迎使用: 查件机器人
[2022-03-06 11:56:17] [INFO]: 开始加载好友列表...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6e70cb]

goroutine 1 [running]:
github.com/Mrs4s/MiraiGo/client.(*QQClient).getQiDianAddressDetailList(0xc0002ac580)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/qidian.go:32 +0x6b
github.com/Mrs4s/MiraiGo/client.(*QQClient).GetFriendList(0xc00013a000)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/client.go:504 +0x3d
github.com/Mrs4s/MiraiGo/client.(*QQClient).ReloadFriendList(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/client.go:491
github.com/Mrs4s/go-cqhttp/cmd/gocq.Main()
        github.com/Mrs4s/go-cqhttp/cmd/gocq/main.go:314 +0x1905
main.main()
        github.com/Mrs4s/go-cqhttp/main.go:13 +0x17

### 补充说明（可选）

前一个版本

[2022-03-06 12:01:14] [INFO]: 当前版本:v1.0.0-beta8-fix2
[2022-03-06 12:01:14] [WARNING]: 已开启Debug模式.
[2022-03-06 12:01:14] [DEBUG]: 开发交流群: 192548878
[2022-03-06 12:01:14] [INFO]: 用户交流群: 721829413
[2022-03-06 12:01:14] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2022-03-06 12:01:14] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2022-03-06 12:01:19] [INFO]: 开始尝试登录并同步消息...
[2022-03-06 12:01:19] [INFO]: 使用协议: 企点
[2022-03-06 12:01:19] [INFO]: Protocol -> connect to server: 49.7.253.199:8080
[2022-03-06 12:01:19] [DEBUG]: Protocol -> rev pkt: wtlogin.exchange_emp seq: 13878
[2022-03-06 12:01:19] [ERROR]: Protocol -> exchange_emp error: 233
[2022-03-06 12:01:19] [DEBUG]: Protocol -> decode pkt wtlogin.exchange_emp error: exchange_emp failed
github.com/Mrs4s/MiraiGo/client.decodeExchangeEmpResponse
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/decoders.go:208
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:336
runtime.goexit
        runtime/asm_amd64.s:1581
[2022-03-06 12:01:19] [WARNING]: 恢复会话失败: exchange_emp failed , 尝试使用正常流程登录.
[2022-03-06 12:01:20] [DEBUG]: Protocol -> planned disconnect.
[2022-03-06 12:01:21] [INFO]: Protocol -> connect to server: 49.7.253.199:8080
[2022-03-06 12:01:21] [DEBUG]: Protocol -> rev pkt: wtlogin.login seq: 13878
[2022-03-06 12:01:21] [DEBUG]: Protocol -> rev pkt: StatSvc.register seq: 13879
[2022-03-06 12:01:21] [DEBUG]: Protocol -> rev pkt: ProfileService.Pb.ReqSystemMsgNew.Group seq: 13880
[2022-03-06 12:01:21] [ERROR]: Protocol -> unknown group msg: 0
[2022-03-06 12:01:22] [ERROR]: Protocol -> unknown group msg: 0
[2022-03-06 12:01:22] [DEBUG]: Protocol -> rev pkt: ProfileService.Pb.ReqSystemMsgNew.Group seq: 13881
[2022-03-06 12:01:22] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.GetMsgV2 seq: 36008
[2022-03-06 12:01:22] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.getOffMsg seq: 13882
[2022-03-06 12:01:22] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.PushParam seq: 36009
[2022-03-06 12:01:22] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.PbGetMsg seq: 36010
[2022-03-06 12:01:22] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.NoticeEnd seq: 36011
[2022-03-06 12:01:22] [DEBUG]: Protocol -> rev pkt: StatSvc.GetDevLoginInfo seq: 13884
[2022-03-06 12:01:22] [DEBUG]: Protocol -> rev pkt: qidianservice.69 seq: 13883
[2022-03-06 12:01:22] [DEBUG]: Protocol -> decode pkt qidianservice.69 error: login process resp is nil
github.com/Mrs4s/MiraiGo/client.decodeLoginExtraResponse
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/qidian.go:165
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:336
runtime.goexit
        runtime/asm_amd64.s:1581
[2022-03-06 12:01:22] [DEBUG]: Protocol -> rev pkt: HttpConn.0x6ff_501 seq: 13885
[2022-03-06 12:01:22] [DEBUG]: Protocol -> decode pkt HttpConn.0x6ff_501 error: please call login extra before
github.com/Mrs4s/MiraiGo/client.decodeConnKeyResponse
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/qidian.go:181
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/network.go:336
runtime.goexit
        runtime/asm_amd64.s:1581
[2022-03-06 12:01:22] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbGetMsg seq: 13886
[2022-03-06 12:01:22] [DEBUG]: Protocol -> rev pkt: trpc.group_pro.synclogic.SyncLogic.SyncFirstView seq: 13887
[2022-03-06 12:01:22] [DEBUG]: Protocol -> rev pkt: trpc.group_pro.synclogic.SyncLogic.PushFirstView seq: 36508
[2022-03-06 12:01:22] [DEBUG]: Protocol -> rev pkt: trpc.group_pro.synclogic.SyncLogic.PushFirstView seq: 36508
[2022-03-06 12:01:22] [DEBUG]: Protocol -> rev pkt: OidbSvcTrpcTcp.0xfc9_1 seq: 13888
[2022-03-06 12:01:22] [INFO]: 登录成功 欢迎使用: 查件机器人
[2022-03-06 12:01:22] [INFO]: 开始加载好友列表...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xb335eb]

goroutine 1 [running]:
github.com/Mrs4s/MiraiGo/client.(*QQClient).getQiDianAddressDetailList(0xc000480000)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/qidian.go:32 +0x6b
github.com/Mrs4s/MiraiGo/client.(*QQClient).GetFriendList(0xc00016c000)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/client.go:521 +0x3d
github.com/Mrs4s/MiraiGo/client.(*QQClient).ReloadFriendList(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20211208080234-25c67a3ee1c1/client/client.go:508
github.com/Mrs4s/go-cqhttp/cmd/gocq.Main()
        github.com/Mrs4s/go-cqhttp/cmd/gocq/main.go:330 +0x1a45
main.main()
        github.com/Mrs4s/go-cqhttp/main.go:13 +0x17

**Comment by YiwanGi** [comment]
[2022-04-01 18:16:01] [INFO]: 开始加载好友列表...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x12e70cb]

goroutine 1 [running]:
github.com/Mrs4s/MiraiGo/client.(*QQClient).getQiDianAddressDetailList(0xc0004d0000)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/qidian.go:32 +0x6b
github.com/Mrs4s/MiraiGo/client.(*QQClient).GetFriendList(0xc000182000)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/client.go:504 +0x3d
github.com/Mrs4s/MiraiGo/client.(*QQClient).ReloadFriendList(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/client.go:491
github.com/Mrs4s/go-cqhttp/cmd/gocq.Main()
        github.com/Mrs4s/go-cqhttp/cmd/gocq/main.go:314 +0x1905
main.main()
        github.com/Mrs4s/go-cqhttp/main.go:13 +0x17
