### ISSUE TITLE
Panic when function InsertGroupMessage with WebSocket

### ISSUE THREAD

**Issue by ChamberyChang** [Mrs4s/go-cqhttp#141]
**环境信息**
go-cqhttp版本: v0.9.19
运行环境: debian9_amd64
连接方式: WS

**bug内容**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8e4915]

goroutine 41 [running]:
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).InsertGroupMessage(0xc000076680, 0x0, 0xc0001bfc38)
        /github/workspace/coolq/bot.go:153 +0x45
  thub.com/Mrs4s/go-cqhttp/coolq.(*CQBot).SendGroupMessage(0xc000076680, 0x3647db8c, 0xc0001bfc38, 0x601)
        /github/workspace/coolq/bot.go:120 +0x14a
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendGroupMessage(0xc000076680, 0x3647db8c, 0xc648e0, 0xc000149da8, 0x0)
        /github/workspace/coolq/api.go:136 +0x22e
github.com/Mrs4s/go-cqhttp/server.glob..func9(0xc000076680, 0x5, 0xc00008c704, 0x10d, 0x0, 0x0, 0x0, 0x24, 0x6)
        /github/workspace/server/websocket.go:355 +0x16d
github.com/Mrs4s/go-cqhttp/server.(*websocketServer).listenApi(0x1310aa0, 0xc0004ab340)
        /github/workspace/server/websocket.go:287 +0x50a
created by github.com/Mrs4s/go-cqhttp/server.(*websocketServer).api
        /github/workspace/server/websocket.go:251 +0x1c6
```

**复现方法**
从websocket发送令bot读取群聊内图片的指令，并指示其在响应语句中插入图片的过程中，bot在未完成应答前即崩溃结束进程。

另外，私聊内发送图片、群聊发送图片而不触发其响应、群聊内指示其响应文字、群聊内指示其发单张图片的过程中，均不会触发问题导致崩溃。

**Comment by Mrs4s** [comment]
发送图片数量是不是太多了

**Comment by Mrs4s** [comment]
我检查了下代码，只有在发送消息过长的情况下有可能触发这个问题

**Comment by ChamberyChang** [comment]
那为什么私聊或者直接对话都没有问题，偏偏群聊会出现这个问题呢

**Comment by Mrs4s** [comment]
总之已经修复了, 是一处边界检查没做好的问题
