### ISSUE TITLE
[Bug]: 发送图片引发的报错，无论是Steam或者file格式都报错

### ISSUE THREAD

**Issue by 764763903a** [Mrs4s/go-cqhttp#1413]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1/包括以上版本  运行环

### 运行环境

CentOS

### 运行架构

AMD64

### 连接方式

LambdaServer

### 使用协议

0 | iPad

### 重现步骤

当机器人回复照片得时候

### 期望的结果是什么？

正常发送图片

### 实际的结果是什么？

异常，且报错

### 简单的复现代码/链接（可选）

```golang
wd, _ := os.Getwd()
					file, _ := ioutil.ReadFile(wd + "/output.jpg")
					bot.SendPrivateMessage(uid, models.Config.QQGroupID, &message.SendingMessage{Elements: []message.IMessageElement{&coolq.LocalImageElement{Stream: bytes.NewReader(file)}}})
```

### 日志记录（可选）

```golang
[2022-03-08 03:06:26] [INFO]: 收到好友 天天向上(xxxxxx) 的消息: https://kpl.m.jd.com/product?wareId=10028363691164&amp;utm_source=iosapp&amp;utm_medium=liteshare&amp;utm_campaign=t_335139774&amp;utm_term=CopyURL&amp;ad_od=share&amp;utm_user=plusmember (473479339) 
[2022-03-08 03:06:28] [INFO]: 开始发送图片 
event error: runtime error: invalid memory address or nil pointer dereference
goroutine 708 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.cover.func1()
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220209092529-5d071b034c17/client/events.go:597 +0x39
panic({0x105f120, 0x1ce5960})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/Mrs4s/go-cqhttp/internal/btree.(*DB).Insert(0x0, 0x1cea1c0, {0xc0017b2180, 0x50, 0xc001361528})
        /usr/local/go/path/pkg/mod/github.com/764763903a/go-cqhttp@v1.0.4/internal/btree/btree.go:473 +0x30
github.com/Mrs4s/go-cqhttp/internal/cache.(*Cache).Insert(0x1d91240, {0xc0009ce100, 0x10, 0x11f80ca}, {0xc0017b2180, 0xb9, 0xc0})
        /usr/local/go/path/pkg/mod/github.com/764763903a/go-cqhttp@v1.0.4/internal/cache/cache.go:35 +0xdd
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).checkMedia(0xc00060f4d0, {0xc0004ce110, 0x1, 0x1}, 0x5d4e0d78)
        /usr/local/go/path/pkg/mod/github.com/764763903a/go-cqhttp@v1.0.4/coolq/event.go:775 +0x11c
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).SendPrivateMessage(0xc00060f4d0, 0x2d955eff, 0x1c4791dc, 0xc001361a08)
        /usr/local/go/path/pkg/mod/github.com/764763903a/go-cqhttp@v1.0.4/coolq/bot.go:291 +0xec
github.com/cdle/xdd/qbot.Main.func1(0x2d955eff, {0x10111e0, 0xc0004ce080})
        /opt/xdd-plus/qbot/main.go:80 +0x3cb
github.com/cdle/xdd/models.glob..func5(0xc000b6c4d0, {0xc000e66600, 0xbb})
        /opt/xdd-plus/models/bot.go:59 +0xfe
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).privateMessageEvent(0xc00060f4d0, 0xc0011a0840, 0xc000584fc0)
        /usr/local/go/path/pkg/mod/github.com/764763903a/go-cqhttp@v1.0.4/coolq/event.go:44 +0x22d
github.com/Mrs4s/MiraiGo/client.(*QQClient).dispatchPrivateMessage.func1()
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220209092529-5d071b034c17/client/events.go:219 +0x28
github.com/Mrs4s/MiraiGo/client.cover(0xc00136fbf0)
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220209092529-5d071b034c17/client/events.go:600 +0x3e
github.com/Mrs4s/MiraiGo/client.(*QQClient).dispatchPrivateMessage(0xc0011a0840, 0xc000584fc0)
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220209092529-5d071b034c17/client/events.go:218 +0x91
github.com/Mrs4s/MiraiGo/client.privateMessageDecoder(0xc0011a0840, 0xc00158ac00, 0x29)
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220209092529-5d071b034c17/client/c2c_processor.go:124 +0x112
github.com/Mrs4s/MiraiGo/client.(*QQClient).commMsgProcessor(0xc0011a0840, 0xc001089170, 0xc0015c47c0)
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220209092529-5d071b034c17/client/c2c_processor.go:96 +0x527
github.com/Mrs4s/MiraiGo/client.(*QQClient).c2cMessageSyncProcessor(0xc0011a0840, 0xc00060f710, 0xc0015c47c0)
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220209092529-5d071b034c17/client/c2c_processor.go:67 +0x5be
github.com/Mrs4s/MiraiGo/client.decodeMessageSvcPacket(0xc0017a9500, 0x961, {0xc0017a9500, 0x961, 0x961})
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220209092529-5d071b034c17/client/decoders.go:379 +0xa5
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc001511a90)
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220209092529-5d071b034c17/client/network.go:343 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        /usr/local/go/path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220209092529-5d071b034c17/client/network.go:329 +0x697
```

### 补充说明（可选）

代码如上

**Comment by 764763903a** [comment]
测试过dev 依旧不行

**Comment by wdvxdr1123** [comment]
非发行版不提供支持

**Comment by 764763903a** [comment]
> 非发行版不提供支持

也就是版本要回退到0.94?
