### ISSUE TITLE
[Bug]: 登录时报错

### ISSUE THREAD

**Issue by Gingmzmzx** [Mrs4s/go-cqhttp#1439]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0-rc1

### 运行环境

Linux

### 运行架构

x86

### 连接方式

HTTP

### 使用协议

3 | MacOS

### 重现步骤

./go-cqhttp启动就会遇到报错
报错有很多种
[root@mail yzxzb]# ./go-cqhttp
[2022-03-24 09:32:14] [INFO]: 当前版本:v1.0.0-rc1 
[2022-03-24 09:32:14] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2022-03-24 09:32:14] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2022-03-24 09:32:19] [INFO]: 开始尝试登录并同步消息... 
[2022-03-24 09:32:19] [INFO]: 使用协议: iPad 
[2022-03-24 09:32:22] [INFO]: Protocol -> connect to server: 203.205.255.220:8080 
[2022-03-24 09:32:24] [ERROR]: Protocol -> parse incoming packet error: packet dropped 
[2022-03-24 09:32:54] [ERROR]: Protocol -> sync channel error: Packet failed to sendPacket: connection closed 
[2022-03-24 09:32:54] [INFO]: 登录成功 欢迎使用: 一只小猪比 
[2022-03-24 09:32:54] [INFO]: 开始加载好友列表... 
[2022-03-24 09:32:54] [FATAL]: 遇到错误: Packet failed to sendPacket: connection closed 

[root@mail yzxzb]# ./go-cqhttp
[2022-03-24 09:39:50] [INFO]: 当前版本:v1.0.0-rc1 
[2022-03-24 09:39:50] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2022-03-24 09:39:50] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2022-03-24 09:39:55] [INFO]: 开始尝试登录并同步消息... 
[2022-03-24 09:39:55] [INFO]: 使用协议: iPad 
[2022-03-24 09:39:57] [INFO]: Protocol -> connect to server: 203.205.255.220:8080 
panic: runtime error: makeslice: len out of range

goroutine 37 [running]:
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/reader.go:40
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).readSSOFrame(0x74355b496b426358, 0xc0003628c0, {0xc00013a236, 0x70, 0x70})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:62 +0x185
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).ReadResponse(0xc00057bb40, {0xc0006162d0, 0x84, 0x84})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:51 +0x2a9
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0xc00017c580)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:295 +0x1b2
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:120 +0x307

还有一种是加载群列表时报错panic: runtime error: makeslice: len out of range

### 期望的结果是什么？

正常登录

### 实际的结果是什么？

报错退出

**Comment by Gingmzmzx** [comment]
[dumps.zip](https://github.com/Mrs4s/go-cqhttp/files/8337741/dumps.zip)

**Comment by ytxh** [comment]
我也遇到了这个问题

**Comment by zhtyirg3** [comment]
这个可以解决吗，是因为国外服务器的问题吗？我也是这个问题

**Comment by daseinem** [comment]
./go-cqhttp -faststart                                                                                                                                                                 ─╯
[2022-03-27 21:39:05] [INFO]: 当前版本:v1.0.0-rc1
[2022-03-27 21:39:05] [WARNING]: 已开启Debug模式.
[2022-03-27 21:39:05] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2022-03-27 21:39:05] [INFO]: 开始尝试登录并同步消息...
[2022-03-27 21:39:05] [INFO]: 使用协议: Android Phone
[2022-03-27 21:39:07] [INFO]: Protocol -> connect to server: 203.205.255.220:8080
[2022-03-27 21:39:07] [DEBUG]: Protocol -> rev pkt: wtlogin.login seq: 13878
[2022-03-27 21:39:07] [DEBUG]: Protocol -> rev pkt: wtlogin.login seq: 13879
[2022-03-27 21:39:08] [DEBUG]: Protocol -> rev pkt: StatSvc.register seq: 13880
[2022-03-27 21:39:08] [DEBUG]: Protocol -> rev pkt: ProfileService.Pb.ReqSystemMsgNew.Group seq: 13881
[2022-03-27 21:39:08] [DEBUG]: Protocol -> rev pkt: OnlinePush.SidTicketExpired seq: -559562783
[2022-03-27 21:39:08] [DEBUG]: Protocol -> rev pkt: ProfileService.Pb.ReqSystemMsgNew.Group seq: 13882
[2022-03-27 21:39:08] [DEBUG]: Protocol -> rev pkt: wtlogin.exchange_emp seq: 13883
[2022-03-27 21:39:09] [ERROR]: Protocol -> parse incoming packet error: packet dropped
[2022-03-27 21:39:09] [DEBUG]: Protocol -> planned disconnect.
[2022-03-27 21:39:38] [ERROR]: Protocol -> sync channel error: Packet failed to sendPacket: connection closed
[2022-03-27 21:39:38] [INFO]: 登录成功 欢迎使用: **
[2022-03-27 21:39:38] [INFO]: 开始加载好友列表...
[2022-03-27 21:39:38] [FATAL]: 遇到错误: Packet failed to sendPacket: connection closed

最新dev分支也是一样。
同服务器测试其他Q号正常，配置文件和设备文件不变，换其他服务器不能登录，换家宽IP登录正常。

**Comment by Gingmzmzx** [comment]
> 

我也是同服务器测试其他Q号正常

**Comment by Gingmzmzx** [comment]
我是临时用beta8-fix2跑的

**Comment by clacknya** [comment]
同遇到这个问题，根据 #1402 ，使用 v1.0.0-beta8-fix2 可正常工作
