### ISSUE TITLE
[Bug]: 突然出现的无法登陆。

### ISSUE THREAD

**Issue by DavidYin166** [Mrs4s/go-cqhttp#1448]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [x] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0-rc1

### 运行环境

Ubuntu

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

不需要什么特别的方法，就是直接运行程序。
sudo ./go-cqhttp
或者
./go-cqhttp

### 期望的结果是什么？

正常登陆并开始处理消息

### 实际的结果是什么？

无法登陆。
会出现两种错误，每次不一定出现哪一个。（姑且称为错误A和错误B）
错误A是白字，提示切片超出范围，。（也许意味着A错误实际上是登录成功了）
错误B是红字、橙字，看上去像是网络问题，但是我有尝试更换不同地区、不同平台的设备进行测试，都出现了相同的问题，那么也许可能并不是网络问题。
（具体的错误信息我会在下方附上）

### 简单的复现代码/链接（可选）

```golang
sudo ./go-cqhttp
或者
./go-cqhttp
```

### 日志记录（可选）

```golang
以下是错误A的日志：
abc@abc-desktop:~/go-cqhttp2$ sudo ./go-cqhttp
[sudo] abc 的密码：
WARN[0000] post-format 配置错误, 将自动使用 string
[2022-03-31 11:49:26] [WARNING]: 账号密码未配置, 将使用二维码登录.
[2022-03-31 11:49:26] [WARNING]: 将在 5秒 后继续.
[2022-03-31 11:49:31] [INFO]: 当前版本:v1.0.0-rc1
[2022-03-31 11:49:31] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2022-03-31 11:49:31] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2022-03-31 11:49:36] [INFO]: 开始尝试登录并同步消息...
[2022-03-31 11:49:36] [INFO]: 使用协议: iPad
[2022-03-31 11:49:37] [INFO]: Protocol -> connect to server: 60.29.238.126:8080
[2022-03-31 11:49:37] [INFO]: 请使用手机QQ扫描二维码 (qrcode.png) :


（这些空白的地方就是二维码，有很多行，复制不过来）


[2022-03-31 11:49:47] [INFO]: 扫码成功, 请在手机端确认登录.
panic: runtime error: makeslice: len out of range

goroutine 88 [running]:
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/reader.go:40
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).readSSOFrame(0x4000132060, 0x4000334730, {0x400027b603, 0x4fe, 0x505})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:62 +0x170
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).ReadResponse(0x4000132060, {0x400027ab00, 0x51b, 0x51b})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:51 +0x310
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0x400013e000)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:295 +0x188
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:120 +0x3f4
abc@abc-desktop:~/go-cqhttp2$
以上是错误A的日志。





以下是错误B的日志：
abc@abc-desktop:~/go-cqhttp2$ sudo ./go-cqhttp_arm64
WARN[0000] post-format 配置错误, 将自动使用 string
[2022-03-31 11:54:45] [WARNING]: 账号密码未配置, 将使用二维码登录.
[2022-03-31 11:54:45] [WARNING]: 将在 5秒 后继续.
[2022-03-31 11:54:50] [INFO]: 当前版本:550c17c
[2022-03-31 11:54:50] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2022-03-31 11:54:50] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2022-03-31 11:54:55] [INFO]: 开始尝试登录并同步消息...
[2022-03-31 11:54:55] [INFO]: 使用协议: iPad
[2022-03-31 11:54:56] [INFO]: Protocol -> connect to server: 123.125.0.172:8080
[2022-03-31 11:54:56] [INFO]: 请使用手机QQ扫描二维码 (qrcode.png) :


（这些空白的地方就是二维码，有很多行，复制不过来）


[2022-03-31 11:55:09] [INFO]: 扫码成功, 请在手机端确认登录.
[2022-03-31 11:55:11] [WARNING]: Protocol -> device lock is disable. http api may fail.（选择不同的登录协议，这句可能出现也可能不出现）
[2022-03-31 11:55:12] [ERROR]: Protocol -> parse incoming packet error: packet dropped
[2022-03-31 11:55:42] [ERROR]: Protocol -> sync channel error: Packet failed to sendPacket: connection closed
[2022-03-31 11:55:42] [INFO]: 登录成功 欢迎使用: Biu
[2022-03-31 11:55:42] [INFO]: 开始加载好友列表...
[2022-03-31 11:55:42] [FATAL]: 遇到错误: Packet failed to sendPacket: connection closed
abc@abc-desktop:~/go-cqhttp2$
以上是错误B的日志。
```

### 补充说明（可选）

尝试了cqhttp自带的5种协议，均没有解决问题。
尝试过的平台
arm_x86
arm_x64
win_x64
Ubuntu_18.04.5_LTS_x64
CentOS_7.6_x64

以下是Debug模式下的A错误：
abc@abc-desktop:~/go-cqhttp2$ ./go-cqhttp -D
WARN[0000] post-format 配置错误, 将自动使用 string
[2022-03-31 12:46:22] [WARNING]: 账号密码未配置, 将使用二维码登录.
[2022-03-31 12:46:22] [WARNING]: 将在 5秒 后继续.
[2022-03-31 12:46:27] [INFO]: 当前版本:v1.0.0-rc1
[2022-03-31 12:46:27] [WARNING]: 已开启Debug模式.
[2022-03-31 12:46:27] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2022-03-31 12:46:27] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2022-03-31 12:46:32] [INFO]: 开始尝试登录并同步消息...
[2022-03-31 12:46:32] [INFO]: 使用协议: iPad
[2022-03-31 12:46:33] [INFO]: Protocol -> connect to server: 220.194.118.217:8080
[2022-03-31 12:46:33] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13878
[2022-03-31 12:46:33] [INFO]: 请使用手机QQ扫描二维码 (qrcode.png) :

（假装有二维码）

[2022-03-31 12:46:34] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13879
[2022-03-31 12:46:35] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13880
[2022-03-31 12:46:36] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13881
[2022-03-31 12:46:37] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13882
[2022-03-31 12:46:38] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13883
[2022-03-31 12:46:40] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13884
[2022-03-31 12:46:40] [INFO]: 扫码成功, 请在手机端确认登录.
[2022-03-31 12:46:41] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13885
[2022-03-31 12:46:42] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13886
[2022-03-31 12:46:42] [DEBUG]: Protocol -> rev pkt: wtlogin.login seq: 13887
[2022-03-31 12:46:42] [DEBUG]: Protocol -> rev pkt: StatSvc.register seq: 13888
[2022-03-31 12:46:42] [DEBUG]: Protocol -> rev pkt: ProfileService.Pb.ReqSystemMsgNew.Group seq: 13889
[2022-03-31 12:46:42] [DEBUG]: Protocol -> rev pkt: ProfileService.Pb.ReqSystemMsgNew.Group seq: 13890
[2022-03-31 12:46:43] [DEBUG]: Protocol -> rev pkt: OnlinePush.SidTicketExpired seq: -17541638988
[2022-03-31 12:46:43] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.GetMsgV2 seq: -1754163896
[2022-03-31 12:46:43] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.getOffMsg seq: 13891
[2022-03-31 12:46:43] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.PushParam seq: -1754163895
[2022-03-31 12:46:43] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.PbGetMsg seq: -1754163894
[2022-03-31 12:46:43] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.NoticeEnd seq: -1754163893
[2022-03-31 12:46:43] [DEBUG]: Protocol -> rev pkt: wtlogin.exchange_emp seq: 13892
[2022-03-31 12:46:43] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbGetMsg seq: 13894
panic: runtime error: makeslice: len out of range

goroutine 31 [running]:
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/reader.go:40
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).readSSOFrame(0x4000390060, 0x40000a2be0, {0x4000030d87, 0x42a, 0x431})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:62 +0x170
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).ReadResponse(0x4000390060, {0x4000030480, 0x44b, 0x44b})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:51 +0x310
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0x4000396000)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:295 +0x188
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:120 +0x3f4
abc@abc-desktop:~/go-cqhttp2$
以上是Debug模式下的A错误。

以下是Debug模式下的B错误：
abc@abc-desktop:~/go-cqhttp2$ ./go-cqhttp -D
WARN[0000] post-format 配置错误, 将自动使用 string
[2022-03-31 12:24:17] [WARNING]: 账号密码未配置, 将使用二维码登录.
[2022-03-31 12:24:17] [WARNING]: 将在 5秒 后继续.
[2022-03-31 12:24:22] [INFO]: 当前版本:v1.0.0-rc1
[2022-03-31 12:24:22] [WARNING]: 已开启Debug模式.
[2022-03-31 12:24:22] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2022-03-31 12:24:22] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2022-03-31 12:24:27] [INFO]: 开始尝试登录并同步消息...
[2022-03-31 12:24:27] [INFO]: 使用协议: iPad
[2022-03-31 12:24:28] [INFO]: Protocol -> connect to server: 60.29.237.176:8080
[2022-03-31 12:24:28] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13878
[2022-03-31 12:24:28] [INFO]: 请使用手机QQ扫描二维码 (qrcode.png) :

（假装有二维码）

[2022-03-31 12:24:29] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13879
[2022-03-31 12:24:31] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13880
[2022-03-31 12:24:32] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13881
[2022-03-31 12:24:33] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13882
[2022-03-31 12:24:34] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13883
[2022-03-31 12:24:35] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13884
[2022-03-31 12:24:36] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13885
[2022-03-31 12:24:36] [INFO]: 扫码成功, 请在手机端确认登录.
[2022-03-31 12:24:37] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13886
[2022-03-31 12:24:38] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13887
[2022-03-31 12:24:39] [DEBUG]: Protocol -> rev pkt: wtlogin.trans_emp seq: 13888
[2022-03-31 12:24:40] [DEBUG]: Protocol -> rev pkt: wtlogin.login seq: 13889
[2022-03-31 12:24:40] [DEBUG]: Protocol -> rev pkt: StatSvc.register seq: 13890
[2022-03-31 12:24:40] [DEBUG]: Protocol -> rev pkt: ProfileService.Pb.ReqSystemMsgNew.Group seq: 13891
[2022-03-31 12:24:40] [DEBUG]: Protocol -> rev pkt: OnlinePush.SidTicketExpired seq: -1820040632
[2022-03-31 12:24:40] [DEBUG]: Protocol -> rev pkt: ProfileService.Pb.ReqSystemMsgNew.Group seq: 13892
[2022-03-31 12:24:40] [DEBUG]: Protocol -> rev pkt: wtlogin.exchange_emp seq: 13893
[2022-03-31 12:24:40] [ERROR]: Protocol -> parse incoming packet error: packet dropped
[2022-03-31 12:24:40] [DEBUG]: Protocol -> planned disconnect.
[2022-03-31 12:25:10] [ERROR]: Protocol -> sync channel error: Packet failed to sendPacket: connection closed
[2022-03-31 12:25:10] [INFO]: 登录成功 欢迎使用: Biu
[2022-03-31 12:25:10] [INFO]: 开始加载好友列表...
[2022-03-31 12:25:10] [FATAL]: 遇到错误: Packet failed to sendPacket: connection closed
abc@abc-desktop:~/go-cqhttp2$
以上是Debug模式下的B错误。

**Comment by RrowR** [comment]
同B错误

**Comment by YidaozhanYa** [comment]
我这边换用真实设备的 device.json 即可

**Comment by DavidYin166** [comment]
> 我这边换用真实设备的 device.json 即可

咦？原来可以使用真实设备的device.json吗？求教一下怎么获取真是设备的device.json，谢谢啦！

**Comment by YidaozhanYa** [comment]
我是从手机上AIDA64一行一行抄的...不过这也不是长久之计，用了几次之后又那样了

**Comment by SanaChitose** [comment]
疑似二维码登录出现问题，我先用的短信验证码登录解决了

**Comment by yukino0x** [comment]
请问你解决了吗

**Comment by QinCaii** [comment]
> 疑似二维码登录出现问题，我先用的短信验证码登录解决了

怎么用短信登录呀？还能用短信的么

**Comment by elongpaoxiao** [comment]
先从本地电脑上跑一次，然后把device.json和session.token复制到服务器就可以解决

**Comment by sanshanya** [comment]
我出现过这问题，删除远古时期生成的device.json，生成新的就解决了

**Comment by IceCapriccio** [comment]
> 

感谢，删除device.json后我也ok了
