### ISSUE TITLE
处理频道撤回事件时出现错误: 获取操作者资料时出现错误

### ISSUE THREAD

**Issue by moian98** [Mrs4s/go-cqhttp#1483]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0 rc1

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

重新步骤好像是随机的，不好复现。
经过反复观察，发现是“部分”频道用户修改了“当前频道昵称”后有几率出现。
不管是自己写的功能，还是nonebot2商店里下载安装的插件都有几率出现。
不管是自己写的功能，还是nonebot2商店里下载安装的插件都没用写“撤回事件”的相关功能。

### 期望的结果是什么？

正常输出各插件应该输出的内容

### 实际的结果是什么？

gocq控制台输出：
[2022-04-24 14:09:55] [INFO]: 收到来自频道 星瞳(51818971636******) 子频道 🕹️王者荣耀讨论区(204****) 内 热情不该被暮色掩埋(1441152187480****) 的消息:
 今日人品
[2022-04-24 14:09:55] [INFO]: 处置WS命令时发生无法恢复的异常：runtime error: invalid memory address or nil pointer dereference
goroutine 911878 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest.func1()
        github.com/Mrs4s/go-cqhttp/server/websocket.go:414 +0x45
panic({0xac5700, 0x1162e80})
        runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/client.(*GuildService).SendGuildChannelMessage(0xc00038a0a0, 0xb8191485085a1c, 0x1f2dc1, 0xc00098c4a8)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/guild_msg.go:88 +0x513
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).SendGuildChannelMessage(0xc000464000, 0x1, 0x117, 0xc00098c4a8)
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:399 +0x11f
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendGuildChannelMessage(0xc000464000, 0xb8191485085a1c, 0x0, {0x5, {0xc000b4c071, 0x117}, {0x0, 0x0}, 0x0,
 0x71, ...}, ...)
        github.com/Mrs4s/go-cqhttp/coolq/api.go:783 +0x2d8
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).call(0xc0002b4320, {0xc000b4c00c, 0x16}, {0xc951c0, 0xc000056730})
        github.com/Mrs4s/go-cqhttp/modules/api/api.go:212 +0x7d2d
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).Call(0xc0002b4320, {0xc000b4c00c, 0x16}, {0xc951c0, 0xc000056730})
        github.com/Mrs4s/go-cqhttp/modules/api/caller.go:34 +0xaa
github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest(0xc000388048, 0x7fe7a0, {0xc000b4c000, 0xc000056460, 0x0})
        github.com/Mrs4s/go-cqhttp/server/websocket.go:421 +0x525
github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI.func2(0xc0002b2080)
        github.com/Mrs4s/go-cqhttp/server/websocket.go:268 +0x95
created by github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI
        github.com/Mrs4s/go-cqhttp/server/websocket.go:266 +0x1b2

[2022-04-24 14:09:55] [WARNING]: 监听反向WS Universal时出现错误: read tcp 127.0.0.1:57210->127.0.0.1:56523: use of closed network connection
[2022-04-24 14:09:59] [WARNING]: 向反向WS Universal服务器推送 Event 时出现错误: write tcp 127.0.0.1:57210->127.0.0.1:56523: use of closed network conn ection
[2022-04-24 14:10:00] [ERROR]: 处理频道撤回事件时出现错误: 获取操作者资料时出现错误 fetch roles error: decode packet error: oidb result unsuccessful: 58002 msg: users not in guild 

### 日志记录（可选）

```golang
[2022-04-24 12:52:30] [ERROR]: 处理频道撤回事件时出现错误: 获取操作者资料时出现错误 fetch roles error: decode packet error: oidb result unsuccessful: 58002 msg: users not in guild 
[2022-04-24 12:52:35] [ERROR]: 处理频道撤回事件时出现错误: 获取操作者资料时出现错误 fetch roles error: decode packet error: oidb result unsuccessful: 58002 msg: users not in guild 
[2022-04-24 13:22:14] [ERROR]: 处理频道撤回事件时出现错误: 获取操作者资料时出现错误 fetch roles error: decode packet error: oidb result unsuccessful: 58002 msg: users not in guild 
[2022-04-24 13:32:25] [ERROR]: 处理频道撤回事件时出现错误: 获取操作者资料时出现错误 fetch roles error: decode packet error: oidb result unsuccessful: 58002 msg: users not in guild 
[2022-04-24 13:32:28] [ERROR]: 处理频道撤回事件时出现错误: 获取操作者资料时出现错误 fetch roles error: decode packet error: oidb result unsuccessful: 58002 msg: users not in guild 
[2022-04-24 13:32:29] [ERROR]: 处理频道撤回事件时出现错误: 获取操作者资料时出现错误 fetch roles error: decode packet error: oidb result unsuccessful: 58002 msg: users not in guild 
[2022-04-24 13:32:33] [ERROR]: 处理频道撤回事件时出现错误: 获取操作者资料时出现错误 fetch roles error: decode packet error: oidb result unsuccessful: 58002 msg: users not in guild 
[2022-04-24 13:32:45] [ERROR]: 处理频道撤回事件时出现错误: 获取操作者资料时出现错误 fetch roles error: decode packet error: oidb result unsuccessful: 58002 msg: users not in guild 
[2022-04-24 13:33:00] [ERROR]: 处理频道撤回事件时出现错误: 获取操作者资料时出现错误 fetch roles error: decode packet error: oidb result unsuccessful: 58002 msg: users not in guild 
[2022-04-24 13:33:04] [ERROR]: 处理频道撤回事件时出现错误: 获取操作者资料时出现错误 fetch roles error: decode packet error: oidb result unsuccessful: 58002 msg: users not in guild 
[2022-04-24 13:36:01] [ERROR]: 处理频道撤回事件时出现错误: 获取操作者资料时出现错误 fetch roles error: decode packet error: oidb result unsuccessful: 58002 msg: users not in guild 
[2022-04-24 13:36:20] [ERROR]: 处理频道撤回事件时出现错误: 获取操作者资料时出现错误 fetch roles error: decode packet error: oidb result unsuccessful: 58002 msg: users not in guild 
[2022-04-24 13:37:17] [ERROR]: 处理频道撤回事件时出现错误: 获取操作者资料时出现错误 fetch roles error: decode packet error: oidb result unsuccessful: 58002 msg: users not in guild 
[2022-04-24 13:37:51] [ERROR]: 处理频道撤回事件时出现错误: 获取操作者资料时出现错误 fetch roles error: decode packet error: oidb result unsuccessful: 58002 msg: users not in guild 
[2022-04-24 13:37:52] [ERROR]: 处理频道撤回事件时出现错误: 获取操作者资料时出现错误 fetch roles error: decode packet error: oidb result unsuccessful: 58002 msg: users not in guild
```

### 补充说明（可选）

再经过观察，我自己猜测是用户设置的QQ频道头像的问题，这些都有个共同点就是他们的头像在手机端频道能正常显示，但在PC端，头像就显示QQ的企鹅icon。

**Comment by moian98** [comment]
好像描述有误，我再研究一下。先关闭了

**Comment by GensouSakuya** [comment]
貌似是为某个频道单独设置了头像之后就会这样？🤔
