### ISSUE TITLE
[Bug]: 启动程序时, 报 "index out of range" 异常

### ISSUE THREAD

**Issue by SlimeNull** [Mrs4s/go-cqhttp#1486]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

1. 程序因为网络原因而断开连接, 然后 Ctrl+C 结束进程后, 重启程序后, 会有这样的报错
```
[2022-04-25 16:33:54] [ERROR]: Protocol -> panic on decoder ConfigPushSvc.PushReq : runtime error: index out of range [0] with length 0
goroutine 101 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:332 +0x5d
panic({0xbb2f80, 0xc00048e168})
        runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).peakHead(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/jce/reader.go:31
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).skipToTag(0xc000409de0, 0x8)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/jce/reader.go:149 +0x16d
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).ReadMapStrMapStrByte(0xc000409dc0, 0x47d8b4)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/jce/reader.go:426 +0x25
github.com/Mrs4s/MiraiGo/binary/jce.(*RequestDataVersion2).ReadFrom(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/jce/structs.go:552
github.com/Mrs4s/MiraiGo/client.decodePushReqPacket(0xc000221340, 0x3ec, {0xc0004be800, 0x15, 0x11eac80})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/decoders.go:307 +0x133
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0004ac230)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:343 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:329 +0x697

[2022-04-25 16:33:54] [ERROR]: 出现错误 packet decode error: ConfigPushSvc.PushReq - runtime error: index out of range [0] with length 0. 详细信息已转储至文件 dumps/1650875634.dump 请连同日志提交给开发者处理
```

dump 文件base64编码后的内容是:
```
AAAD7BACLDxMViNRUVNlcnZpY2UuQ29uZmlnUHVzaFN2Yy5NYWluU2VydmFudGYH
UHVzaFJlcX0AAQOrCAABBgdQdXNoUmVxGAABBhJDb25maWdQdXNoLlB1c2hSZXEd
AAEDgwoQAS0AAQN1GQAHChYNMTExLjIwNi45OS41MCEfkDABTFxgCHABhgJ0apYD
dW5prAsKFg0xMTEuMjA2Ljk5LjgwIFAwAUxcYAhwAYYCdGqWA3VuaawLChYOMTU3
LjE0OC41NC4xMDUhNrAwAUxcYAhwAYYCc3qWA3VuaawLChYOMTU3LjE0OC40Mi4x
NzQhAbswAUxcYAhwAYYCc3qWA3VuaawLChYOMTU3LjE0OC4zMi4xNjcgUDABTFxg
CHABhgJzepYDdW5prAsKFg0xMTEuMjA2Ljk5LjgwIFAwAUxcYAhwAYYCdGqWA3Vu
aawLChYRbXNmd2lmaS4zZy5xcS5jb20hH5AwAUxcYAh8hgZvdGhlcnOWBm90aGVy
c6wLOQAHChYNMTExLjIwNi45OS41MCEfkDABTFxgCHABhgJ0apYDdW5prAsKFg0x
MTEuMjA2Ljk5LjgwIFAwAUxcYAhwAYYCdGqWA3VuaawLChYOMTU3LjE0OC41NC4x
MDUhNrAwAUxcYAhwAYYCc3qWA3VuaawLChYOMTU3LjE0OC40Mi4xNzQhAbswAUxc
YAhwAYYCc3qWA3VuaawLChYOMTU3LjE0OC4zMi4xNjcgUDABTFxgCHABhgJzepYD
dW5prAsKFg0xMTEuMjA2Ljk5LjgwIFAwAUxcYAhwAYYCdGqWA3VuaawLChYRbXNm
d2lmaS4zZy5xcS5jb20hH5AwAUxcYAh8hgZvdGhlcnOWBm90aGVyc6wLTFxscAGJ
AAQKFg02MC4yOC4xNzIuMjMzIFAwAUxQA2AIfIYCdGqWA3VuaawLChYOMTU3LjE0
OC40Mi4xOTggUDABTFADYAh8hgJzepYDdW5prAsKFg02MC4yOC4xNzIuMjMzIFAw
AUxQA2AIfIYCc3qWA3VuaawLChYOMTU3LjE0OC40Mi4xOTggUDABTFADYAh8hgJ0
apYDdW5prAuZAAQKFg02MC4yOC4xNzIuMjMzIFAwAUxQA2AIfIYCdGqWA3VuaawL
ChYOMTU3LjE0OC40Mi4xOTggUDABTFADYAh8hgJzepYDdW5prAsKFg02MC4yOC4x
NzIuMjMzIFAwAUxQA2AIfIYCc3qWA3VuaawLChYOMTU3LjE0OC40Mi4xOTggUDAB
TFADYAh8hgJ0apYDdW5prAupDLkMyQzZDOz8D/YQAPwRMgAk+vELjJgMqAw=
```

这似乎是玄学 bug, 在我删去所有存储, 日志, 包括 device.json 后, 然后以于原来相同的 config.yml 运行 gocqhttp, 他同样可能会出现这个问题

而当我第三次重新删去所有数据后, 这个错误没有了, 但是还有另外一个错误:
```
[2022-04-25 16:35:03] [ERROR]: Protocol -> unexpected disconnect: EOF
```

这个出现在登录的时候, 但是并不影响消息的接收, gocqhttp 并不会因为这个而崩溃

### 期望的结果是什么？

期望程序处理好这些异常, 然后不显示 ERROR, 而是在妥善处理后, 显示 WARNING

### 实际的结果是什么？

```
Microsoft Windows [Version 10.0.22598.200]
(c) Microsoft Corporation. All rights reserved.

C:\NShare\Software\go-cqhttp>go-cqhttp.exe
[2022-04-25 16:28:47] [WARNING]: 账号密码未配置, 将使用二维码登录.
[2022-04-25 16:28:47] [WARNING]: 将在 5秒 后继续.
[2022-04-25 16:28:52] [INFO]: 当前版本:v1.0.0-rc1
[2022-04-25 16:28:52] [WARNING]: 虚拟设备信息不存在, 将自动生成随机设备.
[2022-04-25 16:28:52] [INFO]: 已生成设备信息并保存到 device.json 文件.
[2022-04-25 16:28:52] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2022-04-25 16:28:57] [INFO]: 开始尝试登录并同步消息...
[2022-04-25 16:28:57] [INFO]: 使用协议: iPad
[2022-04-25 16:28:58] [INFO]: Protocol -> connect to server: 112.80.130.224:8080
[2022-04-25 16:28:58] [INFO]: 请使用手机QQ扫描二维码 (qrcode.png) :

### 这里是二维码 ###

[2022-04-25 16:29:03] [INFO]: 扫码成功, 请在手机端确认登录.
[2022-04-25 16:29:10] [INFO]: 收到服务器地址更新通知, 将在下一次重连时应用.
[2022-04-25 16:29:21] [INFO]: 登录成功 欢迎使用: OpenSource
[2022-04-25 16:29:21] [INFO]: 开始加载好友列表...
[2022-04-25 16:29:22] [INFO]: 共加载 17 个好友.
[2022-04-25 16:29:22] [INFO]: 开始加载群列表...
[2022-04-25 16:29:22] [INFO]: 共加载 7 个群.
[2022-04-25 16:29:22] [INFO]: 资源初始化完成, 开始处理信息.
[2022-04-25 16:29:22] [INFO]: アトリは、高性能ですから!
[2022-04-25 16:29:22] [INFO]: CQ HTTP 服务器已启动: 127.0.0.1:5700
[2022-04-25 16:29:22] [INFO]: 正在检查更新.
[2022-04-25 16:29:22] [INFO]: CQ WebSocket 服务器已启动: 127.0.0.1:6700
[2022-04-25 16:29:22] [WARNING]: lambda 初始化失败: Post "http:///runtime/init/ready": http: no Host in request URL
[2022-04-25 16:29:26] [INFO]: 检查更新完成. 当前已运行最新版本.
[2022-04-25 16:29:27] [ERROR]: Protocol -> unexpected disconnect: EOF
[2022-04-25 16:29:27] [INFO]: Protocol -> connect to server: 220.194.118.224:80
[2022-04-25 16:29:27] [INFO]: 开始诊断网络情况
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x962c4a]

goroutine 214 [running]:
github.com/Mrs4s/go-cqhttp/internal/selfdiagnosis.NetworkDiagnosis(0xc000088040)
        github.com/Mrs4s/go-cqhttp/internal/selfdiagnosis/diagnoses.go:13 +0x6a
created by github.com/Mrs4s/go-cqhttp/cmd/gocq.Main.func5
        github.com/Mrs4s/go-cqhttp/cmd/gocq/main.go:331 +0x73

C:\NShare\Software\go-cqhttp>go-cqhttp.exe
[2022-04-25 16:32:12] [INFO]: 当前版本:v1.0.0-rc1
[2022-04-25 16:32:12] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2022-04-25 16:32:12] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2022-04-25 16:32:17] [INFO]: 开始尝试登录并同步消息...
[2022-04-25 16:32:17] [INFO]: 使用协议: iPad
[2022-04-25 16:32:18] [INFO]: Protocol -> connect to server: 112.80.130.224:8080
[2022-04-25 16:32:18] [INFO]: 收到服务器地址更新通知, 将在下一次重连时应用.
[2022-04-25 16:32:21] [INFO]: 登录成功 欢迎使用: OpenSource
[2022-04-25 16:32:21] [INFO]: 开始加载好友列表...
[2022-04-25 16:32:22] [INFO]: 共加载 17 个好友.
[2022-04-25 16:32:22] [INFO]: 开始加载群列表...
[2022-04-25 16:32:22] [INFO]: 共加载 7 个群.
[2022-04-25 16:32:22] [INFO]: 资源初始化完成, 开始处理信息.
[2022-04-25 16:32:22] [INFO]: アトリは、高性能ですから!
[2022-04-25 16:32:22] [INFO]: CQ HTTP 服务器已启动: 127.0.0.1:5700
[2022-04-25 16:32:22] [INFO]: CQ WebSocket 服务器已启动: 127.0.0.1:6700
[2022-04-25 16:32:22] [INFO]: 正在检查更新.
[2022-04-25 16:32:22] [WARNING]: lambda 初始化失败: Post "http:///runtime/init/ready": http: no Host in request URL
[2022-04-25 16:32:22] [INFO]: 检查更新完成. 当前已运行最新版本.
[2022-04-25 16:32:27] [INFO]: 开始诊断网络情况
[2022-04-25 16:32:29] [INFO]: 网络诊断完成. 未发现问题
[2022-04-25 16:32:37] [ERROR]: Protocol -> unexpected disconnect: EOF
[2022-04-25 16:32:37] [INFO]: Protocol -> connect to server: 220.194.118.236:80
[2022-04-25 16:32:40] [INFO]: 收到服务器地址更新通知, 将在下一次重连时应用.
[2022-04-25 16:33:21] [INFO]: 收到群 EleCho(XXX) 内 ʚ憨批诺尔ɞ(XXX) 的消息: ？ (-1137015017)
[2022-04-25 16:33:26] [ERROR]: Protocol -> unexpected disconnect: read tcp 192.168.8.103:32519->220.194.118.236:80: wsarecv: An established connection was aborted by the software in your host machine.
[2022-04-25 16:33:26] [INFO]: Protocol -> connect to server: 111.206.99.118:8080
[2022-04-25 16:33:26] [ERROR]: Protocol -> connect server error: dial tcp error: dial tcp 111.206.99.118:8080: connectex: A socket operation was attempted to an unreachable network.
[2022-04-25 16:33:26] [ERROR]: Protocol -> connect server error: dial tcp error: dial tcp 111.206.99.118:8080: connectex: A socket operation was attempted to an unreachable network.
[2022-04-25 16:33:26] [WARNING]: Bot已离线: connection dropped by server.
[2022-04-25 16:33:29] [WARNING]: 将在 3 秒后尝试重连. 重连次数：2/0
[2022-04-25 16:33:32] [WARNING]: 尝试重连...
[2022-04-25 16:33:32] [INFO]: Protocol -> connect to server: 157.148.57.99:80
[2022-04-25 16:33:33] [INFO]: 收到群 EleCho(XXX) 内 乌拉-折耳猫(XXX) 的消息: [CQ:at,qq=XXX] 看
私聊 (624154285)
[2022-04-25 16:33:34] [ERROR]: Protocol -> unexpected disconnect: read tcp 192.168.8.103:32731->157.148.57.99:80: wsarecv: An established connection was aborted by the software in your host machine.
[2022-04-25 16:33:34] [INFO]: Protocol -> connect to server: 220.194.118.224:14000
[2022-04-25 16:33:34] [ERROR]: Protocol -> connect server error: dial tcp error: dial tcp 220.194.118.224:14000: connectex: A socket operation was attempted to an unreachable network.
[2022-04-25 16:33:34] [ERROR]: Protocol -> connect server error: dial tcp error: dial tcp 220.194.118.224:14000: connectex: A socket operation was attempted to an unreachable network.

C:\NShare\Software\go-cqhttp>go-cqhttp.exe -faststart
[2022-04-25 16:33:54] [INFO]: 当前版本:v1.0.0-rc1
[2022-04-25 16:33:54] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2022-04-25 16:33:54] [INFO]: 开始尝试登录并同步消息...
[2022-04-25 16:33:54] [INFO]: 使用协议: iPad
[2022-04-25 16:33:54] [INFO]: Protocol -> connect to server: 112.80.130.241:8080
[2022-04-25 16:33:54] [ERROR]: Protocol -> panic on decoder ConfigPushSvc.PushReq : runtime error: index out of range [0] with length 0
goroutine 101 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:332 +0x5d
panic({0xbb2f80, 0xc00048e168})
        runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).peakHead(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/jce/reader.go:31
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).skipToTag(0xc000409de0, 0x8)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/jce/reader.go:149 +0x16d
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).ReadMapStrMapStrByte(0xc000409dc0, 0x47d8b4)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/jce/reader.go:426 +0x25
github.com/Mrs4s/MiraiGo/binary/jce.(*RequestDataVersion2).ReadFrom(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/jce/structs.go:552
github.com/Mrs4s/MiraiGo/client.decodePushReqPacket(0xc000221340, 0x3ec, {0xc0004be800, 0x15, 0x11eac80})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/decoders.go:307 +0x133
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0004ac230)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:343 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:329 +0x697

[2022-04-25 16:33:54] [ERROR]: 出现错误 packet decode error: ConfigPushSvc.PushReq - runtime error: index out of range [0] with length 0. 详细信息已转储至文件 dumps/1650875634.dump 请连同日志提交给开发者处理
[2022-04-25 16:33:58] [INFO]: 登录成功 欢迎使用: OpenSource
[2022-04-25 16:33:58] [INFO]: 开始加载好友列表...
[2022-04-25 16:33:58] [INFO]: 共加载 17 个好友.
[2022-04-25 16:33:58] [INFO]: 开始加载群列表...
[2022-04-25 16:33:59] [INFO]: 共加载 7 个群.
[2022-04-25 16:33:59] [INFO]: 资源初始化完成, 开始处理信息.
[2022-04-25 16:33:59] [INFO]: アトリは、高性能ですから!
[2022-04-25 16:33:59] [INFO]: CQ HTTP 服务器已启动: 127.0.0.1:5700
[2022-04-25 16:33:59] [INFO]: 正在检查更新.
[2022-04-25 16:33:59] [INFO]: CQ WebSocket 服务器已启动: 127.0.0.1:6700
[2022-04-25 16:33:59] [WARNING]: lambda 初始化失败: Post "http:///runtime/init/ready": http: no Host in request URL
[2022-04-25 16:33:59] [INFO]: 检查更新完成. 当前已运行最新版本.
[2022-04-25 16:34:04] [INFO]: 开始诊断网络情况
[2022-04-25 16:34:05] [INFO]: 网络诊断完成. 未发现问题
[2022-04-25 16:34:12] [ERROR]: Protocol -> unexpected disconnect: EOF
[2022-04-25 16:34:12] [INFO]: Protocol -> connect to server: 112.86.231.234:8080
[2022-04-25 16:34:12] [ERROR]: Protocol -> panic on decoder ConfigPushSvc.PushReq : runtime error: index out of range [0] with length 0
goroutine 190 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:332 +0x5d
panic({0xbb2f80, 0xc00048e258})
        runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).peakHead(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/jce/reader.go:31
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).skipToTag(0xc00065fde0, 0x8)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/jce/reader.go:149 +0x16d
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).ReadMapStrMapStrByte(0xc00065fdc0, 0x0)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/jce/reader.go:426 +0x25
github.com/Mrs4s/MiraiGo/binary/jce.(*RequestDataVersion2).ReadFrom(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/binary/jce/structs.go:552
github.com/Mrs4s/MiraiGo/client.decodePushReqPacket(0xc000221340, 0x3ea, {0xc000656000, 0x15, 0x0})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/decoders.go:307 +0x133
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0002c4550)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:343 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:329 +0x697

[2022-04-25 16:34:12] [ERROR]: 出现错误 packet decode error: ConfigPushSvc.PushReq - runtime error: index out of range [0] with length 0. 详细信息已转储至文件 dumps/1650875652.dump 请连同日志提交给开发者处理
[2022-04-25 16:34:28] [ERROR]: Protocol -> unexpected disconnect: EOF
[2022-04-25 16:34:28] [INFO]: Protocol -> connect to server: 116.147.18.148:8080
[2022-04-25 16:34:29] [INFO]: 收到服务器地址更新通知, 将在下一次重连时应用.
[2022-04-25 16:35:03] [ERROR]: Protocol -> unexpected disconnect: EOF
[2022-04-25 16:35:03] [INFO]: Protocol -> connect to server: 123.125.0.236:443
[2022-04-25 16:38:31] [INFO]: 收到群 EleCho(XXX) 内 ArsiIksait(XXX) 的消息: 哎，我居然还没满18，白高兴了 (1379198523)
[2022-04-25 16:39:42] [INFO]: 收到群 EleCho(XXX) 内 乌拉-玖天晴(XXX) 的消息: [CQ:image,file=02148eeeb2d2363b89f9351661b570d2.image,subType=1] (-867142760)
[2022-04-25 16:40:40] [INFO]: 收到群 EleCho(XXX) 内 老孙(XXX) 的消息: [CQ:image,file=56dbd88d7f53aa5381b0f3fe52f2e2df.image,subType=1] (-1151909106)
[2022-04-25 16:41:59] [INFO]: 收到群 EleCho(XXX) 内 Arsi的小狐狸awa(XXX) 的消息: [CQ:image,file=afac7ef4a60a560592f12eb148b1ae30.image,subType=1] (576590516)
```

**Comment by HBcao233** [comment]
我也出现了同样的问题

**Comment by wosiwq** [comment]
请问系统版本号能放一下吗
例：
版本 windows 10 专业版
版本号 21H2
操作系统内部版本号 19044.1645

**Comment by SlimeNull** [comment]
***@***.***

Peace & Love

________________________________

**Comment by SlimeNull** [comment]
![image](https://user-images.githubusercontent.com/69663231/167251439-e0ba35f0-24df-4ec9-a159-22c1fc90c2e5.png)

**Comment by wosiwq** [comment]
可以考虑更换[v1.0.0-beta8-fix2](https://github.com/Mrs4s/go-cqhttp/releases/download/v1.0.0-beta8-fix2/go-cqhttp_windows_amd64.exe)来使用，我已知的出现这个问题的好像都是win11用户

**Comment by FujishiroOtone** [comment]
win11 22H2 ，隔一段时间报一次，但是并没有掉线
![image](https://user-images.githubusercontent.com/19571014/223070872-24b16677-1e4b-49d4-8f22-d6d3d8261e5f.png)
`[2023-03-05 02:42:18] [ERROR]: Protocol -> panic on decoder MultiMsg.ApplyDown : runtime error: index out of range [0] with length 0
goroutine 56505 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x83
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1(0x1210c680, 0x120b21e0)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:332 +0x46
panic({0xbd0c20, 0x12016080})
        runtime/panic.go:1038 +0x1bc
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse(0x1210c680, 0x1209a0f0, {0x12090000, 0x49, 0x49})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/multimsg.go:102 +0xa2b
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0x1210c680, 0x1224e438, 0x120b21e0)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:343 +0x187
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:329 +0x599

[2023-03-05 02:42:18] [ERROR]: 出现错误 packet decode error: MultiMsg.ApplyDown - runtime error: index out of range [0] with length 0. 详细信息已转储至文件 dumps/1677955338.dump 请连同日志提交给开发者处理`
