### ISSUE TITLE
[Bug]: panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by aohanhongzhi** [Mrs4s/go-cqhttp#1516]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

最新源代码编译

### 运行环境

Linux

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

同一个机器，就有一个文件夹运行不了，其他QQ正常。很奇怪

### 期望的结果是什么？

正常接收消息

### 实际的结果是什么？

自动退出了

### 日志记录（可选）

```golang
May 28 00:06:23.238 [ERRO] Protocol -> parse incoming packet error: packet dropped ( /media/data/eric/app/jt-go-cqhttp/cmd/gocq/main.go:407 )
May 28 00:06:23.238 [WARN] Bot已离线: session expired ( /media/data/eric/app/jt-go-cqhttp/cmd/gocq/main.go:271 )
May 28 00:06:26.239 [WARN] 将在 3 秒后尝试重连. 重连次数：2/0 ( /media/data/eric/app/jt-go-cqhttp/cmd/gocq/main.go:283 )
May 28 00:06:29.240 [WARN] 尝试重连... ( /media/data/eric/app/jt-go-cqhttp/cmd/gocq/main.go:292 )
May 28 00:06:29.240 [INFO] Protocol -> connect to server: 183.47.99.24:443 ( /media/data/eric/app/jt-go-cqhttp/cmd/gocq/main.go:405 )
panic: runtime error: makeslice: len out of range

goroutine 65 [running]:
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
        /media/data/go-path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220209092529-5d071b034c17/binary/reader.go:40
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).readSSOFrame(0x62383f2a44624b3e?, 0xc0009dd630, {0xc0002783c6?, 0xf0?, 0xf0?})
        /media/data/go-path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:62 +0x250
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).ReadResponse(0xc000441de0, {0xc000490b40, 0x103, 0x103})
        /media/data/go-path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220209092529-5d071b034c17/client/internal/network/response.go:51 +0x3b9
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0xc00025bb80)
        /media/data/go-path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220209092529-5d071b034c17/client/network.go:295 +0x1ac
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
        /media/data/go-path/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20220209092529-5d071b034c17/client/network.go:120 +0x305
```

**Comment by Mrs4s** [comment]
请试试最新版本是否还存在这个问题
