### ISSUE TITLE
[Bug]: interface {} is *cmd0x388.D388TryUpImgRsp, not *client.imageUploadResponse

### ISSUE THREAD

**Issue by wfjsw** [Mrs4s/go-cqhttp#1539]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0-rc2

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

-

### 期望的结果是什么？

-

### 实际的结果是什么？

```
panic: interface conversion: interface {} is *cmd0x388.D388TryUpImgRsp, not *client.imageUploadResponse
goroutine 417 [running]:
ithub.com/Mrs4s/MiraiGo/client.(*QQClient).uploadGroupOrGuildImage(0xc0001c4000, {0xa?, 0x928e80?, 0xba6f90?}, {0xba6f90, 0xc00000f770>
        github.com/Mrs4s/MiraiGo@v0.0.0-20220605085305-ae33763fe10a/client/image.go:105 +0xf37
github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadImage(0xba6f90?, {0x70?, 0x0?, 0xc00003d680?}, {0xba6f90?, 0xc00000f770?}, {0xc000381>
        github.com/Mrs4s/MiraiGo@v0.0.0-20220605085305-ae33763fe10a/client/image.go:49 +0x7b
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).uploadLocalImage(0xc0001cb280, {0x0?, 0x40571d?, 0xc00006ca20?}, 0xc000084640)
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:159 +0x165
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).uploadMedia.func1()
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:219 +0x56
github.com/Mrs4s/go-cqhttp/coolq.(*worker).do.func1()
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:137 +0x5a
created by github.com/Mrs4s/go-cqhttp/coolq.(*worker).do
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:135 +0x85
```

**Comment by Mrs4s** [comment]
#1538
