### ISSUE TITLE
[Bug]: (版本为fix#1538的dev版本)interface {} is *cmd0x388.D388TryUpImgRsp, not *client.imageUploadResponse

### ISSUE THREAD

**Issue by Jadlokin-Scarlet** [Mrs4s/go-cqhttp#1544]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc2 (dev版本：update dep fix #1538）

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

通过api发送频道图文消息时报错并退出

### 期望的结果是什么？

发送成功

### 实际的结果是什么？

程序退出

### 简单的复现代码/链接（可选）

```golang
url=http://0.0.0.0:000/send_guild_channel_msg?access_token=123456 

params={"guild_id":"123456","channel_id":"123456","message":"[CQ:image,file\u003dhttps://vtweet.atodeyo.com/commons/image/1244254367806410753.jpg]弦月藤士郎 2022年06月17日 15:40\n【大喜利】「ロマンスの不祥事」みたいな語呂が最高なこと、言ってください。\n---机翻\n【大喜利】请说“罗曼史的丑闻”这样的语感是最棒的。"}
```

### 日志记录（可选）

```golang
[2022-06-17 14:42:30] [INFO]: 当前版本:v1.0.0-rc2
[2022-06-17 14:42:30] [WARNING]: 已开启Debug模式.
[2022-06-17 14:42:30] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2022-06-17 14:42:30] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2022-06-17 14:42:35] [INFO]: 开始尝试登录并同步消息...
[2022-06-17 14:42:35] [INFO]: 使用协议: iPad
[2022-06-17 14:42:40] [INFO]: Protocol -> connect to server: [::...:.............]:14000
[2022-06-17 14:42:40] [DEBUG]: Protocol -> rev pkt: wtlogin.exchange_emp seq: 13878
[2022-06-17 14:42:40] [WARNING]: Protocol -> device lock is disable. http api may fail.
[2022-06-17 14:42:40] [DEBUG]: Protocol -> rev pkt: StatSvc.register seq: 13879
[2022-06-17 14:42:41] [DEBUG]: Protocol -> rev pkt: ProfileService.Pb.ReqSystemMsgNew.Group seq: 13880
[2022-06-17 14:42:41] [DEBUG]: Protocol -> rev pkt: ProfileService.Pb.ReqSystemMsgNew.Group seq: 13881
[2022-06-17 14:42:41] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.GetMsgV2 seq: -1293579096
[2022-06-17 14:42:41] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.getOffMsg seq: 13882
[2022-06-17 14:42:41] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.PushParam seq: -1293579095
[2022-06-17 14:42:41] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.PushParam seq: -1293579094
[2022-06-17 14:42:41] [DEBUG]: Protocol -> rev pkt: StatSvc.GetDevLoginInfo seq: 13883
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: StatSvc.GetDevLoginInfo seq: 13885
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbGetMsg seq: 13884
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbDeleteMsg seq: 13886
[2022-06-17 14:42:42] [DEBUG]: Protocol -> continue sync with flag: {true 1}
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbGetMsg seq: 13887
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.PbGetMsg seq: -1293579093
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: RegPrxySvc.NoticeEnd seq: -1293579092
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbDeleteMsg seq: 13888
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: trpc.group_pro.synclogic.SyncLogic.SyncFirstView seq: 13889
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: trpc.group_pro.synclogic.SyncLogic.PushFirstView seq: -1293578396
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: trpc.group_pro.synclogic.SyncLogic.PushFirstView seq: -1293578396
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: OidbSvcTrpcTcp.0xfc9_1 seq: 13890
[2022-06-17 14:42:42] [INFO]: 登录成功 欢迎使用: ...
[2022-06-17 14:42:42] [INFO]: 开始加载好友列表...
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: OnlinePush.PbPushGroupMsg seq: -1612430716
[2022-06-17 14:42:42] [DEBUG]: Protocol -> sync group .....
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: OidbSvcTrpcTcp.0xf5d_1 seq: 13891
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: OidbSvc.0x88d_0 seq: 13893
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: friendlist.getFriendGroupList seq: 13892
[2022-06-17 14:42:42] [INFO]: 共加载 5 个好友.
[2022-06-17 14:42:42] [INFO]: 开始加载群列表...
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: trpc.group_pro.synclogic.SyncLogic.PushFirstView seq: -1293578396
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: OidbSvcTrpcTcp.0xf5d_1 seq: 13894
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopListReqV2 seq: 13896
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: OidbSvcTrpcTcp.0xf5d_1 seq: 13897
[2022-06-17 14:42:42] [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 13895
[2022-06-17 14:42:43] [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 13901
[2022-06-17 14:42:43] [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 13902
[2022-06-17 14:42:43] [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 13899
[2022-06-17 14:42:43] [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 13898
[2022-06-17 14:42:43] [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 13905
[2022-06-17 14:42:43] [DEBUG]: Protocol -> rev pkt: OidbSvcTrpcTcp.0xf5d_1 seq: 13907
[2022-06-17 14:42:43] [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 13904
[2022-06-17 14:42:43] [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 13900
[2022-06-17 14:42:43] [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 13903
[2022-06-17 14:42:43] [DEBUG]: Protocol -> rev pkt: friendlist.GetTroopMemberListReq seq: 13906
[2022-06-17 14:42:43] [INFO]: 共加载 9 个群.
[2022-06-17 14:42:43] [DEBUG]: Protocol -> rev pkt: OidbSvcTrpcTcp.0xf5d_1 seq: 13908
[2022-06-17 14:42:43] [DEBUG]: Protocol -> rev pkt: StatSvc.SetStatusFromClient seq: 13909
[2022-06-17 14:42:43] [INFO]: 资源初始化完成, 开始处理信息.
[2022-06-17 14:42:43] [INFO]: アトリは、高性能ですから!
[2022-06-17 14:42:43] [INFO]: CQ HTTP 服务器已启动: [::]:...
[2022-06-17 14:42:43] [INFO]: CQ WebSocket 服务器已启动: [::]:...
[2022-06-17 14:42:43] [INFO]: 正在检查更新.
[2022-06-17 14:42:43] [DEBUG]: Protocol -> rev pkt: OidbSvcTrpcTcp.0xf5d_1 seq: 13910
[2022-06-17 14:42:43] [DEBUG]: Protocol -> rev pkt: ConfigPushSvc.PushDomain seq: -447901877
[2022-06-17 14:42:43] [DEBUG]: Protocol -> Unhandled Command: ConfigPushSvc.PushDomain
Seq: 36683
This message can be ignored.
[2022-06-17 14:42:43] [DEBUG]: Protocol -> rev pkt: ConfigPushSvc.PushReq seq: -447901879
[2022-06-17 14:42:43] [DEBUG]: Protocol -> got file storage svc push.
[2022-06-17 14:42:43] [INFO]: 检查更新完成. 当前已运行最新版本.
[2022-06-17 14:42:43] [INFO]: 开始诊断网络情况
[2022-06-17 14:42:46] [DEBUG]: 聊天服务器连接延迟: 33ms
[2022-06-17 14:42:46] [DEBUG]: 聊天服务器丢包率: 0%
[2022-06-17 14:42:46] [DEBUG]: 长消息服务器连接延迟: 8ms
[2022-06-17 14:42:46] [DEBUG]: 长消息服务器响应延迟: 62ms
[2022-06-17 14:42:46] [DEBUG]: 媒体服务器连接延迟: 34ms
[2022-06-17 14:42:46] [DEBUG]: 媒体服务器丢包率: 0%
[2022-06-17 14:42:46] [INFO]: 网络诊断完成. 未发现问题
[2022-06-17 14:42:50] [DEBUG]: Protocol -> rev pkt: MsgPush.PushGroupProMsg seq: -1047926388
[2022-06-17 14:42:50] [INFO]: 收到来自频道 ...(...) 子频道 游戏杂谈(...) 内 ...(...) 的消息: 草
[2022-06-17 14:42:52] [DEBUG]: Protocol -> rev pkt: MsgPush.PushGroupProMsg seq: -1670641814
[2022-06-17 14:42:52] [INFO]: 收到来自频道 ...(...) 子频道 直播频道2(...) 内 ria(...) 的消息: 什么东西
[2022-06-17 14:43:02] [DEBUG]: Protocol -> rev pkt: MsgPush.PushGroupProMsg seq: -1628987676
[2022-06-17 14:43:02] [INFO]: 收到来自频道 ...(...) 子频道 ...{...) 内 ...) 的消息: [CQ:image,file=....image,url=...]
[2022-06-17 14:43:04] [DEBUG]: HTTPServer接收到API调用: send_guild_channel_msg
[2022-06-17 14:43:05] [DEBUG]: Protocol -> rev pkt: ImgStore.QQMeetPicUp seq: 13912
panic: interface conversion: interface {} is *cmd0x388.D388TryUpImgRsp, not *client.imageUploadResponse

goroutine 199 [running]:
github.com/Mrs4s/MiraiGo/client.(*QQClient).uploadGroupOrGuildImage(0xc0001f0000, {0xa?, 0x928e80?, 0xba6f90?}, {0xba6f90, 0xc00000e6b8}, {0xc000176ea0, 0x1, 0xba6f90?})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220605085305-ae33763fe10a/client/image.go:105 +0xf37
github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadImage(0xba6f90?, {0xb8?, 0x0?, 0x0?}, {0xba6f90?, 0xc00000e6b8?}, {0xc000176ea0?, 0x6546f9?, 0xc0000f7180?})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220605085305-ae33763fe10a/client/image.go:49 +0x7b
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).uploadLocalImage(0xc0000df580, {0x0?, 0xc0006f1f98?, 0x67fee5?}, 0xc00052ca00)
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:159 +0x165
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).uploadMedia.func1()
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:219 +0x56
github.com/Mrs4s/go-cqhttp/coolq.(*worker).do.func1()
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:137 +0x5a
created by github.com/Mrs4s/go-cqhttp/coolq.(*worker).do
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:135 +0x85
```

### 补充说明（可选）

看起来和#1538差不多，不过尝试了dev版本也还是报错

**Comment by Mrs4s** [comment]
`[2022-06-17 14:42:30] [INFO]: 当前版本:v1.0.0-rc2`
看上去似乎没有正确替换?
