### ISSUE TITLE
[Bug]: 无法接收 合并转发消息 中的短视频

### ISSUE THREAD

**Issue by BILLYx1120** [Mrs4s/go-cqhttp#1546]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc1

### 运行环境

Windows (64)

### 运行架构

x86

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

我的机器人会接收 **合并转发** 内容， 而但凡 **合并转发** 的内容里出现了短视频，cq-http就会报错并跳过这一项。

### 期望的结果是什么？

正常获取短视频的message segment，使得我可以按照我程序中的方式处理segment

### 实际的结果是什么？

在接收 **合并转发消息** 时如果转发的消息里有短视频，那么会报错：packet decode error: PttCenterSvr.ShortVideoDownReq

一些参考截图：
![bug01](https://user-images.githubusercontent.com/20014530/174456319-2540c8fa-2100-4bfa-8ad8-e6f55ba5ccc7.PNG)
![bug02](https://user-images.githubusercontent.com/20014530/174456324-99fbc403-0f32-46a8-8893-24b9a6015b8e.PNG)

### 日志记录（可选）

```golang
[2022-05-07 17:34:07] [ERROR]: Protocol -> panic on decoder PttCenterSvr.ShortVideoDownReq : runtime error: index out of range [0] with length 0
goroutine 193 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:332 +0x5d
panic({0x15f2f80, 0xc0000aecf0})
        runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/client.decodePttShortVideoDownResponse(0xc00001aa80, 0x21, {0xc00001aa80, 0x21, 0x21})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/ptt.go:348 +0x14e
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc00048caf0)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:343 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:329 +0x697

[2022-05-07 17:34:07] [ERROR]: 出现错误 packet decode error: PttCenterSvr.ShortVideoDownReq - runtime error: index out of range [0] with length 0. 详细信息已转储至文件 dumps/1651959247.dump 请连同日志提交给开发者处理
[2022-05-07 17:34:22] [ERROR]: Protocol -> panic on decoder PttCenterSvr.ShortVideoDownReq : runtime error: index out of range [0] with length 0
goroutine 245 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:332 +0x5d
panic({0x15f2f80, 0xc0000aee70})
        runtime/panic.go:1038 +0x215
github.com/Mrs4s/MiraiGo/client.decodePttShortVideoDownResponse(0xc00001ae10, 0x21, {0xc00001ae10, 0x21, 0x21})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/ptt.go:348 +0x14e
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc00048cf50)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:343 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20220209092529-5d071b034c17/client/network.go:329 +0x697

[2022-05-07 17:34:22] [ERROR]: 出现错误 packet decode error: PttCenterSvr.ShortVideoDownReq - runtime error: index out of range [0] with length 0. 详细信息已转储至文件 dumps/1651959262.dump 请连同日志提交给开发者处理
```

### 补充说明（可选）

Dump文件：
[1651959262.zip](https://github.com/Mrs4s/go-cqhttp/files/8934315/1651959262.zip)

我能确认的是我的程序没有问题，它可以正常单独接收短视频

另，对于失效视频的处理好像也不太好...但我不记得了

**Comment by wdvxdr1123** [comment]
dev分支和rc1版本中均无法复现
