### ISSUE TITLE
[Bug]: event error: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Caleeen** [Mrs4s/go-cqhttp#1592]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

无法重现，挂机时出现，在心跳后

### 期望的结果是什么？

没有该错误

### 实际的结果是什么？

出现该错误

### 日志记录（可选）

```golang
event error: runtime error: invalid memory address or nil pointer dereference
goroutine 12182 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24  0x65
github.com/Mrs4s/MiraiGo/client.(*EventHandle[...]).dispatch.func1()
	github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/events.go:36  0x59
panic({0x1108f00, 0x163e180})
	runtime/panic.go:838  0x207
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).groupMessageEvent(0xc0acd0ba1a4ebc94?, 0x51c0963c4301?, 0x0)
	github.com/Mrs4s/go-cqhttp/coolq/event.go:102  0x41
github.com/Mrs4s/MiraiGo/client.(*EventHandle[...]).dispatch(0xc00022a618, 0xc000292000?, 0x0)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/events.go:40  0x110
github.com/Mrs4s/MiraiGo/client.decodeGroupMessagePacket(0xc000292000, 0x294?, {0xc00036c000, 0x294, 0x294})
	github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/group_msg.go:303  0x328
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc000066320)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:346  0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
	github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:332  0x4b8
```

### 补充说明（可选）

出现错误，但可以收发消息，没有崩溃

**Comment by GLGDLY** [comment]
[ERROR]: 出现错误 packet decode error: MsgPush.PushGroupProMsg - runtime error: invalid memory address or nil pointer dereference. 详细信息已转储至文件 dumps/1658023491.dump 请连同日志提交给开发者处理 
[1658023491.zip](https://github.com/Mrs4s/go-cqhttp/files/9126920/1658023491.zip)

**Comment by clacknya** [comment]
[ERROR]: 出现错误 packet decode error: OnlinePush.PbPushTransMsg - runtime error: invalid memory address or nil pointer dereference. 详细信息已转储至文件 dumps/1663850490.dump 请连同日志提交给开发者处理

[1663850490.zip](https://github.com/Mrs4s/go-cqhttp/files/9631995/1663850490.zip)
