### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GLGDLY** [Mrs4s/go-cqhttp#1594]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

1 | Android Phone

### 重现步骤

开启就会出现，每次接收新消息的时候就会出现这种情况，完全不能正常接收到消息

### 期望的结果是什么？

正常解析事件

### 实际的结果是什么？

显示bug，并希望我把日志交给你们处理

### 日志记录（可选）

```golang
[INFO]: 开始诊断网络情况 
[2022-07-18 00:39:20] [INFO]: 网络诊断完成. 未发现问题 
[2022-07-18 00:39:42] [ERROR]: Protocol -> panic on decoder MsgPush.PushGroupProMsg : runtime error: invalid memory address or nil pointer dereference
goroutine 183 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
	github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:335 +0x65
panic({0xa18f00, 0xf4e180})
	runtime/panic.go:838 +0x207
github.com/Mrs4s/MiraiGo/client.decodeGuildEventFlowPacket(0xc0001e6000, 0x42?, {0xc0000afa40, 0x42, 0x42})
	github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/guild_eventflow.go:52 +0x1c8
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc000335360)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:346 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
	github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:332 +0x4b8
 
[2022-07-18 00:39:42] [ERROR]: 出现错误 packet decode error: MsgPush.PushGroupProMsg - runtime error: invalid memory address or nil pointer dereference. 详细信息已转储至文件 dumps/1658075982.dump 请连同日志提交给开发者处理
```

### 补充说明（可选）

[1658075982.zip](https://github.com/Mrs4s/go-cqhttp/files/9128106/1658075982.zip)

**Comment by GLGDLY** [comment]
经测试，回到版本v1.0.0-rc2之后没有这个问题，目前似乎只有最新的rc3存在

**Comment by fy0** [comment]
+1
