### ISSUE TITLE
[Bug]: QQ频道产生未知原因的大量panic

### ISSUE THREAD

**Issue by xry1029** [Mrs4s/go-cqhttp#1598]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [x] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3 (在最新dev版本551a475依旧复现)

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

1 | Android Phone

### 重现步骤

正常运行go-cqhttp
go-cq尝试同步消息
开始反复报panic

### 期望的结果是什么？

没有Error 直接加载群聊消息

### 实际的结果是什么？

尝试登录后一直报Error 看样子是频道相关
20秒左右之后显示登陆成功，正常
重启/换device.json均无法解决
产生大量dump文件

### 日志记录（可选）

```golang
[2022-07-19 22:07:02] [INFO]: 当前版本:551a475 
[2022-07-19 22:07:02] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2022-07-19 22:07:02] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2022-07-19 22:07:07] [INFO]: 开始尝试登录并同步消息... 
[2022-07-19 22:07:07] [INFO]: 使用协议: Android Phone 
[2022-07-19 22:07:10] [INFO]: Protocol -> connect to server: 183.47.106.14:8080 
[2022-07-19 22:07:10] [WARNING]: Protocol -> device lock is disable. http api may fail. /*换打开设备锁的QQ依旧如此*/
[2022-07-19 22:07:12] [ERROR]: Protocol -> panic on decoder MsgPush.PushGroupProMsg : runtime error: invalid memory address or nil pointer dereference
goroutine 16 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
	github.com/Mrs4s/MiraiGo@v0.0.0-20220622015746-24ee0103e7de/client/network.go:335 +0x65
panic({0xa01ac0, 0xf1f360})
	runtime/panic.go:838 +0x207
github.com/Mrs4s/MiraiGo/client.decodeGuildEventFlowPacket(0xc0000ae000, 0x12e?, {0xc000102000, 0x12e, 0x12e})
	github.com/Mrs4s/MiraiGo@v0.0.0-20220622015746-24ee0103e7de/client/guild_eventflow.go:52 +0x1c8
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0000faa50)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220622015746-24ee0103e7de/client/network.go:346 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
	github.com/Mrs4s/MiraiGo@v0.0.0-20220622015746-24ee0103e7de/client/network.go:332 +0x4b8
 
[2022-07-19 22:07:12] [ERROR]: 出现错误 packet decode error: MsgPush.PushGroupProMsg - runtime error: invalid memory address or nil pointer dereference. 详细信息已转储至文件 dumps/1658239632.dump 请连同日志提交给开发者处理 
[2022-07-19 22:07:13] [INFO]: 登录成功 欢迎使用: ********
[2022-07-19 22:07:13] [INFO]: 开始加载好友列表... 
[2022-07-19 22:07:13] [INFO]: 共加载 * 个好友. 
[2022-07-19 22:07:13] [INFO]: 开始加载群列表... 
[2022-07-19 22:07:15] [ERROR]: Protocol -> panic on decoder MsgPush.PushGroupProMsg : runtime error: invalid memory address or nil pointer dereference
goroutine 133 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
	github.com/Mrs4s/MiraiGo@v0.0.0-20220622015746-24ee0103e7de/client/network.go:335 +0x65
panic({0xa01ac0, 0xf1f360})
	runtime/panic.go:838 +0x207
github.com/Mrs4s/MiraiGo/client.decodeGuildEventFlowPacket(0xc0000ae000, 0x151?, {0xc00013ac60, 0x151, 0x151})
	github.com/Mrs4s/MiraiGo@v0.0.0-20220622015746-24ee0103e7de/client/guild_eventflow.go:52 +0x1c8
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0005e21e0)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220622015746-24ee0103e7de/client/network.go:346 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
	github.com/Mrs4s/MiraiGo@v0.0.0-20220622015746-24ee0103e7de/client/network.go:332 +0x4b8
 
[2022-07-19 22:07:15] [ERROR]: 出现错误 packet decode error: MsgPush.PushGroupProMsg - runtime error: invalid memory address or nil pointer dereference. 详细信息已转储至文件 dumps/1658239635.dump 请连同日志提交给开发者处理 
[2022-07-19 22:07:15] [ERROR]: Protocol -> panic on decoder MsgPush.PushGroupProMsg : runtime error: invalid memory address or nil pointer dereference
goroutine 217 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
	github.com/Mrs4s/MiraiGo@v0.0.0-20220622015746-24ee0103e7de/client/network.go:335 +0x65
panic({0xa01ac0, 0xf1f360})
	runtime/panic.go:838 +0x207
github.com/Mrs4s/MiraiGo/client.decodeGuildEventFlowPacket(0xc0000ae000, 0x141?, {0xc00013ac60, 0x141, 0x141})
	github.com/Mrs4s/MiraiGo@v0.0.0-20220622015746-24ee0103e7de/client/guild_eventflow.go:52 +0x1c8
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0001001e0)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220622015746-24ee0103e7de/client/network.go:346 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
	github.com/Mrs4s/MiraiGo@v0.0.0-20220622015746-24ee0103e7de/client/network.go:332 +0x4b8
 
[2022-07-19 22:07:15] [ERROR]: 出现错误 packet decode error: MsgPush.PushGroupProMsg - runtime error: invalid memory address or nil pointer dereference. 详细信息已转储至文件 dumps/1658239635.dump 请连同日志提交给开发者处理 
/*正常了*/
[2022-07-19 22:07:17] [INFO]: 共加载 * 个群. 
[2022-07-19 22:07:17] [INFO]: 资源初始化完成, 开始处理信息. 
[2022-07-19 22:07:17] [INFO]: アトリは、高性能ですから! 
[2022-07-19 22:07:17] [WARNING]: 警告: 心跳功能已关闭，若非预期，请检查配置文件。 
[2022-07-19 22:07:17] [INFO]: 正在检查更新. 
[2022-07-19 22:07:17] [INFO]: HTTP POST上报器已启动: http://127.0.0.1:9090/bot.cgi 
[2022-07-19 22:07:17] [INFO]: CQ HTTP 服务器已启动: 127.0.0.1:9091 
[2022-07-19 22:07:17] [WARNING]: 检查更新失败！ 
[2022-07-19 22:07:17] [INFO]: 检查更新完成. 当前已运行最新版本. 
[2022-07-19 22:07:17] [INFO]: 开始诊断网络情况 
[2022-07-19 22:07:19] [ERROR]: Protocol -> panic on decoder MsgPush.PushGroupProMsg : runtime error: invalid memory address or nil pointer dereference
goroutine 264 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
	github.com/Mrs4s/MiraiGo@v0.0.0-20220622015746-24ee0103e7de/client/network.go:335 +0x65
panic({0xa01ac0, 0xf1f360})
	runtime/panic.go:838 +0x207
github.com/Mrs4s/MiraiGo/client.decodeGuildEventFlowPacket(0xc0000ae000, 0x151?, {0xc00013ac60, 0x151, 0x151})
	github.com/Mrs4s/MiraiGo@v0.0.0-20220622015746-24ee0103e7de/client/guild_eventflow.go:52 +0x1c8
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0000fbc20)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220622015746-24ee0103e7de/client/network.go:346 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
	github.com/Mrs4s/MiraiGo@v0.0.0-20220622015746-24ee0103e7de/client/network.go:332 +0x4b8
 
[2022-07-19 22:07:19] [ERROR]: 出现错误 packet decode error: MsgPush.PushGroupProMsg - runtime error: invalid memory address or nil pointer dereference. 详细信息已转储至文件 dumps/1658239639.dump 请连同日志提交给开发者处理 
[2022-07-19 22:07:20] [INFO]: 网络诊断完成. 未发现问题
```

### 补充说明（可选）

base64压缩的一份go-cqhttp产生的转储文件：
GAAoATKWAvklCisqKQjLjJeq87KBcxCl70YY8L1iIILeXijL8dqWBqIGCwiN/L3VDRCokq5eCoAC
CjcKIDAA8RQgovux/fGAgIACKMyW//8PMOYYEhMIgR4QJyDwvWIogt5eMEoAcRo+CjwKHBAMAPAf
GJ7Y/9UFKAo4hgFAAkoH5a6L5L2TABIcqgMZCPQDEhS6AgYIzb1iEAW6AggI4QkA9i8YAiKEAQoJ
5bCP5ZOl6YWSEgtRUeS8gem5headkRoc8J+nkeKAjfCfkrtRUemikemBk+S6pOa1geWMuigCQjgA
EUiAAPcTYgB6KjEjMTY0MDc0MzIwMGE1NzVmZjJhZTE1MjMxNWEjMx4A4DGIAcyS7YsGmgEAogEA
OgBAAQ==

**Comment by GLGDLY** [comment]
#1594 跟我的问题一样，我切到rc2没这个问题了，但是rc2发图会崩溃…………

**Comment by Mrs4s** [comment]
看上去应该是协议有点修改，但是我现在在外面旅游，晚点看看吧
