### ISSUE TITLE
[Bug]: 关于群文件相关的api的一些bug

### ISSUE THREAD

**Issue by wkr1423** [Mrs4s/go-cqhttp#1606]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0-rc3

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

使用/create_group_file_folder时

### 期望的结果是什么？

能正常地创建文件夹，并有正常的返回

### 实际的结果是什么？

能正常创建文件夹，但无正常的返回，好像报的是指针错误？

### 简单的复现代码/链接（可选）

```golang
执行下面的python代码
    def makeDir(groupId, folderName):
        return requests.post(
            f"http://{HTTP_HOST}:{HTTP_PORT}/create_group_file_folder",
            data={
                "group_id": groupId,
                "name": folderName,
                "parent_id": "/"
            }
        ).json()


[2022-07-31 10:55:09,848](DEBUG): Starting new HTTP connection (1): localhost:5700
[2022-07-31 10:55:40,059](DEBUG): http://localhost:5700 "POST /create_group_file_folder HTTP/1.1" 200 126
{'data': None, 'msg': 'FILE_SYSTEM_API_ERROR', 'retcode': 100, 'status': 'failed', 'wording': 'create folder error: Packet timed out'}
```

### 日志记录（可选）

```golang
[2022-07-31 10:26:51] [ERROR]: Protocol -> panic on decoder OidbSvc.0x6d7_0 : runtime error: invalid memory address or nil pointer dereference
goroutine 298 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:335 +0x65
panic({0xa00880, 0xf1d360})
        runtime/panic.go:838 +0x207
github.com/Mrs4s/MiraiGo/client.decodeOIDB6d7Response(0xc0005b2420?, 0x5e?, {0xc0005b2420, 0x5e, 0x5e})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/group_file.go:397 +0x8f
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc00059e5a0)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:346 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:332 +0x4b8
 
[2022-07-31 10:26:51] [ERROR]: 出现错误 packet decode error: OidbSvc.0x6d7_0 - runtime error: invalid memory address or nil pointer dereference. 详细信息已转储至文件 dumps/1659263211志提交给开发者处理
```

**Comment by MingxuanGame** [comment]
这是 miraigo 的一个 bug
Mrs4s/MiraiGo#289
