### ISSUE TITLE
[Bug]: 转换CQ码 [CQ:video,file=...,cover=...] 时出现错误

### ISSUE THREAD

**Issue by qq9077** [Mrs4s/go-cqhttp#1637]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0-rc3

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

按照 https://docs.go-cqhttp.org/guide/quick_start.html#%E5%AE%89%E8%A3%85-ffmpeg 安装了ffmpeg
软件在D盘 也加入了环境变量path
并且能够 在C:\> 使用CMD 执行 c:\>ffmpeg.exe -i "https://xxx.m3u8" -c copy video.mp4 成功获得mp4文件
运行结果也能看到
video:12721kB audio:5981kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.231952%

c:\>
但是程序中调用就出现如下错误
[2022-08-16 10:38:21] [WARNING]: 转换CQ码 [CQ:video,file=http://xxxxx/xxx/xxx.m3u8,cover=...] 时出现错误: convert mp4 failed: exit status 1 将原样发送.

有什么办法可以检查问题来源么  还是说这个是程序bug ？

### 期望的结果是什么？

程序报告确切的反生问题的原因 以本地解决问题
或者程序修复了错误

### 实际的结果是什么？

一头雾水

### 简单的复现代码/链接（可选）

```golang
[2022-08-16 10:38:20] [INFO]: 收到好友  /dx真红眼龙(xxx) 的消息: nsbcfn
(xxx)
[2022-08-16 10:38:21] [WARNING]: 转换CQ码 [CQ:video,file=https://xxx.m3u8,cover=https://xxx.jpg] 时出现错误: convert mp4 failed: exit status 1 将原样发送.

[2022-08-16 10:38:21] [INFO]: 发送好友 156779077(xxx)  的消息: [CQ:video,
... (xxx)
```

**Comment by qianjunakasumi** [comment]
尝试自行调用 `ffmpeg` 命令转换为 `mp4` 后，将新 `mp4` 路径填充至 cq 码

**Comment by qq9077** [comment]
发送的文件大小有没有限制 我这个发送的是培训视频 部分超过1分钟的 可能体积会超过100M

**Comment by lmy8848** [comment]
```text
[2022-11-09 16:22:48] [ERROR]: Protocol -> panic on decoder PttCenterSvr.ShortVideoDownReq : runtime error: index out of range [0] with length 0
goroutine 517 [running]
runtime/debug.Stack()te
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:335 +0x65
panic({0xd444e0, 0xc000d29f50})
        runtime/panic.go:838 +0x207
github.com/Mrs4s/MiraiGo/client.decodePttShortVideoDownResponse(0xc001263590?, 0x24?, {0xc001263590, 0x24, 0x24})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/ptt.go:337 +0x14e
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc000224640)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:346 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:332 +0x4b8

[2022-11-09 16:22:48] [ERROR]: 出现错误 packet decode error: PttCenterSvr.ShortVideoDownReq - runtime error: index out of range [0] with length 0. 详细信息已转储至文件 dumps/1667982168.dump 请连同日志提交给开发者处理
[2022-11-09 16:23:03] [ERROR]: Protocol -> panic on decoder PttCenterSvr.ShortVideoDownReq : runtime error: index out of range [0] with length 0
goroutine 473 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:335 +0x65
panic({0xd444e0, 0xc0008ab170})
        runtime/panic.go:838 +0x207
github.com/Mrs4s/MiraiGo/client.decodePttShortVideoDownResponse(0xc0006a4090?, 0x24?, {0xc0006a4090, 0x24, 0x24})
        github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/ptt.go:337 +0x14e
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0004b0780)
        github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:346 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:332 +0x4b8

[2022-11-09 16:23:03] [ERROR]: 出现错误 packet decode error: PttCenterSvr.ShortVideoDownReq - runtime error: index out of range [0] with length 0. 详细信息已转储至文件 dumps/1667982183.dump 请连同日志提交给开发者处理
```
> 视频可以正常发送，但是报以上错误
