### ISSUE TITLE
[Bug]: [WARNING]: Protocol -> device lock is disable. http api may fail. 

### ISSUE THREAD

**Issue by V1046-RMAHORO** [Mrs4s/go-cqhttp#1653]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc3

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

./go-cqhttp
[2022-08-29 18:01:26] [INFO]: 当前版本:v1.0.0-rc3 
[2022-08-29 18:01:26] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2022-08-29 18:01:26] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2022-08-29 18:01:31] [INFO]: 开始尝试登录并同步消息... 
[2022-08-29 18:01:31] [INFO]: 使用协议: iPad 
[2022-08-29 18:01:31] [INFO]: Protocol -> connect to server: [::ffff:42.81.192.181]:443 
[2022-08-29 18:01:33] [INFO]: 登录成功 欢迎使用: 阳 
[2022-08-29 18:01:33] [INFO]: 开始加载好友列表... 
[2022-08-29 18:01:33] [INFO]: 共加载 10 个好友. 
[2022-08-29 18:01:33] [INFO]: 开始加载群列表... 
[2022-08-29 18:01:34] [INFO]: 共加载 2 个群. 
[2022-08-29 18:01:34] [INFO]: 资源初始化完成, 开始处理信息. 
[2022-08-29 18:01:34] [INFO]: アトリは、高性能ですから! 
[2022-08-29 18:01:34] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:6700/onebot/v11/ws/ 

### 期望的结果是什么？

[2022-08-29 18:01:26] [INFO]: 当前版本:v1.0.0-rc3 
[2022-08-29 18:01:26] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2022-08-29 18:01:26] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2022-08-29 18:01:31] [INFO]: 开始尝试登录并同步消息... 
[2022-08-29 18:01:31] [INFO]: 使用协议: iPad 
[2022-08-29 18:01:31] [INFO]: Protocol -> connect to server: [::ffff:42.81.192.181]:443 
[2022-08-29 18:01:32] [WARNING]: Protocol -> device lock is disable. http api may fail. 
[2022-08-29 18:01:33] [INFO]: 登录成功 欢迎使用: 阳 
[2022-08-29 18:01:33] [INFO]: 开始加载好友列表... 
[2022-08-29 18:01:33] [INFO]: 共加载 10 个好友. 
[2022-08-29 18:01:33] [INFO]: 开始加载群列表... 
[2022-08-29 18:01:34] [INFO]: 共加载 2 个群. 
[2022-08-29 18:01:34] [INFO]: 资源初始化完成, 开始处理信息. 
[2022-08-29 18:01:34] [INFO]: アトリは、高性能ですから! 
[2022-08-29 18:01:34] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:6700/onebot/v11/ws/ 
[2022-08-29 18:01:34] [INFO]: 正在检查更新. 

### 实际的结果是什么？

[2022-08-29 18:01:26] [INFO]: 当前版本:v1.0.0-rc3 
[2022-08-29 18:01:26] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2022-08-29 18:01:26] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2022-08-29 18:01:31] [INFO]: 开始尝试登录并同步消息... 
[2022-08-29 18:01:31] [INFO]: 使用协议: iPad 
[2022-08-29 18:01:31] [INFO]: Protocol -> connect to server: [::ffff:42.81.192.181]:443 
[2022-08-29 18:01:32] [WARNING]: Protocol -> device lock is disable. http api may fail. 
[2022-08-29 18:01:33] [INFO]: 登录成功 欢迎使用: 阳 
[2022-08-29 18:01:33] [INFO]: 开始加载好友列表... 
[2022-08-29 18:01:33] [INFO]: 共加载 10 个好友. 
[2022-08-29 18:01:33] [INFO]: 开始加载群列表... 
[2022-08-29 18:01:34] [INFO]: 共加载 2 个群. 
[2022-08-29 18:01:34] [INFO]: 资源初始化完成, 开始处理信息. 
[2022-08-29 18:01:34] [INFO]: アトリは、高性能ですから! 
[2022-08-29 18:01:34] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:6700/onebot/v11/ws/ 
[2022-08-29 18:01:34] [INFO]: 正在检查更新.

**Comment by DarckRM** [comment]
同这个问题，但是目前没有可以直接观察到的影响

**Comment by Mrs4s** [comment]
这个日志不影响功能, 下个版本会删掉

**Comment by symbolworld** [comment]
> 这个日志不影响功能, 下个版本会删掉

我更新了v1.0.0-rc4版本，这个问题还在。系统版本：CentOS Linux release 7.9.2009 (Core) ，运行版本：go-cqhttp_linux_386.tar.gz。
在功能上发现群成员发送语音时，获取失败。
[WARNING]: 语音文件 39F34D513ED8CBC179B64B4EFD15E3FC.amr 下载失败: Get "http://grouptalk.c2c.qq.com": EOF

**Comment by xa9-top** [comment]
我的发送消息就有问题
`[2024-03-02 13:11:26,917][cqhttp_shell/WARNING] PyCqBot: go-cqhttp 警告 no sign server configured
[2024-03-02 13:11:26,918][cqhttp_shell/WARNING] PyCqBot: go-cqhttp 警告 警告: 未配置签名服务器或签名服务器不可用, 这可能会导致登录 45 错误码或发送消息被风控
[2024-03-02 13:11:27,430][cqhttp_shell/WARNING] PyCqBot: go-cqhttp 警告 Protocol -> device lock is disabled. HTTP API may fail.
[2024-03-02 13:11:30,401][MainThread/INFO] PyCqBot: 正在连接 go-cqhttp websocket 服务
[2024-03-02 13:11:30,415][MainThread/INFO] PyCqBot: 成功连接 websocket 服务! bot qq:2020481660
received cmd: switch 2
[2024-03-02 13:11:55,520][asyncHttp_loop/ERROR] PyCqBot: api 请求发生错误 Error: Server disconnected
[2024-03-02 13:11:55,520][asyncHttp_loop/ERROR] PyCqBot: Server disconnected
Traceback (most recent call last):
  File "D:\document\Spit_chatBot-main\python\lib\site-packages\pycqBot\socketApp.py", line 395, in link
    async with self._session.post(url, data=data, allow_redirects=allow_redirects, proxy=proxy, headers=headers) as req:
  File "D:\document\Spit_chatBot-main\python\lib\site-packages\aiohttp\client.py", line 1194, in __aenter__
    self._resp = await self._coro
  File "D:\document\Spit_chatBot-main\python\lib\site-packages\aiohttp\client.py", line 605, in _request
    await resp.start(conn)
  File "D:\document\Spit_chatBot-main\python\lib\site-packages\aiohttp\client_reqrep.py", line 966, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "D:\document\Spit_chatBot-main\python\lib\site-packages\aiohttp\streams.py", line 622, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
[2024-03-02 13:11:55,523][asyncHttp_loop/WARNING] PyCqBot: cqAPI 响应: None / {}`
