### ISSUE TITLE
[Bug]: 处置WS命令时发生无法恢复的异常：btree I/O error: EOF

### ISSUE THREAD

**Issue by nicklly** [Mrs4s/go-cqhttp#1756]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0..0-rc1

### 运行环境

Ubuntu

### 运行架构

x86

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

使用nonebot通过反向ws连接gocqhttp之后输出指令

### 期望的结果是什么？

修复

### 实际的结果是什么？

如下方日志记录所示

### 日志记录（可选）

```golang
[2022-11-02 22:54:18] [INFO]: 处置WS命令时发生无法恢复的异常：btree I/O error: EOF
goroutine 155 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest.func1()
        github.com/Mrs4s/go-cqhttp/server/websocket.go:414 +0x45
panic({0xae72e0, 0xc00000d908})
        runtime/panic.go:1038 +0x215
github.com/Mrs4s/go-cqhttp/internal/btree.(*DB).get(0x52, 0xc000140a20)
        github.com/Mrs4s/go-cqhttp/internal/btree/btree.go:71 +0x105
github.com/Mrs4s/go-cqhttp/internal/btree.(*DB).insert(0xc000155400, 0x3d3000, 0xc000215f58, {0xc0001c6aa0, 0x98, 0xa0}, 0x7f4ed118d108)
        github.com/Mrs4s/go-cqhttp/internal/btree/btree.go:274 +0x65
github.com/Mrs4s/go-cqhttp/internal/btree.(*DB).insertTopLevel(0xc000155400, 0xc000155408, 0xc000215f58, {0xc0001c6aa0, 0x0, 0xc000215f70}, 0x7050aa)
        github.com/Mrs4s/go-cqhttp/internal/btree/btree.go:404 +0x52
github.com/Mrs4s/go-cqhttp/internal/btree.(*DB).Insert(0xc000155400, 0x112f900, {0xc0001c6aa0, 0xc000362030, 0xc0})
        github.com/Mrs4s/go-cqhttp/internal/btree/btree.go:473 +0x4c
github.com/Mrs4s/go-cqhttp/internal/cache.(*Cache).Insert(0x1143440, {0xc000362030, 0x10, 0x5595e}, {0xc0001c6aa0, 0x98, 0xa0})
        github.com/Mrs4s/go-cqhttp/internal/cache/cache.go:35 +0xdd
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).checkMedia(0xc000350240, {0xc00020e030, 0x1, 0x0}, 0x18a113e8)
        github.com/Mrs4s/go-cqhttp/coolq/event.go:746 +0x8c7
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).SendGroupMessage(0xc000350240, 0x1, 0xc0002164a0)
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:256 +0x125
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendGroupMessage(0xc000350240, 0x0, {0x5, {0xc000700074, 0x72247}, {0x0, 0x0}, 0x0, 0x74, {0x0, ...}}, ...)
        github.com/Mrs4s/go-cqhttp/coolq/api.go:729 +0x270
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendMessage(0x0, 0x0, 0x0, {0x5, {0xc000700074, 0x72247}, {0x0, 0x0}, 0x0, 0x74, ...}, ...)
        github.com/Mrs4s/go-cqhttp/coolq/api.go:679 +0x5b
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).call(0xc0003025a0, {0xc00070000c, 0x8}, {0xc6d200, 0xc000354280})
        github.com/Mrs4s/go-cqhttp/modules/api/api.go:219 +0x69e
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).Call(0xc0003025a0, {0xc00070000c, 0x8}, {0xc6d200, 0xc000354280})
        github.com/Mrs4s/go-cqhttp/modules/api/caller.go:34 +0xaa
github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest(0xc0003ff098, 0xc000350240, {0xc000700000, 0x722cb, 0xaa600})
        github.com/Mrs4s/go-cqhttp/server/websocket.go:421 +0x525
github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI.func2(0x0)
        github.com/Mrs4s/go-cqhttp/server/websocket.go:268 +0x95
created by github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI
        github.com/Mrs4s/go-cqhttp/server/websocket.go:266 +0x1b2
 
[2022-11-02 22:54:18] [WARNING]: 监听反向WS Universal时出现错误: read tcp 127.0.0.1:54892->127.0.0.1:13579: use of closed network connection 
[2022-11-02 22:54:19] [WARNING]: 向反向WS Universal服务器推送 Event 时出现错误: write tcp 127.0.0.1:54892->127.0.0.1:13579: use of closed network connection
```

**Comment by Z735803792** [comment]
同样的问题
ubuntu20.04,rc3版本.
简单说就是突然端开链接，但过会重连还是能连上，正常使用倒是没有必要的问题。
我这边出现这个问题的频率，大概是一个月7次左右，似乎以前就有这个问题，但这个月开启了上线推送才发现
![image](https://user-images.githubusercontent.com/70925546/201136836-8d9061c4-672b-44f0-bdb3-bed2b795e0cf.png)

**Comment by Mrs4s** [comment]
已修复
