### ISSUE TITLE
[Bug]: 运行cq-http一段时间后出现Protocol -> parse incoming packet error: return code unsuccessful: -10001，重启会提示一个空指针异常

### ISSUE THREAD

**Issue by swsun111** [Mrs4s/go-cqhttp#1784]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

V1.0.0-rc3

### 运行环境

CentOS

### 运行架构

None

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

运行过程中出现，Protocol -> parse incoming packet error: return code unsuccessful: -10001

### 期望的结果是什么？

正常运行

### 实际的结果是什么？

Protocol -> parse incoming packet error: return code unsuccessful: -10001

### 日志记录（可选）

```golang
[0m[37m[2022-11-30 11:41:30] [INFO]: 收到群 央妈的继承者们(751283123) 内 呼啸-南方基金(3005263171) 的消息: 出7d 14d AAA (-1621409259) 
[0m[31m[2022-11-30 12:50:48] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10001 
[0m[31m[2022-11-30 12:51:03] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10001 
[0m[31m[2022-11-30 12:54:49] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10001 
[0m[31m[2022-11-30 12:55:04] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10001 
[0m[31m[2022-11-30 12:58:49] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10001 
[0m[31m[2022-11-30 12:59:04] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10001 
[0m[31m[2022-11-30 13:02:49] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10001 
[0m[31m[2022-11-30 13:03:04] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10001 

-----------------------------------------------------------------------------------------------
[0m[37m[2022-12-01 19:30:40] [INFO]: 登录成功 欢迎使用: 资金 存单雪莹 
[0m[37m[2022-12-01 19:30:40] [INFO]: 开始加载好友列表... 
[0m[37m[2022-12-01 19:30:40] [INFO]: 共加载 349 个好友. 
[0m[37m[2022-12-01 19:30:40] [INFO]: 开始加载群列表... 
[0m[37m[2022-12-01 19:30:42] [INFO]: 共加载 13 个群. 
[0m[37m[2022-12-01 19:30:42] [INFO]: 资源初始化完成, 开始处理信息. 
[0m[37m[2022-12-01 19:30:42] [INFO]: アトリは、高性能ですから! 
[0m[37m[2022-12-01 19:30:42] [INFO]: 正在检查更新. 
[0m[37m[2022-12-01 19:30:42] [INFO]: HTTP POST上报器已启动: http://127.0.0.1:9001/bondchain-qq/api/qq-post-event 
[0m[37m[2022-12-01 19:30:42] [INFO]: CQ HTTP 服务器已启动: 172.17.0.1:5716 
[0m[37m[2022-12-01 19:30:42] [INFO]: 检查更新完成. 当前已运行最新版本. 
[0m[37m[2022-12-01 19:30:42] [INFO]: 开始诊断网络情况 
[0m[37m[2022-12-01 19:30:44] [INFO]: 网络诊断完成. 未发现问题 
[0m[31m[2022-12-01 19:37:46] [ERROR]: Protocol -> unexpected disconnect: EOF 
[0m[37m[2022-12-01 19:37:46] [INFO]: Protocol -> connect to server: 220.194.118.230:8080 
[0m[31m[2022-12-01 19:37:47] [ERROR]: Protocol -> panic on decoder ConfigPushSvc.PushReq : runtime error: index out of range [0] with length 0
goroutine 254 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
	github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:335 +0x65
panic({0xa6afa0, 0xc0004920d8})
	runtime/panic.go:838 +0x207
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).peakHead(...)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/binary/jce/reader.go:31
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).skipToTag(0xc000205d18?, 0x8?)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/binary/jce/reader.go:144 +0x105
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).ReadMapStrMapStrByte(0xc000205cf8, 0xd812cd13e59a79d4?)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/binary/jce/reader.go:421 +0x25
github.com/Mrs4s/MiraiGo/binary/jce.(*RequestDataVersion2).ReadFrom(...)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/binary/jce/structs.go:552
github.com/Mrs4s/MiraiGo/client.decodePushReqPacket(0xc000256000, 0x3f0?, {0xc0001bc000?, 0x15?, 0x36d329b5608c3b34?})
	github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/decoders.go:312 +0x133
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0002642d0)
	github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:346 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
	github.com/Mrs4s/MiraiGo@v0.0.0-20220621083050-ae8c187aa59d/client/network.go:332 +0x4b8
 
[0m[31m[2022-12-01 19:37:47] [ERROR]: 出现错误 packet decode error: ConfigPushSvc.PushReq - runtime error: index out of range [0] with length 0. 详细信息已转储至文件 dumps/1669894667.dump 请连同日志提交给开发者处理
```

### 补充说明（可选）

分割线以上为错误出现时日志，分割线以下为重启后日志

**Comment by swsun111** [comment]
> 你的 dumps/1669894667.dump 文件呢
您看看
[dumps.zip](https://github.com/Mrs4s/go-cqhttp/files/10150051/dumps.zip)

**Comment by Mrs4s** [comment]
这个应该是被挤了
