### ISSUE TITLE
[Bug]: packet decode error: MultiMsg.ApplyDown - runtime error

### ISSUE THREAD

**Issue by eve2ptp** [Mrs4s/go-cqhttp#1870]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc4

### 运行环境

Linux

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

WebSocket (反向)

### 使用协议

1 | Android Phone

### 重现步骤

not sure，it just normal running

### 期望的结果是什么？

No errors occur

### 实际的结果是什么？

No errors occur

### 日志记录（可选）

```golang
[2023-01-29 12:16:18] [ERROR]: Protocol -> panic on decoder MultiMsg.ApplyDown : runtime error: index out of range [0] with length 0
goroutine 74861 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x64
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/network.go:335 +0x48
panic({0x609660, 0x40000bc0f0})
        runtime/panic.go:884 +0x20c
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse(0x40004da140?, 0x49?, {0x40004da140, 0x49, 0x49})
        github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/multimsg.go:108 +0x8dc
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0x40000646e0)
        github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/network.go:346 +0x184
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/network.go:332 +0x4e4

[2023-01-29 12:16:18] [ERROR]: 出现错误 packet decode error: MultiMsg.ApplyDown - runtime error: index out of range [0] with length 0. 详细信息已转储至文件
dumps/1674965778.dump 请连同日志提交给开发者处理


dump file: [1674965778.zip](https://github.com/Mrs4s/go-cqhttp/files/10529220/1674965778.zip)
```

**Comment by wdvxdr1123** [comment]
duplicate with #1251
