### ISSUE TITLE
图片发送失败后程序崩溃

### ISSUE THREAD

**Issue by takayama-lily** [Mrs4s/go-cqhttp#19]
```
[2020-08-04 16:36:40] [INFO]: 收到好友 **(*******) 的消息: qqhead()
Packet Timed out
Packet Timed out
Packet Timed out
[2020-08-04 16:37:11] [WARNING]: 警告: 好友 *******消息图片上传失败.
panic: EOF

goroutine 7 [running]:
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200803034534-d8ed1a49ff8b/binary/reader.go:39
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadInt32(0xc000068ed8, 0x1)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200803034534-d8ed1a49ff8b/binary/reader.go:58 +0x13b
github.com/Mrs4s/MiraiGo/protocol/packets.ParseIncomingPacket(0x0, 0x0, 0x0, 0xc000480ba0, 0x10, 0x10, 0xc000032050, 0x0, 0x0)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200803034534-d8ed1a49ff8b/protocol/packets/global.go:87 +0x89
github.com/Mrs4s/MiraiGo/client.(*QQClient).loop(0xc0001b9340)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200803034534-d8ed1a49ff8b/client/client.go:743 +0x184
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).Login
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200803034534-d8ed1a49ff8b/client/client.go:151 +0x86
root@takayama:/mnt/d/ftp/go-cqhttp#
```

**Comment by Mrs4s** [comment]
出现频繁嘛。
这个问题应该是掉线导致的

**Comment by takayama-lily** [comment]
出现的不频繁。
但是我发现，如果图片地址有问题，消息会被阻塞，直到图片结果返回才会继续处理。
```
[2020-08-04 17:07:22] [INFO]: 收到好友 ******** 的消息: img("https://www.baidu.com")
[2020-08-04 17:07:26] [INFO]: 收到好友 ******** 的消息: .jrrp
[2020-08-04 17:07:40] [WARNING]: 警告: ******** 消息图片上传失败.
```
.jrrp的回复在17:07:40之后才出现。因为控制台没输出，不确定是反向ws阻塞了，还是输出阻塞了。

**Comment by takayama-lily** [comment]
打开了debug，有输出了。
```
[2020-08-04 17:21:40] [INFO]: 收到好友 高山(372914165) 的消息: img("https://www.baidu.com")
[2020-08-04 17:21:40] [DEBUG]: 向WS服务器 ws://usus.***.bid:3000 推送Event: {"font":0,"message":"img(\"https://www.baidu.com\")","message_id":-1226028300,"message_type":"private","post_type":"message","raw_message":"img(\"https://www.baidu.com\")","self_id":646702491,"sender":{"age":0,"nickname":"高山","sex":"unknown","user_id":372914165},"sub_type":"friend","time":1596529300,"user_id":372914165}
[2020-08-04 17:21:40] [DEBUG]: 反向WS接收到API调用: .handle_quick_operation 参数: {"context":{"font":0,"message":"img(\"https://www.baidu.com\")","message_id":-1226028300,"message_type":"private","post_type":"message","raw_message":"img(\"https://www.baidu.com\")","self_id":646702491,"sender":{"age":0,"nickname":"高山","sex":"unknown","user_id":372914165},"sub_type":"friend","time":1596529300,"user_id":372914165},"operation":{"reply":"[CQ:image,cache=1,file=https://www.baidu.com]","at_sender":false}}
[2020-08-04 17:21:43] [INFO]: 收到好友 高山(372914165) 的消息: .jrrp
[2020-08-04 17:21:43] [DEBUG]: 向WS服务器 ws://usus.***.bid:3000 推送Event: {"font":0,"message":".jrrp","message_id":-1041532318,"message_type":"private","post_type":"message","raw_message":".jrrp","self_id":646702491,"sender":{"age":0,"nickname":"高山","sex":"unknown","user_id":372914165},"sub_type":"friend","time":1596529303,"user_id":372914165}
[2020-08-04 17:21:58] [WARNING]: 警告: 好友 372914165 消息图片上传失败.
[2020-08-04 17:21:58] [DEBUG]: 反向WS接收到API调用: send_private_msg 参数: {"user_id":372914165,"message":"[CQ:at,qq=372914165] 今天的人品是: 82 [中吉]","auto_escape":false}
```

**Comment by Mrs4s** [comment]
这部分我会优化一下
