### ISSUE TITLE
[Bug]: Protocol -> panic on decoder MultiMsg.ApplyDown : runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by dfmjndm** [Mrs4s/go-cqhttp#1902]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

rc4

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

1

### 期望的结果是什么？

1

### 实际的结果是什么？

1

### 简单的复现代码/链接（可选）

```golang
1
```

### 日志记录（可选）

```golang
[2023-02-10 15:42:12] [ERROR]: Protocol -> panic on decoder MultiMsg.ApplyDown : runtime error: index out of range [0] with length 0
goroutine 275 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/network.go:335 +0x65
panic({0xa7e9c0, 0xc000853c20})
        runtime/panic.go:884 +0x212
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse(0xc000033270?, 0x49?, {0xc000033270, 0x49, 0x49})
        github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/multimsg.go:108 +0x9c5
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0007b1540)
        github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/network.go:346 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/network.go:332 +0x4cd
 
[2023-02-10 15:42:12] [ERROR]: 出现错误 packet decode error: MultiMsg.ApplyDown - runtime error: index out of range [0] with length 0. 详细信息已转储至文件 dumps/1676014932.dump 请连同日志提交给开发者处理
```

**Comment by Fader282** [comment]
我也是出现这个问题，二十多次后bot就被冻结下机了（悲）
附今天的dump文件

```
[2023-02-10 14:52:45] [ERROR]: Protocol -> panic on decoder MultiMsg.ApplyDown : runtime error: index out of range [0] with length 0
goroutine 48238 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
	github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/network.go:335 +0x65
panic({0x112cee0, 0xc00093b608})
	runtime/panic.go:884 +0x212
github.com/Mrs4s/MiraiGo/client.decodeMultiApplyDownResponse(0xc0000a8820?, 0x49?, {0xc0000a8820, 0x49, 0x49})
	github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/multimsg.go:108 +0x9c5
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc000808960)
	github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/network.go:346 +0x1c7
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
	github.com/Mrs4s/MiraiGo@v0.0.0-20221202060717-4658474c60dd/client/network.go:332 +0x4cd
 
[2023-02-10 14:52:45] [ERROR]: 出现错误 packet decode error: MultiMsg.ApplyDown - runtime error: index out of range [0] with length 0. 详细信息已转储至文件 dumps/1676011965.dump 请连同日志提交给开发者处理 
```
[1676011965.zip](https://github.com/Mrs4s/go-cqhttp/files/10706592/1676011965.zip)

**Comment by wdvxdr1123** [comment]
duplicate with #1251

**Comment by ilihu** [comment]
我今天也出现这个问题，报错一模一样。v1.0.0-rc3，Linux AMD64 平台
