### ISSUE TITLE
Websocket Connect Issue

### ISSUE THREAD

**Issue by masnn** [Mrs4s/go-cqhttp#2]
Server: go-cqhttp@0.9.2

```log
http: panic serving 127.0.0.1:10562: runtime error: index out of range [1] with length 1
goroutine 279 [running]:
net/http.(*conn).serve.func1(0xc00011c280)
        /usr/local/go/src/net/http/server.go:1772 +0x140
panic(0xbdddc0, 0xc0009949a0)
        /usr/local/go/src/runtime/panic.go:973 +0x3a4
github.com/Mrs4s/go-cqhttp/server.(*websocketServer).any(0x128a360, 0xd66ee0, 0xc00032c380, 0xc000a3e000)
        /github/workspace/server/websocket.go:241 +0x531
net/http.HandlerFunc.ServeHTTP(0xc00008a1c0, 0xd66ee0, 0xc00032c380, 0xc000a3e000)
        /usr/local/go/src/net/http/server.go:2012 +0x4b
net/http.(*ServeMux).ServeHTTP(0x128a320, 0xd66ee0, 0xc00032c380, 0xc000a3e000)
        /usr/local/go/src/net/http/server.go:2387 +0x1ac
net/http.serverHandler.ServeHTTP(0xc000a00000, 0xd66ee0, 0xc00032c380, 0xc000a3e000)
        /usr/local/go/src/net/http/server.go:2807 +0xaa
net/http.(*conn).serve(0xc00011c280, 0xd68ca0, 0xc000428040)
        /usr/local/go/src/net/http/server.go:1895 +0x873
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2933 +0x363
```

Client: ws@7.3.1

```
Error: socket hang up
    at createHangUpError (_http_client.js:332:15)
    at Socket.socketOnEnd (_http_client.js:435:23)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at ClientRequest.req.on (bot/node_modules/ws/lib/websocket.js:551:15)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketOnEnd (_http_client.js:435:9)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by masnn** [comment]
My fault.
