### ISSUE TITLE
[Bug]: TTS 引发 Websockets 错误

### ISSUE THREAD

**Issue by VermiIIi0n** [Mrs4s/go-cqhttp#2032]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0-rc5

### 运行环境

MacOS

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

发送 WS 请求:
```JSON
{
  "action": "send_group_msg",
  "params": {
    "group_id": <*****>,
    "message": [
      {
        "type": "tts",
        "data": {
          "text": "你好!"
        }
      }
    ]
  },
  "echo": "0"
}
```

在日志报错:

<details><summary>Log</summary> 

```shell
[2023-03-27 18:55:30] [ERROR]: 处置WS命令时发生无法恢复的异常：EOF
goroutine 59445 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x64
github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest.func1()
	github.com/Mrs4s/go-cqhttp/server/websocket.go:471 +0x3c
panic({0x101290f20, 0x1400008e060})
	runtime/panic.go:884 +0x1f4
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadByte(...)
	github.com/Mrs4s/MiraiGo@v0.0.0-20230317162854-fd83d24f6794/binary/reader.go:32
github.com/Mrs4s/MiraiGo/client.(*QQClient).GetTts(0x14000644000, {0x140004ac063, 0x7})
	github.com/Mrs4s/MiraiGo@v0.0.0-20230317162854-fd83d24f6794/client/http_api.go:92 +0x720
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).ConvertElement(0x1400046e000, 0x1016db860, {{0x140004ac04e, 0x3}, {0x1400007a0a0, 0x1, 0x1}}, 0x2)
	github.com/Mrs4s/go-cqhttp/coolq/cqcode.go:658 +0x3ff8
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).ConvertElements(0x5?, 0x140004ac044?, {0x14000694390?, 0x1, 0x0?}, 0x0?)
	github.com/Mrs4s/go-cqhttp/coolq/cqcode.go:417 +0xd4
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).ConvertObjectMessage(0x0?, 0x1016db860, {0x5, {0x140004ac044, 0x2a}, {0x0, 0x0}, 0x0, 0x44, {0x0, ...}}, ...)
	github.com/Mrs4s/go-cqhttp/coolq/cqcode.go:396 +0xc8
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendGroupMessage(0x1400046e000, 0x12dacfe9, {0x5, {0x140004ac044, 0x2a}, {0x0, 0x0}, 0x0, 0x44, {0x0, ...}}, ...)
	github.com/Mrs4s/go-cqhttp/coolq/api.go:757 +0xe4
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).call(0x14000374760, {0x140004ac00b, 0xe}, 0x1016db860, {0x10135aeb8, 0x1400045e410})
	github.com/Mrs4s/go-cqhttp/modules/api/api.go:43 +0xa6c
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).Call(0x14000374760, {0x140004ac00b, 0xe}, 0x0?, {0x10135aeb8, 0x1400045e410})
	github.com/Mrs4s/go-cqhttp/modules/api/caller.go:35 +0xb0
github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest(0x140000a8768, 0x1400046e000?, {0x140004ac000?, 0x7b?, 0x300?})
	github.com/Mrs4s/go-cqhttp/server/websocket.go:480 +0x2c4
github.com/Mrs4s/go-cqhttp/server.(*webSocketServer).listenAPI.func2(0x14000754330?)
	github.com/Mrs4s/go-cqhttp/server/websocket.go:460 +0x88
created by github.com/Mrs4s/go-cqhttp/server.(*webSocketServer).listenAPI
	github.com/Mrs4s/go-cqhttp/server/websocket.go:458 +0x144
```
</detailes>

### 期望的结果是什么？

正常发送 TTS 消息, 或者正常回报错误.

### 实际的结果是什么？

WS 连接因错误中断.

### 补充说明（可选）

提交 issue 时协议无法选择 Android Pad, 所以标的 iPad

**Comment by meowjiao321** [comment]
我这边也有这个错误，好久了都没修复

**Comment by afraidjpg** [comment]
我看了下源码这是因为在MiraiGo中，调用腾讯ttl接口后，从response中读取bytes的时候出错了，MiraiGo用了一个自建的buffer reader，然后逐个读取bytes的内容直到遇到`0x0d`，也就是ASCII的 \r 换行符

这是他的 ReadByte 代码：
```go
func (r *Reader) ReadByte() byte {
	b, err := r.buf.ReadByte()
	if err != nil {
		panic(err)
	}
	return b
}
```

这里底层实际调用了 `bytes.Reader.ReadByte()`

这是它的源码：
```go
// ReadByte implements the io.ByteReader interface.
func (r *Reader) ReadByte() (byte, error) {
	r.prevRune = -1
	if r.i >= int64(len(r.s)) {
		return 0, io.EOF     //  <--- 在这里，当读取到超出长度的时候（也就是读到结束），会返回一个结束符error
	}
	b := r.s[r.i]
	r.i++
	return b, nil
}
```

那么很显然就是没有读取到\r换行符直接读到response的结尾引发了异常。我并不太清楚腾讯在tts的接口上返回的具体数据格式。
但我认为假如没有读取到\r就直接panic，是个不太好的做法，作为一个常驻后台的应用，我觉得不应该这么轻易的panic掉，不然这样程序也太不稳定了。。。
