### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ialdaiaxiariyay** [Mrs4s/go-cqhttp#2039]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0-rc5

### 运行环境

CentOS

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | iPad

### 重现步骤

./go-cqhttp之后出现
[2023-04-01 11:05:23] [INFO]: 当前版本:v1.0.0-rc5
[2023-04-01 11:05:23] [INFO]: 将使用 device.json 内的设备信息运行Bot.
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/Mrs4s/MiraiGo/client/internal/auth.pkcs5Trimming(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230317162854-fd83d24f6794/client/internal/auth/qimei.go:107
github.com/Mrs4s/MiraiGo/client/internal/auth.aesDecrypt({0xfbc648, 0x0, 0x0}, {0xc0000281b0, 0x10, 0x10})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230317162854-fd83d24f6794/client/internal/auth/qimei.go:97 +0x105
github.com/Mrs4s/MiraiGo/client/internal/auth.(*Device).RequestQImei(0xc0000cca00)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230317162854-fd83d24f6794/client/internal/auth/qimei.go:66 +0x973
github.com/Mrs4s/MiraiGo/client/internal/auth.(*Device).ReadJson(0xc0000cca00, {0xc000212700, 0x315, 0x380})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230317162854-fd83d24f6794/client/internal/auth/device.go:154 +0xbc5
github.com/Mrs4s/go-cqhttp/cmd/gocq.LoginInteract()
        github.com/Mrs4s/go-cqhttp/cmd/gocq/main.go:161 +0x2fd
main.main()
        github.com/Mrs4s/go-cqhttp/main.go:20 +0x2a

### 期望的结果是什么？

[2023-04-01 11:16:46] [INFO]: 当前版本:v1.0.0-rc5
[2023-04-01 11:16:46] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2023-04-01 11:16:46] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2023-04-01 11:16:51] [INFO]: 开始尝试登录并同步消息...
[2023-04-01 11:16:51] [INFO]: 使用协议: Android Pad 8.9.33.10335
[2023-04-01 11:16:51] [INFO]: 从文件 data/versions/6.json 读取协议版本 Android Pad 8.9.35.10440.
[2023-04-01 11:16:52] [INFO]: Protocol -> connect to server: [::ffff:119.147.190.138]:8080
[2023-04-01 11:16:52] [WARNING]: Protocol -> device lock is disable. http api may fail.
[2023-04-01 11:16:53] [INFO]: 登录成功 欢迎使用: 緒山まひろ
[2023-04-01 11:16:53] [INFO]: 开始加载好友列表...
[2023-04-01 11:16:54] [INFO]: 共加载 2 个好友.
[2023-04-01 11:16:54] [INFO]: 开始加载群列表...
[2023-04-01 11:16:54] [INFO]: 共加载 0 个群.
[2023-04-01 11:16:54] [INFO]: 资源初始化完成, 开始处理信息.
[2023-04-01 11:16:54] [INFO]: アトリは、高性能ですから!
[2023-04-01 11:16:54] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:8080/onebot/v11/ws/
[2023-04-01 11:16:54] [INFO]: 正在检查更新.
[2023-04-01 11:16:54] [INFO]: 检查更新完成. 当前已运行最新版本.
[2023-04-01 11:16:54] [INFO]: 开始诊断网络情况
[2023-04-01 11:16:56] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connectex: No connection could be made because the target machine actively refused it.
[2023-04-01 11:16:57] [INFO]: 网络诊断完成. 未发现问题
[2023-04-01 11:16:59] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:8080/onebot/v11/ws/
[2023-04-01 11:17:01] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connectex: No connection could be made because the target machine actively refused it.

### 实际的结果是什么？

[root@localhost ~]# go-cqhttp
[2023-04-01 11:05:23] [INFO]: 当前版本:v1.0.0-rc5
[2023-04-01 11:05:23] [INFO]: 将使用 device.json 内的设备信息运行Bot.
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/Mrs4s/MiraiGo/client/internal/auth.pkcs5Trimming(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230317162854-fd83d24f6794/client/internal/auth/qimei.go:107
github.com/Mrs4s/MiraiGo/client/internal/auth.aesDecrypt({0xfbc648, 0x0, 0x0}, {0xc0000281b0, 0x10, 0x10})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230317162854-fd83d24f6794/client/internal/auth/qimei.go:97 +0x105
github.com/Mrs4s/MiraiGo/client/internal/auth.(*Device).RequestQImei(0xc0000cca00)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230317162854-fd83d24f6794/client/internal/auth/qimei.go:66 +0x973
github.com/Mrs4s/MiraiGo/client/internal/auth.(*Device).ReadJson(0xc0000cca00, {0xc000212700, 0x315, 0x380})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230317162854-fd83d24f6794/client/internal/auth/device.go:154 +0xbc5
github.com/Mrs4s/go-cqhttp/cmd/gocq.LoginInteract()
        github.com/Mrs4s/go-cqhttp/cmd/gocq/main.go:161 +0x2fd
main.main()
        github.com/Mrs4s/go-cqhttp/main.go:20 +0x2a
[root@localhost ~]#

**Comment by Mrs4s** [comment]
#2017  请尝试使用dev版本
