### ISSUE TITLE
[Bug]: 启动报错

### ISSUE THREAD

**Issue by baigeiapi** [Mrs4s/go-cqhttp#2047]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.0.0 -749cde2 

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

1 | Android Phone

### 重现步骤

启动报错

### 期望的结果是什么？

启动正常

### 实际的结果是什么？

修复

### 简单的复现代码/链接（可选）

```golang
[2023-04-03 16:45:04] [INFO]: Protocol -> connect to server: 222.94.109.123:8080 
[2023-04-03 16:45:04] [WARNING]: Protocol -> device lock is disable. http api may fail. 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x51c259]

goroutine 84 [running]:
compress/flate.(*decompressor).huffSym(0xc000538600, 0xc000538628)
        compress/flate/inflate.go:719 +0xf9
compress/flate.(*decompressor).huffmanBlock(0xc000538600?)
        compress/flate/inflate.go:494 +0x45
compress/flate.(*decompressor).nextBlock(0xc000538600)
        compress/flate/inflate.go:327 +0x19c
compress/flate.(*decompressor).Read(0xc000538600, {0xc00012a400, 0x200, 0x0?})
        compress/flate/inflate.go:347 +0x7e
compress/zlib.(*reader).Read(0xc000081220, {0xc00012a400, 0xc000081220?, 0x200})
        compress/zlib/reader.go:97 +0x57
bytes.(*Buffer).ReadFrom(0xc000087cd0, {0x7f199f882600, 0xc000081220})
        bytes/buffer.go:202 +0x98
github.com/Mrs4s/MiraiGo/binary.ZlibUncompress({0xc00054cc00, 0x1010, 0x1010})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/binary/utils.go:36 +0x14a
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).readSSOFrame(0x75344250453f6258?, 0xc0000811d0, {0xc00054b908?, 0x1060?, 0x1060?})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/internal/network/response.go:89 +0x798
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).ReadResponse(0xc00047c120, {0xc000549300, 0x1074, 0x1074})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/internal/network/response.go:52 +0x31b
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0xc0004f2000)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/network.go:356 +0x211
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/network.go:181 +0x1c5
```

### 日志记录（可选）

```golang
http://apilin.cn:65432/share/smhaArRq
```

### 补充说明（可选）

二次启动生成dump文件

**Comment by Mrs4s** [comment]
#2045
