### ISSUE TITLE
[Bug]:  删除 `session.token` 后会重新启动失败

### ISSUE THREAD

**Issue by FengLiuFeseliud** [Mrs4s/go-cqhttp#2054]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [x] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0

### 运行环境

其它（请在下方说明）

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

1 | Android Pad

#### Linux 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64

滑块验证，验证设备锁二维码完成后，重新启动会启动失败
删除 `session.token` 后会重新启动失败，`session.token`  生成后第二次启动成功
稳定失败

### 期望的结果是什么？

正常启动或者重新生成 `session.token` 后正常退出

### 实际的结果是什么？

https://user-images.githubusercontent.com/73475715/230209400-26ef18d8-0b30-49fc-880f-74153a535a64.mp4

### 日志记录（可选）

```golang
[2023-04-06 04:46:50] [INFO]: 当前版本:v1.0.0
[2023-04-06 04:46:50] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2023-04-06 04:46:50] [INFO]: 开始尝试登录并同步消息...
[2023-04-06 04:46:50] [INFO]: 使用协议: Android Pad 8.9.35.10440
[2023-04-06 04:46:51] [INFO]: Protocol -> connect to server: 222.94.109.78:8080
[2023-04-06 04:46:51] [WARNING]: Protocol -> device lock is disable. http api may fail.
[2023-04-06 04:46:53] [INFO]: 登录成功 欢迎使用: Apeiria System
[2023-04-06 04:46:53] [INFO]: 开始加载好友列表...
[2023-04-06 04:46:53] [INFO]: 共加载 3 个好友.
[2023-04-06 04:46:53] [INFO]: 开始加载群列表...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x712ced]

goroutine 64 [running]:
github.com/Mrs4s/MiraiGo/binary.ZlibUncompress({0xc000425500, 0x345e, 0x345e})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/binary/utils.go:35 +0xed
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).readSSOFrame(0x667b353a753a2d41?, 0xc00039d540, {0xc000422009?, 0x34c0?, 0x34c0?})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/internal/network/response.go:89 +0x798
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).ReadResponse(0xc000097548, {0xc0001f4000, 0x34d4, 0x34d4})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/internal/network/response.go:52 +0x31b
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0xc000224000)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/network.go:356 +0x211
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/network.go:181 +0x1c5
2 草 ./go-cqhttp -faststart                                   FengBot -> main ?
[2023-04-06 04:47:00] [INFO]: 当前版本:v1.0.0
[2023-04-06 04:47:00] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2023-04-06 04:47:00] [INFO]: 开始尝试登录并同步消息...
[2023-04-06 04:47:00] [INFO]: 使用协议: Android Pad 8.9.35.10440
[2023-04-06 04:47:00] [INFO]: Protocol -> connect to server: 114.222.112.229:8080
[2023-04-06 04:47:00] [WARNING]: Protocol -> device lock is disable. http api may fail.
[2023-04-06 04:47:04] [INFO]: 登录成功 欢迎使用: Apeiria System
[2023-04-06 04:47:04] [INFO]: 开始加载好友列表...
[2023-04-06 04:47:04] [INFO]: 共加载 3 个好友.
[2023-04-06 04:47:04] [INFO]: 开始加载群列表...
[2023-04-06 04:47:05] [INFO]: 共加载 5 个群.
[2023-04-06 04:47:05] [INFO]: 资源初始化完成, 开始处理信息.
[2023-04-06 04:47:05] [INFO]: アトリは、高性能ですから!
[2023-04-06 04:47:05] [INFO]: 正在检查更新.
[2023-04-06 04:47:05] [INFO]: CQ WebSocket 服务器已启动: [::]:8080
[2023-04-06 04:47:06] [INFO]: 检查更新完成. 当前已运行最新版本.
[2023-04-06 04:47:06] [INFO]: 开始诊断网络情况
[2023-04-06 04:47:08] [INFO]: 网络诊断完成. 未发现问题
^C%
草 rm ./session.token                                         FengBot -> main ?
草 ./go-cqhttp -faststart                                     FengBot -> main ?
[2023-04-06 04:47:16] [INFO]: 当前版本:v1.0.0
[2023-04-06 04:47:16] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2023-04-06 04:47:17] [INFO]: 开始尝试登录并同步消息...
[2023-04-06 04:47:17] [INFO]: 使用协议: Android Pad 8.9.35.10440
[2023-04-06 04:47:17] [INFO]: Protocol -> connect to server: [::ffff:58.212.179.185]:8080
[2023-04-06 04:47:17] [WARNING]: Protocol -> device lock is disable. http api may fail.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x51c259]

goroutine 114 [running]:
compress/flate.(*decompressor).huffSym(0xc000415300, 0xc000415328)
        compress/flate/inflate.go:719 +0xf9
compress/flate.(*decompressor).huffmanBlock(0xc000415300?)
        compress/flate/inflate.go:494 +0x45
compress/flate.(*decompressor).nextBlock(0xc000415300)
        compress/flate/inflate.go:327 +0x19c
compress/flate.(*decompressor).Read(0xc000415300, {0xc00017a000, 0x200, 0x0?})
        compress/flate/inflate.go:347 +0x7e
compress/zlib.(*reader).Read(0xc0003a6460, {0xc00017a000, 0xc0003a6460?, 0x200})
        compress/zlib/reader.go:97 +0x57
bytes.(*Buffer).ReadFrom(0xc0000eecd0, {0x7f492f7198a8, 0xc0003a6460})
        bytes/buffer.go:202 +0x98
github.com/Mrs4s/MiraiGo/binary.ZlibUncompress({0xc00025c000, 0x5ed, 0x5ed})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/binary/utils.go:36 +0x14a
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).readSSOFrame(0x6458715735766870?, 0xc0003a6410, {0xc0003fce08?, 0x640?, 0x640?})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/internal/network/response.go:89 +0x798
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).ReadResponse(0xc000398078, {0xc0003fc000, 0x654, 0x654})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/internal/network/response.go:52 +0x31b
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0xc0002f6000)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/network.go:356 +0x211
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/network.go:181 +0x1c5
```

**Comment by FengLiuFeseliud** [comment]
可能是代理网络？

**Comment by kanbereina** [comment]
session.token不是用来保持用户会话状态的么
运行在服务器上需要这个吧

**Comment by FengLiuFeseliud** [comment]
> session.token不是用来保持用户会话状态的么 运行在服务器上需要这个吧

旧版本删除了也会重新登录运行，不会不能启动，估计是网络问题

**Comment by Mrs4s** [comment]
请尝试最新版本
