### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by neal240** [Mrs4s/go-cqhttp#2072]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

1 | Android Phone

### 重现步骤

启动gocq

### 期望的结果是什么？

成功启动gocq

### 实际的结果是什么？

无法启动

### 日志记录（可选）

```golang
root@neal:/usr/bin# go-cqhttp
[2023-04-08 21:51:55] [INFO]: 当前版本:v1.0.0
[2023-04-08 21:51:55] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2023-04-08 21:51:55] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2023-04-08 21:52:00] [INFO]: 开始尝试登录并同步消息...
[2023-04-08 21:52:00] [INFO]: 使用协议: Android Pad 8.9.35.10440
[2023-04-08 21:51:16] [INFO]: 正在检查协议更新...
[2023-04-08 21:51:20] [INFO]: 检测到协议更新: 8.9.35.10440 -> 8.9.38.10545
[2023-04-08 21:51:20] [INFO]: 如果登录时出现版本过低错误, 可尝试使用 -update-protocol 参数启动
[2023-04-08 21:51:20] [INFO]: Protocol -> connect to server: [::ffff:36.155.207.186]:14000
[2023-04-08 21:51:20] [WARNING]: Protocol -> device lock is disable. http api may fail.
[2023-04-08 21:51:21] [INFO]: 登录成功 欢迎使用: 朋友
[2023-04-08 21:51:21] [INFO]: 开始加载好友列表...
[2023-04-08 21:51:21] [INFO]: 共加载 5 个好友.
[2023-04-08 21:51:21] [INFO]: 开始加载群列表...
[2023-04-08 21:51:21] [ERROR]: Protocol -> panic on decoder friendlist.GetTroopListReqV2 : runtime error: index out of range [2348] with length 2348
goroutine 119 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/network.go:393 +0x65
panic({0xab4340, 0xc0000260f0})
        runtime/panic.go:884 +0x213
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).peakHead(...)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/binary/jce/reader.go:31
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).skipToTag(0xc0005ee578, 0x1)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/binary/jce/reader.go:148 +0xf2
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).ReadInt16(0xc0002a9d78, 0xc0005ee520?)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/binary/jce/reader.go:181 +0x25
github.com/Mrs4s/MiraiGo/binary/jce.(*RequestPacket).ReadFrom(0xc0002a9d98, 0xc000354090?)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/binary/jce/structs.go:539 +0x2f
github.com/Mrs4s/MiraiGo/client.decodeGroupListResponse(0xc0005f0000, 0x92c?)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/decoders.go:549 +0xc5
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0004d0000)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/network.go:405 +0x182
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/network.go:390 +0x4cd

[2023-04-08 21:51:21] [ERROR]: 出现错误 packet decode error: friendlist.GetTroopListReqV2 - runtime error: index out of range [2348] with length 2348. 详细信息已转储至文件 dumps/1680961881.dump 请连同日志提交给开发者处理
[2023-04-08 21:51:23] [INFO]: 收到服务器地址更新通知, 将在下一次重连时应用.
[2023-04-08 21:51:36] [ERROR]: Protocol -> parse incoming packet error: packet dropped
[2023-04-08 21:51:36] [WARNING]: Bot已离线: session expired
[2023-04-08 21:51:39] [WARNING]: 将在 3 秒后尝试重连. 重连次数：2/0
[2023-04-08 21:51:42] [WARNING]: 尝试重连...
[2023-04-08 21:51:42] [INFO]: Protocol -> connect to server: 36.155.201.96:14000
[2023-04-08 21:51:43] [ERROR]: Protocol -> parse incoming packet error: packet dropped
[2023-04-08 21:51:51] [FATAL]: 遇到错误: Packet timed out
```

**Comment by fromann** [comment]
也启动不起来

~~~txt
root@ss:~/QQRobot/QBot# ./go-cqhttp
[2023-04-08 22:42:02] [INFO]: 当前版本:v1.0.0
[2023-04-08 22:42:02] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2023-04-08 22:42:02] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2023-04-08 22:42:07] [INFO]: 开始尝试登录并同步消息...
[2023-04-08 22:42:07] [INFO]: 使用协议: Android Pad 8.9.35.10440
[2023-04-08 22:42:07] [INFO]: 从文件 data/versions/6.json 读取协议版本 Android Pad 8.9.38.10545.
[2023-04-08 22:42:07] [INFO]: 正在检查协议更新...
[2023-04-08 22:42:09] [INFO]: Protocol -> connect to server: 120.241.150.69:8080
[2023-04-08 22:42:09] [WARNING]: 登录需要滑条验证码, 请验证后重试.
[2023-04-08 22:42:09] [WARNING]: 请选择提交滑块ticket方式:
[2023-04-08 22:42:09] [WARNING]: 1. 自动提交
[2023-04-08 22:42:09] [WARNING]: 2. 手动抓取提交
[2023-04-08 22:42:09] [WARNING]: 请输入(1 - 2)：
1
[2023-04-08 22:43:38] [WARNING]: 请前往该地址验证 -> **这里有链接隐藏啦**
panic: assignment to entry in nil map
goroutine 99 [running]:
vendor/golang.org/x/net/http2/hpack.(*headerFieldTable).addEntry(...)
        vendor/golang.org/x/net/http2/hpack/tables.go:58
vendor/golang.org/x/net/http2/hpack.(*dynamicTable).add(0xc000221540, {{0xaff89c, 0x4}, {0xc0004a3c60, 0x1d}, 0x0})
        vendor/golang.org/x/net/http2/hpack/hpack.go:174 +0xb5
vendor/golang.org/x/net/http2/hpack.(*Decoder).parseFieldLiteral(0xc000221540, 0xe0?, 0x0)
        vendor/golang.org/x/net/http2/hpack/hpack.go:393 +0x365
vendor/golang.org/x/net/http2/hpack.(*Decoder).parseHeaderFieldRepr(0xc0002a8c40?)
        vendor/golang.org/x/net/http2/hpack/hpack.go:316 +0x114
vendor/golang.org/x/net/http2/hpack.(*Decoder).Write(0xc000221540, {0xc00012a800?, 0x113, 0x11300040101?})
        vendor/golang.org/x/net/http2/hpack/hpack.go:262 +0x132
net/http.(*http2Framer).readMetaFrame(0xc000240e00, 0xc000075cb0)
        net/http/h2_bundle.go:2904 +0x305
net/http.(*http2Framer).ReadFrame(0xc000240e00)
        net/http/h2_bundle.go:1856 +0x3e5
net/http.(*http2clientConnReadLoop).run(0xc0004c7f98)
        net/http/h2_bundle.go:9187 +0x12e
net/http.(*http2ClientConn).readLoop(0xc000003080)
        net/http/h2_bundle.go:9082 +0x6f
created by net/http.(*http2Transport).newClientConn
        net/http/h2_bundle.go:7779 +0xc3c
root@ss:~/QQRobot/QBot#
~~~

解决了踢我一脚

**Comment by xxtg666** [comment]
试试看用v1.0.0-rc5版本

**Comment by GiGaFotress** [comment]
不能用1,选择2并且手动抓吧

**Comment by neal240** [comment]
退回rc5版本就能用了，看来就是新版有bug

**Comment by Mrs4s** [comment]
请尝试最新版本
