### ISSUE TITLE
[Bug?]: panic on decoder StatSvc.GetDevLoginInfo

### ISSUE THREAD

**Issue by FengLiuFeseliud** [Mrs4s/go-cqhttp#2079]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [x] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.0

### 运行环境

Linux

### 运行架构

AMD64

### 连接方式

WebSocket (正向)

### 使用协议

0 | iPad

### 重现步骤

滑块启动

### 期望的结果是什么？

正常启动

### 实际的结果是什么？

[dump 1681114338.zip](https://github.com/Mrs4s/go-cqhttp/files/11188917/1681114338.zip)

### 日志记录（可选）

```golang
[2023-04-10 16:12:04,140][go-cqhttp/WARNING] PyCqBot: go-cqhttp 警告 登录需要滑条验证码, 请验证后重试.
[2023-04-10 16:12:04,141][go-cqhttp/WARNING] PyCqBot: go-cqhttp 警告 请选择提交滑块ticket方式:
[2023-04-10 16:12:04,141][go-cqhttp/WARNING] PyCqBot: go-cqhttp 警告 1. 自动提交
[2023-04-10 16:12:04,141][go-cqhttp/WARNING] PyCqBot: go-cqhttp 警告 2. 手动抓取提交
[2023-04-10 16:12:04,142][go-cqhttp/WARNING] PyCqBot: go-cqhttp 警告 请输入(1 - 2)：
1
[2023-04-10 16:12:05,999][go-cqhttp/WARNING] PyCqBot: go-cqhttp 警告 请前往该地址验证 -> https://captcha.go-cqhttp.org/captcha?id=E8Vz730Q&style=simple&aid=16&uin=1718089268&sid=2991599823204107476&cap_cd=5VoLO31f7jcGR6pW-NY_BpPgC6GF1CQ1wcm3uACdzf7oUUYUYEHSsQ**&clientype=1&apptype=2
[2023-04-10 16:12:18,371][go-cqhttp/WARNING] PyCqBot: go-cqhttp 警告 Protocol -> device lock is disable. http api may fail.
[2023-04-10 16:12:18,917][go-cqhttp/ERROR] PyCqBot: go-cqhttp 发生错误 Protocol -> panic on decoder StatSvc.GetDevLoginInfo : runtime error: index out of range [2914] with length 2913
goroutine 91 [running]:
runtime/debug.Stack()
runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/network.go:393 +0x65
panic({0xab4340, 0xc000028888})
runtime/panic.go:884 +0x213
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).peakHead(...)
github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/binary/jce/reader.go:31
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).skipToTag(0xc000047e90, 0x1)
github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/binary/jce/reader.go:148 +0xf2
github.com/Mrs4s/MiraiGo/binary/jce.(*JceReader).ReadInt16(0xc000335e90, 0xc000047ef0?)
github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/binary/jce/reader.go:181 +0x25
github.com/Mrs4s/MiraiGo/binary/jce.(*RequestPacket).ReadFrom(0xc000335eb0, 0xc0004ca3d0?)
github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/binary/jce/structs.go:539 +0x2f
github.com/Mrs4s/MiraiGo/client.decodeDevListResponse(0xc000193000?, 0xb61?)
github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/sync.go:286 +0xad
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc000320300)
github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/network.go:405 +0x182
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/network.go:390 +0x4cd
[2023-04-10 16:12:18,918][go-cqhttp/ERROR] PyCqBot: go-cqhttp 发生错误 出现错误 packet decode error: StatSvc.GetDevLoginInfo - runtime error: index out of range [2914] with length 2913. 详细信息已转储至文件 dumps/1681114338.dump 请连同日志提交给开发者处理
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x712ced]

goroutine 98 [running]:
github.com/Mrs4s/MiraiGo/binary.ZlibUncompress({0xc0000e2a80, 0xa29, 0xa29})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/binary/utils.go:35 +0xed
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).readSSOFrame(0x7a5054726e367741?, 0xc0004b8cd0, {0xc0000e2004?, 0xa78?, 0xa78?})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/internal/network/response.go:89 +0x798
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).ReadResponse(0xc0000c2048, {0xc000193c00, 0xa8c, 0xa8c})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/internal/network/response.go:52 +0x31b
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0xc0000e0000)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/network.go:356 +0x211
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).connect.func1
        github.com/Mrs4s/MiraiGo@v0.0.0-20230401072048-f8d9841755b5/client/network.go:181 +0x1c5

## 另外一种情况

[2023-04-10 16:23:08] [INFO]: 当前版本:v1.0.0 
[2023-04-10 16:23:08] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2023-04-10 16:23:08] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2023-04-10 16:23:13] [INFO]: 开始尝试登录并同步消息... 
[2023-04-10 16:23:13] [INFO]: 使用协议: Android Pad 8.9.35.10440 
[2023-04-10 16:23:14] [INFO]: 正在检查协议更新... 
[2023-04-10 16:23:15] [INFO]: 检测到协议更新: 8.9.35.10440 -> 8.9.38.10545 
[2023-04-10 16:23:15] [INFO]: 如果登录时出现版本过低错误, 可尝试使用 -update-protocol 参数启动 
[2023-04-10 16:23:15] [INFO]: Protocol -> connect to server: 114.222.112.229:8080 
[2023-04-10 16:23:15] [WARNING]: 登录需要滑条验证码, 请验证后重试. 
[2023-04-10 16:23:15] [WARNING]: 请选择提交滑块ticket方式: 
[2023-04-10 16:23:15] [WARNING]: 1. 自动提交 
[2023-04-10 16:23:15] [WARNING]: 2. 手动抓取提交 
[2023-04-10 16:23:15] [WARNING]: 请输入(1 - 2)： 
1
[2023-04-10 16:23:16] [WARNING]: 请前往该地址验证 -> https://captcha.go-cqhttp.org/captcha?id=HDbXWdlo&style=simple&aid=16&uin=1718089268&sid=2111901894333155187&cap_cd=UGZ6LGLgBZ0Y19esYWO_FNc3PoAALy9ZDKLdTPDY4_o2iMesX5JmEg**&clientype=1&apptype=2  
[2023-04-10 16:23:34] [WARNING]: Protocol -> device lock is disable. http api may fail. 
[2023-04-10 16:23:35] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: 1577418172 
[2023-04-10 16:23:35] [ERROR]: Protocol -> parse incoming packet error: packet dropped 
```

**Comment by Mrs4s** [comment]
请尝试最新版本
