### ISSUE TITLE
[Bug]: 无法登录 panic: invalid ip

### ISSUE THREAD

**Issue by Coolkids** [Mrs4s/go-cqhttp#2106]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

最新版本

### 运行环境

Linux

### 运行架构

X86

### 连接方式

WS反向代理

### 使用协议

1 | Android Phone

### 使用[aoki](https://github.com/MrXiaoM/Aoki)生成device.json数据 按照文档编写device.json 
除了
```javascript
 {
  "imsi_md5": "xxx",
  "android_id": "xxx",
  "vendor_name": "xxx",
  "vendor_os_name": "xxx"
}
``` 
这4个字段没写
### 期望的结果是什么？

正常登录

### 实际的结果是什么？

无法登录代码报错

### 日志记录（可选）

```golang
������&---Setup Timezone to Asia/Shanghai---
---Checking if UID: 99 matches user---
usermod: no changes
---Checking if GID: 100 matches user---
usermod: no changes
---Setting umask to 002---
---Taking ownership of data...---
Starting...
]0;go-cqhttp (devel) © 2020 - 2023 Mrs4s[2023-04-21 12:27:17] [INFO]: 当前版本:(devel) 
[2023-04-21 12:27:17] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2023-04-21 12:27:17] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2023-04-21 12:27:22] [INFO]: 开始尝试登录并同步消息... 
[2023-04-21 12:27:22] [INFO]: 使用协议: Android Pad 8.9.35.10440 
[2023-04-21 12:27:22] [INFO]: 正在检查协议更新... 
[2023-04-21 12:27:22] [INFO]: 检测到协议更新: 8.9.35.10440 -> 8.9.38.10545 
[2023-04-21 12:27:22] [INFO]: 如果登录时出现版本过低错误, 可尝试使用 -update-protocol 参数启动 
[2023-04-21 12:27:22] [INFO]: Protocol -> connect to server: 180.109.192.45:8080 
panic: invalid ip
goroutine 1 [running]:
github.com/Mrs4s/MiraiGo/internal/tlv.T1(0x0?, {0x0?, 0xc0004b9504?, 0xb0c49e?})
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20230401072048-f8d9841755b5/internal/tlv/t1.go:12 +0x77
github.com/Mrs4s/MiraiGo/client.(*QQClient).buildLoginPacket(0xc0002e6000)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20230401072048-f8d9841755b5/client/builders.go:52 +0xa5
github.com/Mrs4s/MiraiGo/client.(*QQClient).Login(0xc0002e6000)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20230401072048-f8d9841755b5/client/client.go:249 +0x56
github.com/Mrs4s/go-cqhttp/cmd/gocq.commonLogin()
	/build/cmd/gocq/login.go:72 +0x25
github.com/Mrs4s/go-cqhttp/cmd/gocq.LoginInteract()
	/build/cmd/gocq/main.go:306 +0x17ed
main.main()
	/build/main.go:20 +0x2a
������&---Setup Timezone to Asia/Shanghai---
---Checking if UID: 99 matches user---
usermod: no changes
---Checking if GID: 100 matches user---
usermod: no changes
---Setting umask to 002---
---Taking ownership of data...---
Starting...
]0;go-cqhttp (devel) © 2020 - 2023 Mrs4s[2023-04-21 12:27:48] [INFO]: 当前版本:(devel) 
[2023-04-21 12:27:48] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2023-04-21 12:27:48] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2023-04-21 12:27:53] [INFO]: 开始尝试登录并同步消息... 
[2023-04-21 12:27:53] [INFO]: 使用协议: Android Pad 8.9.35.10440 
[2023-04-21 12:27:54] [INFO]: 正在检查协议更新... 
[2023-04-21 12:27:54] [INFO]: 检测到协议更新: 8.9.35.10440 -> 8.9.38.10545 
[2023-04-21 12:27:54] [INFO]: 如果登录时出现版本过低错误, 可尝试使用 -update-protocol 参数启动 
[2023-04-21 12:27:54] [INFO]: Protocol -> connect to server: [::ffff:114.222.113.185]:443 
panic: invalid ip
goroutine 1 [running]:
github.com/Mrs4s/MiraiGo/internal/tlv.T1(0x0?, {0x0?, 0xc0004b9504?, 0xb0c49e?})
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20230401072048-f8d9841755b5/internal/tlv/t1.go:12 +0x77
github.com/Mrs4s/MiraiGo/client.(*QQClient).buildLoginPacket(0xc0003ee000)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20230401072048-f8d9841755b5/client/builders.go:52 +0xa5
github.com/Mrs4s/MiraiGo/client.(*QQClient).Login(0xc0003ee000)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20230401072048-f8d9841755b5/client/client.go:249 +0x56
github.com/Mrs4s/go-cqhttp/cmd/gocq.commonLogin()
	/build/cmd/gocq/login.go:72 +0x25
github.com/Mrs4s/go-cqhttp/cmd/gocq.LoginInteract()
	/build/cmd/gocq/main.go:306 +0x17ed
main.main()
	/build/main.go:20 +0x2a
������&---Setup Timezone to Asia/Shanghai---
---Checking if UID: 99 matches user---
usermod: no changes
---Checking if GID: 100 matches user---
usermod: no changes
---Setting umask to 002---
---Taking ownership of data...---
Starting...
]0;go-cqhttp (devel) © 2020 - 2023 Mrs4s[2023-04-21 12:28:45] [INFO]: 当前版本:(devel) 
[2023-04-21 12:28:45] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2023-04-21 12:28:45] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2023-04-21 12:28:50] [INFO]: 开始尝试登录并同步消息... 
[2023-04-21 12:28:50] [INFO]: 使用协议: Android Pad 8.9.35.10440 
[2023-04-21 12:28:51] [INFO]: 正在检查协议更新... 
[2023-04-21 12:28:51] [INFO]: 检测到协议更新: 8.9.35.10440 -> 8.9.38.10545 
[2023-04-21 12:28:51] [INFO]: 如果登录时出现版本过低错误, 可尝试使用 -update-protocol 参数启动 
[2023-04-21 12:28:51] [INFO]: Protocol -> connect to server: 180.109.192.45:8080 
panic: invalid ip
goroutine 1 [running]:
github.com/Mrs4s/MiraiGo/internal/tlv.T1(0x0?, {0x0?, 0x416d73?, 0x2000?})
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20230401072048-f8d9841755b5/internal/tlv/t1.go:12 +0x77
github.com/Mrs4s/MiraiGo/client.(*QQClient).buildLoginPacket(0xc0005ca000)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20230401072048-f8d9841755b5/client/builders.go:52 +0xa5
github.com/Mrs4s/MiraiGo/client.(*QQClient).Login(0xc0005ca000)
	/go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20230401072048-f8d9841755b5/client/client.go:249 +0x56
github.com/Mrs4s/go-cqhttp/cmd/gocq.commonLogin()
	/build/cmd/gocq/login.go:72 +0x25
github.com/Mrs4s/go-cqhttp/cmd/gocq.LoginInteract()
	/build/cmd/gocq/main.go:306 +0x17ed
main.main()
	/build/main.go:20 +0x2a
```

**Comment by findingwch** [comment]
为什么关闭了，我也遇到了
