### ISSUE TITLE
[Bug]: 启动时配置文件一直出错，明明写对了呀！

### ISSUE THREAD

**Issue by zixusen** [Mrs4s/go-cqhttp#2169]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

go-cqhttp.exe

### 运行环境

Windows (64)

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

WebSocket (反向)

### 使用协议

2 | Android Watch

### 重现步骤

出现这个：
Active code page: 65001
2023-05-26 18:20:25.618 | ERROR    | config:load_config:610 - 15 validation errors for Config
openai -> accounts -> 1 -> email
  field required (type=value_error.missing)
openai -> accounts -> 1 -> password
  field required (type=value_error.missing)
openai -> accounts -> 1 -> session_token
  field required (type=value_error.missing)
openai -> accounts -> 1 -> access_token
  field required (type=value_error.missing)
openai -> accounts -> 1 -> api_key
  field required (type=value_error.missing)
openai -> accounts -> 2 -> email
  field required (type=value_error.missing)
openai -> accounts -> 2 -> password
  field required (type=value_error.missing)
openai -> accounts -> 2 -> session_token
  field required (type=value_error.missing)
openai -> accounts -> 2 -> access_token
  field required (type=value_error.missing)
openai -> accounts -> 2 -> api_key
  field required (type=value_error.missing)
openai -> accounts -> 3 -> email
  field required (type=value_error.missing)
openai -> accounts -> 3 -> password
  field required (type=value_error.missing)
openai -> accounts -> 3 -> session_token
  field required (type=value_error.missing)
openai -> accounts -> 3 -> access_token
  field required (type=value_error.missing)
openai -> accounts -> 3 -> api_key
  field required (type=value_error.missing)
Traceback (most recent call last):

  File "F:\xin\chatgpt\bot.py", line 10, in <module>
    from constants import config, botManager

  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "F:\xin\chatgpt\constants.py", line 6, in <module>
    config = Config.load_config()
             │      └ <staticmethod(<function Config.load_config at 0x0000023242CC9D00>)>
             └ <class 'config.Config'>

> File "F:\xin\chatgpt\config.py", line 606, in load_config
    return Config.parse_obj(toml.loads(str(guessed_str)))
           │      │         │    │         └ <CharsetMatch 'utf_8' bytes(86c01eaf38ba3511f2a3a8d25f56056238d5e841944c85c32b6e235b5859970b)>
           │      │         │    └ <function loads at 0x0000023242CC8040>
           │      │         └ <module 'toml' from 'F:\\xin\\python3.11\\Lib\\site-packages\\toml\\__init__.py'>
           │      └ <classmethod(<cyfunction BaseModel.parse_obj at 0x0000023241C69B10>)>
           └ <class 'config.Config'>

  File "pydantic\main.py", line 526, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)

  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error

pydantic.error_wrappers.ValidationError: 15 validation errors for Config
openai -> accounts -> 1 -> email
  field required (type=value_error.missing)
openai -> accounts -> 1 -> password
  field required (type=value_error.missing)
openai -> accounts -> 1 -> session_token
  field required (type=value_error.missing)
openai -> accounts -> 1 -> access_token
  field required (type=value_error.missing)
openai -> accounts -> 1 -> api_key
  field required (type=value_error.missing)
openai -> accounts -> 2 -> email
  field required (type=value_error.missing)
openai -> accounts -> 2 -> password
  field required (type=value_error.missing)
openai -> accounts -> 2 -> session_token
  field required (type=value_error.missing)
openai -> accounts -> 2 -> access_token
  field required (type=value_error.missing)
openai -> accounts -> 2 -> api_key
  field required (type=value_error.missing)
openai -> accounts -> 3 -> email
  field required (type=value_error.missing)
openai -> accounts -> 3 -> password
  field required (type=value_error.missing)
openai -> accounts -> 3 -> session_token
  field required (type=value_error.missing)
openai -> accounts -> 3 -> access_token
  field required (type=value_error.missing)
openai -> accounts -> 3 -> api_key
  field required (type=value_error.missing)
2023-05-26 18:20:25.643 | ERROR    | config:load_config:611 - 配置文件有误，请重新修改！
程序已停止运行。
Press any key to continue . . .

### 期望的结果是什么？

配置文件正确，并且我的
1.启动ChatGPT.cmd
2.启动go-cqhttp.cmd
都能正常运行！！！！！！！！！！！
------------------------------------------------------------
以下是我的config.cfg配置文件：
# 这里是 ChatGPT for QQ 的所有配置文件
# 请注意：以 "#" 开头的文本均为注释
# 不会被程序读取
# 如果你想要使用某个设置，请确保前面没有 "#" 号

########################
# 配置文件编写教程：
# https://chatgpt-qq.lss233.com/
########################
[onebot]
qq=477548883
manager_qq =3378736516

[openai]
# 如果你想添加 Claude、Bing 等 AI，请阅读【教程】
browserless_endpoint = "https://chatgpt-proxy.lss233.com/api/"
[[openai.accounts]]
access_token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJtYXJ0aGVsb2VocmVyQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS9hdXRoIjp7InVzZXJfaWQiOiJ1c2VyLVhFb2lsbFZ0dkpZcGdCTFBIOVUwaUduSCJ9LCJpc3MiOiJodHRwczovL2F1dGgwLm9wZW5haS5jb20vIiwic3ViIjoid2luZG93c2xpdmV8YTJmODM0ZjYwY2VhMWMyMiIsImF1ZCI6WyJodHRwczovL2FwaS5vcGVuYWkuY29tL3YxIiwiaHR0cHM6Ly9vcGVuYWkub3BlbmFpLmF1dGgwYXBwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2ODUwNzg1MjYsImV4cCI6MTY4NjI4ODEyNiwiYXpwIjoiVGRKSWNiZTE2V29USHROOTVueXl3aDVFNHlPbzZJdEciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG1vZGVsLnJlYWQgbW9kZWwucmVxdWVzdCBvcmdhbml6YXRpb24ucmVhZCBvcmdhbml6YXRpb24ud3JpdGUifQ.DJBabuvGaLfqlODFz38iY40wBwRt2MrFbLVndT7YkSLdO6j8nEQEE8Zrjd4ZHPeyjq0RE7Z0KXjSHVs5wGhGQikCKfT8TF2hO3PYtNS2ngqhW7PZmDgu1j8DGy77nkMYCDWvxWUBfSwoL-oQHxHW4L1_wZnw7sySnwnOIEiYBV0eK8UqbTQjGzsAmBGkG9FtuhyINL_JFxe5GRDlNdSitYI7_sR4Rw1NBsvSfXPr0EMi9qsQ8ZO87W19S7f5BmyEto0VElr48X98YJL0CrNI4Mn__Ht8kA6jGSLp8dWgZAci44LF1wrrZs9Ac2Og1gyTB4q_wCMAX_oTvtHRyy7Qfw"
proxy="http://127.0.0.1:7890"
[[openai.accounts]]
auto_remove_old_conversations = true
proxy="http://127.0.0.1:7890"
[[openai.accounts]]
title_pattern="qq-{session_id}"
proxy="http://127.0.0.1:7890"
[[openai.accounts]]
paid=true
model="text-davinci-002-render-sha"
proxy="http://127.0.0.1:7890"
[presets]
# 切换预设的命令： 加载预设 猫娘
command = "加载预设 (\\w+)"

[presets.keywords]
# 预设关键词 <-> 实际文件
"聊天" = "presets/issue402.txt"
"猫娘" = "presets/catgirl.txt"

### 实际的结果是什么？

配置错误

**Comment by lixiangwuxian** [comment]
粘贴代码块请使用` ``` `包裹。隐私信息建议打码后放出

**Comment by Mrs4s** [comment]
这不是gocq
