### ISSUE TITLE
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404

### ISSUE THREAD

**Issue by luasqwd** [Mrs4s/go-cqhttp#2171]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

v1.0.1

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

HTTP

### 使用协议

0 | iPad

### 重现步骤

[2023-05-27 17:44:09,802][MainThread/INFO] PyCqBot: 正在连接 go-cqhttp websocket 服务
Traceback (most recent call last):
  File "D:\AAA\Luciferbot\Spit_chatBot-main\Spit_chatBot-main\qqbot.py", line 446, in <module>
    bot.start(start_go_cqhttp= False)
  File "D:\AAA\Anaconda3\a\lib\site-packages\pycqBot\cqHttpApi.py", line 350, in start
    self._websocket_start()
  File "D:\AAA\Anaconda3\a\lib\site-packages\pycqBot\cqHttpApi.py", line 401, in _websocket_start
    asyncio.run(main_logic())
  File "D:\AAA\Anaconda3\a\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\AAA\Anaconda3\a\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\AAA\Anaconda3\a\lib\site-packages\pycqBot\cqHttpApi.py", line 375, in main_logic
    async with websockets.connect(self.__host) as websocket:
  File "D:\AAA\Anaconda3\a\lib\site-packages\websockets\legacy\client.py", line 637, in __aenter__
    return await self
  File "D:\AAA\Anaconda3\a\lib\site-packages\websockets\legacy\client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "D:\AAA\Anaconda3\a\lib\site-packages\websockets\legacy\client.py", line 662, in __await_impl__
    await protocol.handshake(
  File "D:\AAA\Anaconda3\a\lib\site-packages\websockets\legacy\client.py", line 329, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404

### 期望的结果是什么？

正常运行go-cqhttp

### 实际的结果是什么？

pycq不能与go-cqhttp连接

### 简单的复现代码/链接（可选）

```golang
servers:
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器

  - http: # HTTP 通信设置
      address: 127.0.0.1:8000 # HTTP监听地址
      version: 11     # OneBot协议版本, 支持 11/12
      timeout: 5      # 反向 HTTP 超时时间, 单位秒，<5 时将被忽略
      long-polling:   # 长轮询拓展
        enabled: false       # 是否开启
        max-queue-size: 2000 # 消息队列大小，0 表示不限制队列大小，谨慎使用
      middlewares:
        <<: *default # 引用默认中间件
      post:        # 反向HTTP POST地址列表
      #- url: ''                # 地址
      #  secret: ''             # 密钥
      #  max-retries: 3         # 最大重试，0 时禁用
      #  retries-interval: 1500 # 重试时间，单位毫秒，0 时立即
      #- url: http://127.0.0.1:5701/ # 地址
      #  secret: ''                  # 密钥
      #  max-retries: 10             # 最大重试，0 时禁用
      #  retries-interval: 1000      # 重试时间，单位毫秒，0 时立即
  # 正向WS设置
  - ws:
      # 正向WS服务器监听地址
      address: 127.0.0.1:5700
      middlewares:
        <<: *default # 引用默认中间件
```

**Comment by Mrs4s** [comment]
请检查应用配置
