### ISSUE TITLE
I  think i found why get_group_member_list() return empty list

### ISSUE THREAD

**Issue by ChateauXiao** [Mrs4s/go-cqhttp#226]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.23  v0.9.21-fix1
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
if log file have above message ` parse incoming packet error: invalid payload` , then the get_group_member_list() will not get member list properly

**复现方法**
```
[2020-09-01 08:01:15] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2020-09-01 08:01:15] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2020-09-01 08:01:20] [INFO]: 开始尝试登录并同步消息...
[2020-09-01 08:01:21] [INFO]: 登录成功 欢迎使用: cccccc
[2020-09-01 08:01:22] [INFO]: 开始加载好友列表...
[2020-09-01 08:01:22] [INFO]: 共加载 14 个好友.
[2020-09-01 08:01:22] [INFO]: 开始加载群列表...
2020/09/01 08:01:24 parse incoming packet error: invalid payload
2020/09/01 08:01:53 parse incoming packet error: invalid payload
Packet Timed out
Packet Timed out
Packet Timed out
...
Packet Timed out
[2020-09-01 08:02:24] [INFO]: 共加载 144 个群.
[2020-09-01 08:02:24] [INFO]: 信息数据库初始化完成.
[2020-09-01 08:02:24] [WARNING]: post_message_format 配置错误, 将自动使用 string
```

**Comment by Mrs4s** [comment]
what is the physical address of the server?

**Comment by Mrs4s** [comment]
please enable debug and try again.

**Comment by takayama-lily** [comment]
不要说英语。
这个是不是启动的时候群员列表的包超时了所以没加载到。

**Comment by ChateauXiao** [comment]
> what is the physical address of the server?

i run it in a docker container. here is some extra info i can provide for my other account


```
[2020-09-05 08:58:36] [INFO]: 开始加载群列表...
2020/09/05 08:58:38 parse incoming packet error: invalid payload
2020/09/05 08:59:08 parse incoming packet error: invalid payload
panic: interface conversion: interface {} is nil, not client.groupMemberListResponse

goroutine 33 [running]:
github.com/Mrs4s/MiraiGo/client.(*QQClient).GetGroupMembers(0xc0003a8000, 0xc000374770, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200823075559-507fe33e842d/client/client.go:640 +0x2f5
github.com/Mrs4s/MiraiGo/client.(*QQClient).GetGroupList.func1(0xc0003a8000, 0xc000374770, 0xc00076ed84)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200823075559-507fe33e842d/client/client.go:621 +0x61
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).GetGroupList
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200823075559-507fe33e842d/client/client.go:619 +0xfd
```
