### ISSUE TITLE
Hoishino自动报时插件报错WebSocket API call timeout

### ISSUE THREAD

**Issue by shadow7755** [Mrs4s/go-cqhttp#232]
**环境信息**
go-cqhttp版本: v0.9.23
运行环境: windows server 2016
连接方式: 反向WS

**bug内容**
Hoishino自动报时插件报错WebSocket API call timeout，机器人群内不能发送整点报时消息

**复现方法**
整点触发报时插件，报错日志如下
[2020-09-02 22:00:26,822 pcr-comic] INFO: Scheduled job update_seeker completed.
[2020-09-02 22:01:00,144 hourcall] ERROR: <class 'aiocqhttp.exceptions.NetworkError'> occured when doing scheduled job hour_call.
[2020-09-02 22:01:00,176 hourcall] ERROR: WebSocket API call timeout
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 118, in fetch
    return await asyncio.wait_for(future, timeout_sec)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\hoshinobot\hoshino\service.py", line 325, in wrapper
    ret = await func()
  File "C:\Users\Administrator\Desktop\hoshinobot\hoshino\modules\hourcall\hourcall.py", line 24, in hour_call
    await sv.broadcast(msg, 'hourcall', 0)
  File "C:\Users\Administrator\Desktop\hoshinobot\hoshino\service.py", line 339, in broadcast
    glist = await self.get_enable_groups()
  File "C:\Users\Administrator\Desktop\hoshinobot\hoshino\service.py", line 173, in get_enable_groups
    for g in await self.bot.get_group_list(self_id=sid))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 223, in call_action
    return await self._api.call_action(action=action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 186, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 162, in call_action
    await ResultStore.fetch(seq, self._timeout_sec))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 122, in fetch
    raise NetworkError('WebSocket API call timeout')
aiocqhttp.exceptions.NetworkError: WebSocket API call timeout

**Comment by Mrs4s** [comment]
请问go-cqhttp端有没有报错日志

**Comment by shadow7755** [comment]
go-cqhttp端报错只有这2句
[2020-09-02 21:03:43] [WARNING]: 向WS服务器 127.0.0.1:8080 推送Event时出现错误: write tcp 127.0.0.1:50717->127.0.0.1:8080: i/o timeout 
[2020-09-02 21:03:43] [WARNING]: 监听反向WS API时出现错误: read tcp 127.0.0.1:50717->127.0.0.1:8080: use of closed network connection 

8080是hoshino端口

**Comment by rbameto** [comment]
我也有出现了同样的问题，于是我写了个几乎一样的手动触发发现可以正常发出来。
import pytz
from datetime import datetime
import hoshino
from hoshino import Service

sv = Service('hourcall', enable_on_default=False, help_='时报')
tz = pytz.timezone('Asia/Shanghai')

def get_hour_call():
    """挑出一组时报，每日更换，一日之内保持相同"""
    cfg = hoshino.config.hourcall
    now = datetime.now(tz)
    hc_groups = cfg.HOUR_CALLS_ON
    g = hc_groups[ now.day % len(hc_groups) ]
    return cfg.HOUR_CALLS[g]

@sv.on_fullmatch(('报个时'), only_to_me=True)
async def hour_calll(bot,event):
	now = datetime.now(tz)
	hrs = now.hour
	hrs1 = 2 * hrs
	hrs2 = hrs + 1
	msg1 = get_hour_call()[hrs1]
	msg2 = get_hour_call()[hrs2]
	await sv.broadcast(msg1, 'hourcall', 0)
	await sv.broadcast(msg2, 'hourcall', 0)
#-----以上是自己加的，下面是原本的改了点------
@sv.scheduled_job('cron', hour='*')
async def hour_call():
	now = datetime.now(tz)
	if 2 <= now.hour <= 4:
		return  # 宵禁 免打扰
	msg = get_hour_call()[now.hour]
	await sv.broadcast(msg, 'hourcall', 0)

手动是正常的，自动仍然发不出来，然后我发现一个问题。
每次一到整点ws反向连接就会断开，
[2020-09-03 22:00:00,004 hourcall] INFO: Scheduled job hour_call start.
[2020-09-03 22:00:03,551] 127.0.0.1:16588 GET /ws/ 1.1 101 - 1431

然后就会导致出现以下问题：
[2020-09-03 22:01:00,023 hourcall] ERROR: <class 'aiocqhttp.exceptions.NetworkError'> occured when doing scheduled job hour_call.
[2020-09-03 22:01:00,024 hourcall] ERROR: WebSocket API call timeout
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 118, in fetch
    return await asyncio.wait_for(future, timeout_sec)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/HoshinoBot/hoshino/service.py", line 325, in wrapper
    ret = await func()
  File "/root/HoshinoBot/hoshino/modules/hourcall/hourcall.py", line 38, in hour_call
    await sv.broadcast(msg1, 'hourcall', 0)
  File "/root/HoshinoBot/hoshino/service.py", line 339, in broadcast
    glist = await self.get_enable_groups()
  File "/root/HoshinoBot/hoshino/service.py", line 173, in get_enable_groups
    for g in await self.bot.get_group_list(self_id=sid))
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 223, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 186, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 162, in call_action
    await ResultStore.fetch(seq, self._timeout_sec))
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 122, in fetch
    raise NetworkError('WebSocket API call timeout')
aiocqhttp.exceptions.NetworkError: WebSocket API call timeout

go-cqhttp显示也是
[2020-09-03 22:00:02] [WARNING]: 向WS服务器 127.0.0.1:7777 推送Event时出现错误: write tcp 127.0.0.1:16438->127.0.0.1:7777: i/o timeout
[2020-09-03 22:00:02] [WARNING]: 监听反向WS API时出现错误: read tcp 127.0.0.1:16438->127.0.0.1:7777: use of closed network connection
[2020-09-03 22:00:03] [INFO]: 开始尝试连接到反向Websocket Universal服务器: ws://127.0.0.1:7777/ws/

是否是因为这个程序机制导致断开，还是go-cqhttp本身会整点断开呢

**Comment by rbameto** [comment]
更新开了DEBUG之后的信息，这一次bot成功发出来了，但是反向ws还是断了，所以是否整点断线是go-cqhttp和hoshinobot的问题？
信息如下：
`[2020-09-03 23:00:00] [DEBUG]: WS接收到API调用: get_group_list 参数: {"self_id": "594010174"} 
[2020-09-03 23:00:00] [DEBUG]: WS接收到API调用: send_group_msg 参数: {"self_id": "594010174", "group_id": 705482281, "message": "\u4e8c\u4e09\u3007\u3007\u3002\u5dee\u4e0d\u591a\u4eca\u5929\u4e5f\u8981\u7ed3\u675f\u4e86\u5462\u3002\u8fd9\u4e00\u5929\u771f\u662f\u8f9b\u82e6\u4f60\u4e86\uff0c\u660e\u5929\u89c1\u3002"} 
[2020-09-03 23:00:00] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbSendMsg seq: 13944 
[2020-09-03 23:00:00] [DEBUG]: Protocol -> rev pkt: OnlinePush.PbPushGroupMsg seq: 32147 
[2020-09-03 23:00:00] [DEBUG]: WS接收到API调用: get_group_list 参数: {"self_id": "594010174"} 
[2020-09-03 23:00:00] [DEBUG]: WS接收到API调用: send_group_msg 参数: {"self_id": "594010174", "group_id": 705482281, "message": "[CQ:record,file=hourcall/181a-2300.amr]"} 
[2020-09-03 23:00:00] [DEBUG]: Protocol -> rev pkt: PttStore.GroupPttUp seq: 13945 
[2020-09-03 23:00:01] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbSendMsg seq: 13946 
[2020-09-03 23:00:01] [DEBUG]: Protocol -> rev pkt: OnlinePush.PbPushGroupMsg seq: 23352 
[2020-09-03 23:00:03] [DEBUG]: Protocol -> rev pkt: Heartbeat.Alive seq: 13947 
[2020-09-03 23:00:06] [DEBUG]: 向WS服务器 127.0.0.1:9222 推送Event: {"interval":20000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":594010174,"status":null,"time":1599145206} 
[2020-09-03 23:00:06] [DEBUG]: 向WS服务器 127.0.0.1:7777 推送Event: {"interval":20000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":594010174,"status":null,"time":1599145206} 
[2020-09-03 23:00:06] [WARNING]: 向WS服务器 127.0.0.1:7777 推送Event时出现错误: write tcp 127.0.0.1:16734->127.0.0.1:7777: i/o timeout 
[2020-09-03 23:00:06] [WARNING]: 监听反向WS API时出现错误: read tcp 127.0.0.1:16734->127.0.0.1:7777: use of closed network connection 
[2020-09-03 23:00:07] [INFO]: 开始尝试连接到反向Websocket Universal服务器: ws://127.0.0.1:7777/ws/ 
`

**Comment by Mrs4s** [comment]
我怀疑这个是应用层的问题.  断开的原因是写入超时. 可以尝试调高心跳的频率？

**Comment by NepPure** [comment]
v0.9.39版本也有同样的问题，不是每个小时必定出现的，大佬们有什么思路吗

```
[2021-01-30 18:01:00,085 提醒买药] ERROR: WebSocket API call timeout
Traceback (most recent call last):
  File "D:\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 118, in fetch
    return await asyncio.wait_for(future, timeout_sec)
  File "D:\Programs\Python\Python38\lib\asyncio\tasks.py", line 498, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\server\XCW\hoshino\hoshino\service.py", line 325, in wrapper
    ret = await func()
  File "D:\server\XCW\hoshino\hoshino\modules\hourcallyao\hourcall.py", line 23, in hour_call
    await sv.broadcast(str(R.img(f"yao{random.randint(1, 5)}.png").cqcode), 'hourcall', 0)
  File "D:\server\XCW\hoshino\hoshino\service.py", line 339, in broadcast
    glist = await self.get_enable_groups()
  File "D:\server\XCW\hoshino\hoshino\service.py", line 173, in get_enable_groups
    for g in await self.bot.get_group_list(self_id=sid))
  File "D:\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 219, in call_action
    return await self._api.call_action(action=action, **params)
  File "D:\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 186, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "D:\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 162, in call_action
    await ResultStore.fetch(seq, self._timeout_sec))
  File "D:\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 122, in fetch
    raise NetworkError('WebSocket API call timeout')
aiocqhttp.exceptions.NetworkError: WebSocket API call timeout
```

**Comment by Harpes** [comment]
经过测试发现心跳间隔过长（60s）也会概率触发此问题，将心跳间隔（heartbeat_interval）缩短至数秒即可。

**Comment by sam01101** [comment]
草
