### ISSUE TITLE
[Bug]: QQ频道发送消息报错（概率性）

### ISSUE THREAD

**Issue by MRDHR** [Mrs4s/go-cqhttp#2329]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.1.0

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

1 | Android Phone

### 重现步骤

bot.send_guild_channel_msg(guild_id=guildChannelId[0], channel_id=guildChannelId[1],message="测试消息")

### 期望的结果是什么？

发送成功，不会出现错误

### 实际的结果是什么？

发送QQ频道消息报错

### 日志记录（可选）

```golang
处置WS命令时发生无法恢复的异常：runtime error: invalid memory address or nil pointer dereference
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] goroutine 339 [running]:
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] runtime/debug.Stack()
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] runtime/debug/stack.go:24 +0x65
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest.func1()
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] github.com/Mrs4s/go-cqhttp/server/websocket.go:471 +0x46
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] panic({0xa40cc0, 0xf82ea0})
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] runtime/panic.go:884 +0x213
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] github.com/Mrs4s/MiraiGo/client.(*GuildService).SendGuildChannelMessage(0xc0005abb30, 0x85d9393746a5d6, 0xbd801e, 0xc0002959a0)
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] github.com/Mrs4s/MiraiGo@v0.0.0-20230627090859-19e3d172596e/client/guild_msg.go:69 +0x47d
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).SendGuildChannelMessage(0xc00011a000, 0x2?, 0x3bb?, 0xc0002959a0)
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] github.com/Mrs4s/go-cqhttp/coolq/bot.go:437 +0x371
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendGuildChannelMessage(0xc00011a000, 0x85d9393746a5d6, 0xbd801e, {0x5, {0xc0006e2076, 0x3bb}, {0x0, 0x0}, 0x0, 0x76, ...}, ...)
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] github.com/Mrs4s/go-cqhttp/coolq/api.go:826 +0x5ce
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).call(0xc000305da0, {0xc0006e200c, 0x16?}, 0xf84ce0, {0xbece00, 0xc000076230})
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] github.com/Mrs4s/go-cqhttp/modules/api/api.go:264 +0xadcd
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).Call(0xc000305da0, {0xc0006e200c, 0x16}, 0xc0006e2000?, {0xbece00, 0xc000076230})07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] github.com/Mrs4s/go-cqhttp/modules/api/caller.go:35 +0xc5
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] github.com/Mrs4s/go-cqhttp/server.(*wsConn).handleRequest(0xc0005eaa98, 0xa5f4c0?, {0xc0006e2000?, 0xc000499f38?, 0xc000499fd0?})
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] github.com/Mrs4s/go-cqhttp/server/websocket.go:480 +0x41c
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI.func2(0xc000499fb8?)
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] github.com/Mrs4s/go-cqhttp/server/websocket.go:325 +0x95
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] created by github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenAPI
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] github.com/Mrs4s/go-cqhttp/server/websocket.go:323 +0x1b2
07-27 16:48:49 [STDOUT] nonebot_plugin_gocqhttp | [QQ号] 
07-27 16:48:49 [WARNING] nonebot_plugin_gocqhttp | [QQ号] 监听反向WS Universal时出现错误: read tcp 127.0.0.1:33716->127.0.0.1:17130: use of closed network connection
```

**Comment by hnuuhc** [comment]
我也是,可能tx修改了什么?

**Comment by hnuuhc** [comment]
实测是频道消息被风控,出现这个异常就代表该消息别人看不到

**Comment by MRDHR** [comment]
> 实测是频道消息被风控,出现这个异常就代表该消息别人看不到

那有什么办法可以捕获这个异常或者解决这个风控么？

当出现这个异常的时候，bot会重连。我是做了一个定时任务的，当bot上线之后会自动执行。现在是反复重连 定时任务就又重新开始了 反复循环。

**Comment by MRDHR** [comment]
我尝试过try，只能输出日志。无法阻止bot重连的过程。

我也使用过定时任务那个插件，不太好用。我的任务（可能超过一分钟）需要执行完后再延迟1分钟重复执行，无法简单的使用定时任务去执行。

**Comment by Mubanjun** [comment]
先尝试换个签名服务器？或者删掉device.json生成个新的？

如果正在使用WSL(适用于Linux的Windows子系统)，请更新WSL至2.0，并在控制面板放通防火墙，并修改Host文件

如果正在使用原生(直接装在机器上的)Ubuntu，请尝试自行修改Host文件，并监视系统异常

如果正在使用腾讯云的服务器，请放通相应端口，或者干脆只留DDos等必要防护，并且检查私有网络配置

看上去是内存异常呢，可以尝试扩大一些Swap分区大小(至少为本机物理内存的两倍)，或者尝试监视系统，观察是否有异常进程过度消耗内存，不排除中毒的可能性

最后补充，关于频道模块，开发者初心就是抛弃不维护，如果正常聊天没有同样的毛病就先正常用吧

**Comment by hnuuhc** [comment]
> 

就是单纯的被风控了,经常出现这个异常,应该立刻停止发消息,否则会越来越频繁,你可以尝试登陆电脑在频道发消息,自己是看着正常发送,别人是看不到的,这是账号级别的风控,

**Comment by hnuuhc** [comment]
> 我尝试过try，只能输出日志。无法阻止bot重连的过程。
> 
> 我也使用过定时任务那个插件，不太好用。我的任务（可能超过一分钟）需要执行完后再延迟1分钟重复执行，无法简单的使用定时任务去执行。

就是单纯的被风控了,经常出现这个异常,应该立刻停止发消息,否则会越来越频繁,你可以尝试登陆电脑在频道发消息,自己是看着正常发送,别人是看不到的,这是账号级别的风控,

**Comment by MRDHR** [comment]
> > 我尝试过try，只能输出日志。无法阻止bot重连的过程。
> > 我也使用过定时任务那个插件，不太好用。我的任务（可能超过一分钟）需要执行完后再延迟1分钟重复执行，无法简单的使用定时任务去执行。
> 
> 就是单纯的被风控了,经常出现这个异常,应该立刻停止发消息,否则会越来越频繁,你可以尝试登陆电脑在频道发消息,自己是看着正常发送,别人是看不到的,这是账号级别的风控,

尝试登录了，QQ频道居然成了只读模式。主QQ号正常

**Comment by MRDHR** [comment]
谢谢大佬们的提醒
