### ISSUE TITLE
[Bug]: 最新dev版自编译后登录出现问题

### ISSUE THREAD

**Issue by xixi-furry** [Mrs4s/go-cqhttp#2339]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

dev

### 运行环境

Linux

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

WebSocket (反向)

### 使用协议

1 | Android Phone

### 重现步骤

直接登录即可

### 期望的结果是什么？

能够正常登录

### 实际的结果是什么？

暂无

### 日志记录（可选）

```golang
[2023-08-01 11:06:54] [INFO]: 当前版本:(devel) 
[2023-08-01 11:06:54] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2023-08-01 11:06:55] [INFO]: 使用服务器 http://127.0.0.1:8119 进行数据包签名 
[2023-08-01 11:07:00] [INFO]: 连接至签名服务器: http://127.0.0.1:8119 
[2023-08-01 11:07:08] [INFO]: 注册QQ实例 114511 成功: The QQ has already loaded an instance, so this time it is deleting the existing instance and creating a new one. 
[2023-08-01 11:07:08] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2023-08-01 11:07:08] [INFO]: 每 40 分钟将刷新一次签名 token 
[2023-08-01 11:07:13] [INFO]: 开始尝试登录并同步消息... 
[2023-08-01 11:07:13] [INFO]: 使用协议: Android Pad 8.9.63.11390 
[2023-08-01 11:07:13] [INFO]: 正在检查协议更新... 
[2023-08-01 11:07:14] [INFO]: Protocol -> connect to server: 43.135.106.161:8080 
[2023-08-01 11:07:17] [WARNING]: 登录需要滑条验证码, 请验证后重试. 
[2023-08-01 11:07:17] [WARNING]: 请选择提交滑块ticket方式: 
[2023-08-01 11:07:17] [WARNING]: 1. 自动提交 
[2023-08-01 11:07:17] [WARNING]: 2. 手动抓取提交 
[2023-08-01 11:07:17] [WARNING]: 请输入(1 - 2)： 
[2023-08-01 11:07:17] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10005 
2[2023-08-01 11:07:32] [WARNING]: callback error: Packet timed out 
panic: runtime error: slice bounds out of range [-10:]

goroutine 65 [running]:
github.com/Mrs4s/go-cqhttp/cmd/gocq.submit({0x40000b2340, 0x9}, {0x40001b9328, 0x33}, 0x40002f7dd8?, {0x0, 0x0, 0x0?}, {0x671dc6, 0x4})
        /opt/go-cqhttp/make/go-cqhttp/cmd/gocq/login.go:310 +0x3c4
github.com/Mrs4s/go-cqhttp/cmd/gocq.callback({0x40000b2340, 0x9}, {0x40004a2c80?, 0x3, 0x40004172c0?}, {0x671dc6, 0x4})
        /opt/go-cqhttp/make/go-cqhttp/cmd/gocq/login.go:331 +0x6c
created by github.com/Mrs4s/go-cqhttp/cmd/gocq._sign
        /opt/go-cqhttp/make/go-cqhttp/cmd/gocq/login.go:354 +0x7d4
```

**Comment by lgc2333** [comment]
遇到问题 +1，换用 [这个Action (CI #2121)](https://github.com/Mrs4s/go-cqhttp/actions/runs/5504923059) 下的 Artifact 未出现问题

**Comment by 1umine** [comment]
https://github.com/Mrs4s/go-cqhttp/blob/dev/cmd/gocq/login.go#L335C40-L335C40 后面加句 return

https://github.com/Mrs4s/go-cqhttp/blob/dev/cmd/gocq/login.go#L315C22-L315C22 那里改成（或者删了这里的log也行）
```go
if len(buffStr) > 10 {
    log.Infof("submit %v: uin=%v, cmd=%v, callbackID=%v, buffer-end=%v", t, uin, cmd, callbackID,
	buffStr[len(buffStr)-10:])
} else {
    log.Infof("submit %v: uin=%v, cmd=%v, callbackID=%v, buffer=%v", t, uin, cmd, callbackID, buffStr)
}
```
再 action 编译应该没事了

**Comment by fumiama** [comment]
fixed.

**Comment by Eric-Joker** [comment]
> fixed.
![ca72a3fc1cb3598925d67d828f669b3](https://github.com/Mrs4s/go-cqhttp/assets/60310368/b879c4bf-4562-44c0-bdb2-42630cbbec08)
CI#2200和#2199都试了，仍然报错

**Comment by 1umine** [comment]
> 还存在
> 

还存在是指超时还是什么？packet timeout暂时还没解决，不过应该不影响使用，超时后返回空的结果导致panic的问题已经解决了
