### ISSUE TITLE
[Bug]: panic: runtime error: slice bounds out of range [:4] with capacity 

### ISSUE THREAD

**Issue by mmmjie** [Mrs4s/go-cqhttp#2402]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

2023-8-23日的 d85d697 dev

### 运行环境

Linux

### 运行架构

ARM [64] (别名：AArch64 / ARMv8）

### 连接方式

WebSocket (反向)

### 使用协议

6 | aPad

### 重现步骤

启动gocq后

### 期望的结果是什么？

正确运行

### 实际的结果是什么？

[2023-08-23 18:27:10] [INFO]: 登录成功 欢迎使用: BOT>真寻喵~ 
[2023-08-23 18:27:10] [INFO]: 开始加载好友列表... 
[2023-08-23 18:27:10] [INFO]: 共加载 4 个好友. 
[2023-08-23 18:27:10] [INFO]: 开始加载群列表... 
[2023-08-23 18:27:11] [INFO]: 共加载 3 个群. 
[2023-08-23 18:27:11] [INFO]: 资源初始化完成, 开始处理信息. 
[2023-08-23 18:27:11] [INFO]: アトリは、高性能ですから! 
[2023-08-23 18:27:11] [INFO]: 正在检查更新. 
[2023-08-23 18:27:11] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:23333/onebot/v11/ws/ 
[2023-08-23 18:27:11] [INFO]: 已连接到反向WebSocket Universal服务器 ws://127.0.0.1:23333/onebot/v11/ws/ 
[2023-08-23 18:27:11] [WARNING]: 检查更新失败！ 
[2023-08-23 18:27:11] [INFO]: 检查更新完成. 当前已运行最新版本. 
[2023-08-23 18:27:11] [INFO]: 开始诊断网络情况 
[2023-08-23 18:27:12] [INFO]: submit sign: uin=1921659661, cmd=trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish, callbackID=2, buffer=[10 148 1 45 206 214 106 144 55 107 107 127 61 49 113 233 50 160 98 66 159 125 192 211 112 212 147 55 102 230 45 180 48 136 196 52 123 237 175 182 53 254 32 101 95 41 134 241 153 50 23 190 188 49 112 228 140 180 20 213 238 241 43 175]... 
panic: runtime error: slice bounds out of range [:4] with capacity 2

goroutine 264 [running]:
github.com/Mrs4s/go-cqhttp/cmd/gocq.signSubmit({0x40000224a0, 0xa}, {0x4000378028, 0x30}, 0xa8?, {0x40000ab0b0, 0x2, 0x2}, {0x6707ae, 0x4})
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:322 +0x47c
github.com/Mrs4s/go-cqhttp/cmd/gocq.signCallback({0x40000224a0, 0xa}, {0x4000148fa0?, 0x1, 0x400032ac60?}, {0x6707ae, 0x4})
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:343 +0x6c
created by github.com/Mrs4s/go-cqhttp/cmd/gocq.signRequset
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:371 +0x8f8

**Comment by mmmjie** [comment]
重复了

**Comment by wangdakanga** [comment]
#2399
