### ISSUE TITLE
panic: interface conversion: interface {} is nil, not client.groupMemberListResponse

### ISSUE THREAD

**Issue by ChateauXiao** [Mrs4s/go-cqhttp#242]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.23 and v0.9.21-fix1
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
```
[2020-09-05 08:58:36] [INFO]: 开始加载群列表...
2020/09/05 08:58:38 parse incoming packet error: invalid payload
2020/09/05 08:59:08 parse incoming packet error: invalid payload
panic: interface conversion: interface {} is nil, not client.groupMemberListResponse

goroutine 33 [running]:
github.com/Mrs4s/MiraiGo/client.(*QQClient).GetGroupMembers(0xc0003a8000, 0xc000374770, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200823075559-507fe33e842d/client/client.go:640 +0x2f5
github.com/Mrs4s/MiraiGo/client.(*QQClient).GetGroupList.func1(0xc0003a8000, 0xc000374770, 0xc00076ed84)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200823075559-507fe33e842d/client/client.go:621 +0x61
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).GetGroupList
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200823075559-507fe33e842d/client/client.go:619 +0xfd
```

**复现方法**

**Comment by Mrs4s** [comment]
Where the server is located?
