### ISSUE TITLE
[Bug]: 在登入几秒后报错

### ISSUE THREAD

**Issue by sbzlzh** [Mrs4s/go-cqhttp#2460]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

642c746

### 运行环境

Ubuntu

### 运行架构

x86

### 连接方式

WebSocket (反向)

### 使用协议

1 | Android Phone

### 重现步骤

[2023-10-01 20:50:00] [INFO]: 当前版本:642c746 
[2023-10-01 20:50:00] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2023-10-01 20:50:00] [INFO]: 使用服务器 http://bot.lengyudeyue.com:13579 进行数据包签名 
[2023-10-01 20:50:05] [INFO]: 连接至签名服务器: http://bot.lengyudeyue.com:13579 
[2023-10-01 20:50:09] [INFO]: 注册QQ实例 3141403821 成功: Instance loaded successfully. 
[2023-10-01 20:50:09] [INFO]: 开始尝试登录并同步消息... 
[2023-10-01 20:50:09] [INFO]: 使用协议: Android Phone 8.9.63.11390 
[2023-10-01 20:50:09] [INFO]: 每 40 分钟将刷新一次签名 token 
[2023-10-01 20:50:09] [INFO]: 从文件 data/versions/1.json 读取协议版本 Android Phone 8.9.73.11945. 
[2023-10-01 20:50:09] [INFO]: Protocol -> connect to server: 117.62.242.155:8080 
[2023-10-01 20:50:10] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10005 
[2023-10-01 20:50:11] [WARNING]: Protocol -> device lock is disable. http api may fail. 
[2023-10-01 20:50:14] [INFO]: 登录成功 欢迎使用: 真寻 
[2023-10-01 20:50:14] [INFO]: 开始加载好友列表... 
[2023-10-01 20:50:14] [INFO]: 共加载 49 个好友. 
[2023-10-01 20:50:14] [INFO]: 开始加载群列表... 
[2023-10-01 20:50:17] [INFO]: 共加载 23 个群. 
[2023-10-01 20:50:17] [INFO]: 资源初始化完成, 开始处理信息. 
[2023-10-01 20:50:17] [INFO]: アトリは、高性能ですから! 
[2023-10-01 20:50:17] [INFO]: 正在检查更新. 
[2023-10-01 20:50:17] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:14514/onebot/v11/ws/ 
[2023-10-01 20:50:17] [INFO]: 已连接到反向WebSocket Universal服务器 ws://127.0.0.1:14514/onebot/v11/ws/ 
[2023-10-01 20:50:17] [WARNING]: 检查更新失败！ 
[2023-10-01 20:50:17] [INFO]: 检查更新完成. 当前已运行最新版本. 
[2023-10-01 20:50:17] [INFO]: 开始诊断网络情况 
[2023-10-01 20:50:20] [INFO]: 网络诊断完成. 未发现问题 
[2023-10-01 20:50:25] [WARNING]: callback error: Packet timed out 
panic: runtime error: slice bounds out of range [-10:]

goroutine 131 [running]:
github.com/Mrs4s/go-cqhttp/cmd/gocq.signSubmit({0xc00051e940, 0xa}, {0xc0001c4a28, 0x33}, 0x1?, {0x0, 0x0, 0x0?}, {0xafc1d3, 0x4})
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:316 +0x5c5
github.com/Mrs4s/go-cqhttp/cmd/gocq.signCallback({0xc00051e940, 0xa}, {0xc0002e2640?, 0x3, 0xc00030afd0?}, {0xafc1d3, 0x4})
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:337 +0xb1
created by github.com/Mrs4s/go-cqhttp/cmd/gocq.signRequset
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:365 +0xcb0

### 期望的结果是什么？

解决这个bug

### 实际的结果是什么？

[2023-10-01 20:50:25] [WARNING]: callback error: Packet timed out 
panic: runtime error: slice bounds out of range [-10:]

goroutine 131 [running]:
github.com/Mrs4s/go-cqhttp/cmd/gocq.signSubmit({0xc00051e940, 0xa}, {0xc0001c4a28, 0x33}, 0x1?, {0x0, 0x0, 0x0?}, {0xafc1d3, 0x4})
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:316 +0x5c5
github.com/Mrs4s/go-cqhttp/cmd/gocq.signCallback({0xc00051e940, 0xa}, {0xc0002e2640?, 0x3, 0xc00030afd0?}, {0xafc1d3, 0x4})
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:337 +0xb1
created by github.com/Mrs4s/go-cqhttp/cmd/gocq.signRequset
        github.com/Mrs4s/go-cqhttp/cmd/gocq/login.go:365 +0xcb0

**Comment by sbzlzh** [comment]
我在https://github.com/sbzlzh/go-cqhttp/blob/master/cmd/gocq/login.go中的316与327中添加了个东西。使用后并没有出现这个情况。如果这样是对的，那么为了不多这个327的东西，我可以改成endIndex := len(buffStr)
if 10 < endIndex {
    endIndex = 10
}
buffStr[len(buffStr)-endIndex:]

**Comment by 1umine** [comment]
用dev分支最新的，这个bug很早就修了（）

**Comment by sbzlzh** [comment]
好的

**Comment by sbzlzh** [comment]
用了dev最新的，解决了，谢谢你
