### ISSUE TITLE
[Bug]: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 1411484730** [Mrs4s/go-cqhttp#2485]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

1.2.0

### 运行环境

Ubuntu

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

6 | aPad

### 重现步骤

gocq版本1.2.0，qsign版本1.1.9，apad协议使用8983
bug不稳定复现
可能的触发方式为连续发送多条消息或运行一段时间后触发

### 期望的结果是什么？

无

### 实际的结果是什么？

gocq程序崩溃，重启后无法获取签名（qsign正常运行）

### 日志记录（可选）

```golang
[2023-11-04 16:44:32] [ERROR]: Protocol -> unexpected disconnect: EOF 
[2023-11-04 16:44:36] [WARNING]: 获取签名为空，实例可能丢失，正在尝试重新注册 
[2023-11-04 16:44:39] [WARNING]: destroy 实例出现错误, server: http://127.0.0.1:8088: Get "http://127.0.0.1:8088/destroy?uin=1833285115&key=114514": EOF 
[2023-11-04 16:44:39] [WARNING]: 签名服务器 http://127.0.0.1:8088 可能不可用，请求出现错误：Get "http://127.0.0.1:8088": dial tcp 127.0.0.1:8088: connect: connection refused 
[2023-11-04 16:44:39] [WARNING]: nil sign-server 
[2023-11-04 16:44:39] [ERROR]: Protocol -> panic on decoder OnlinePush.PbPushGroupMsg : runtime error: invalid memory address or nil pointer dereference
goroutine 127 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1.1()
	github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/network.go:400 +0x65
panic({0xa49660, 0xf91ea0})
	runtime/panic.go:884 +0x213
github.com/Mrs4s/go-cqhttp/cmd/gocq.requestSignServer({0xafe258, 0x3}, {0xc0001d01e0, 0x91}, 0x0, {0x0, 0x0})
	github.com/Mrs4s/go-cqhttp/cmd/gocq/qsign.go:134 +0x6f
github.com/Mrs4s/go-cqhttp/cmd/gocq.signRegister(0xc0005c1710?, {0xc0003a6450?, 0x1?, 0xa1bd80?}, {0xc0003a6480, 0x10, 0xb08077?}, {0xc00049c031, 0x24}, {0xc000026ac0, ...})
	github.com/Mrs4s/go-cqhttp/cmd/gocq/qsign.go:260 +0x2e5
github.com/Mrs4s/go-cqhttp/cmd/gocq.sign(0x0?, {0xc0005954f0, 0xa}, {0xb08077, 0xf}, {0xb12744, 0x1b}, {0xc0002c5810, 0x6f, 0x6f})
	github.com/Mrs4s/go-cqhttp/cmd/gocq/qsign.go:331 +0xeb4
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).PackSecSign(0xc00058e108, 0xc0005c1ae8)
	github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/network/transport.go:159 +0xbf
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).packBody(0xc00058e108, 0xc0005c1ae8, 0xc000598300)
	github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/network/transport.go:141 +0x390
github.com/Mrs4s/MiraiGo/client/internal/network.(*Transport).PackPacket(0xc00058e108, 0xc0005c1ae8)
	github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/network/transport.go:217 +0x28f
github.com/Mrs4s/MiraiGo/client.(*QQClient).uniPacket(0xc000610000, {0xb08077, 0xf}, {0xc0002c5810, 0x6f, 0x6f})
	github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/packet.go:30 +0x12d
github.com/Mrs4s/MiraiGo/client.(*QQClient).buildGroupInfoRequestPacket(0xc000610000, 0x3914abe5)
	github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/group_info.go:118 +0x3ce
github.com/Mrs4s/MiraiGo/client.(*QQClient).GetGroupInfo(0x3914abe5?, 0xb07ad4?)
	github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/group_info.go:72 +0x25
github.com/Mrs4s/MiraiGo/client.(*QQClient).parseGroupMessage(0xc000610000, 0xc000192360)
	github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/group_msg.go:343 +0x146
github.com/Mrs4s/MiraiGo/client.decodeGroupMessagePacket(0xc000610000, 0xc0001f2940)
	github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/group_msg.go:255 +0x2d6
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func1(0xc0001f2940)
	github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/network.go:412 +0x182
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
	github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/network.go:397 +0x4cd
 
[2023-11-04 16:44:39] [ERROR]: 出现错误 packet decode error: OnlinePush.PbPushGroupMsg - runtime error: invalid memory address or nil pointer dereference. 详细信息已转储至文件 dumps/1699087479.dump 请连同日志提交给开发者处理 
[2023-11-04 16:44:39] [WARNING]: Protocol -> device lock is disabled. HTTP API may fail. 
[2023-11-04 16:44:44] [WARNING]: 检查更新失败: Get "https://api.github.com/repos/Mrs4s/go-cqhttp/releases/latest": EOF 
[2023-11-04 16:46:39] [WARNING]: Protocol -> device lock is disabled. HTTP API may fail. 
[2023-11-04 16:46:44] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:46:44] [WARNING]: 检查更新失败！ 
[2023-11-04 16:46:47] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:46:50] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:46:53] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:46:56] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:46:59] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:02] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:05] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:08] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:11] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:14] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:17] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:20] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:23] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:26] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:29] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:32] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:35] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:38] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:41] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:44] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:47] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:50] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:53] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:56] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:47:59] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:48:02] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:48:05] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:48:08] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:48:11] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:48:14] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:48:17] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:48:20] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:48:23] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused 
[2023-11-04 16:48:26] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws/ 时出现错误: dial tcp 127.0.0.1:8080: connect: connection refused
```

**Comment by 1411484730** [comment]
[Uploading 1699087479.zip…]()

**Comment by 1411484730** [comment]
[1699087479.zip](https://github.com/Mrs4s/go-cqhttp/files/13256267/1699087479.zip)

**Comment by 1umine** [comment]
只配置一个signserver吧，多个还是有点问题

**Comment by 1411484730** [comment]
似乎是8983及之后8985协议的问题导致频繁刷新token导致的qsign崩溃
