### ISSUE TITLE
[Bug]: Dev7563573版本中无法发送语音

### ISSUE THREAD

**Issue by xiaosuyyds** [Mrs4s/go-cqhttp#2515]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [X] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

dev7563573

### 运行环境

Windows (64)

### 运行架构

None

### 连接方式

HTTP

### 使用协议

0 | Default

### 重现步骤

再次发送语音消息

### 期望的结果是什么？

成功发送语音消息
![image](https://github.com/Mrs4s/go-cqhttp/assets/109886162/f4aee7ef-ecd5-4970-b8d8-d9f9e147bd78)

### 实际的结果是什么？

无法发送语音，有时直接报错，有时上传失败
![image](https://github.com/Mrs4s/go-cqhttp/assets/109886162/7496c2c0-e40b-46ee-b346-03f21b56dece)

### 日志记录（可选）

```golang
[2024-01-26 07:25:04] [INFO]: 当前版本:7563573
[2024-01-26 07:25:04] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2024-01-26 07:25:05] [INFO]: 使用签名服务器：http://localhost:13579
[2024-01-26 07:25:05] [WARNING]: 自动注册实例已关闭，请配置 sign-server 端自动注册实例以保持正常签名
[2024-01-26 07:25:05] [WARNING]: 定时刷新 token 已关闭
[2024-01-26 07:25:05] [INFO]: 自动刷新 token 已关闭，token 过期后获取签名时将不会立即尝试刷新获取新 token
[2024-01-26 07:25:05] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2024-01-26 07:25:10] [INFO]: 开始尝试登录并同步消息...
[2024-01-26 07:25:10] [INFO]: 使用协议: Android Pad 8.9.63.11390
[2024-01-26 07:25:10] [INFO]: 从文件 data/versions/6.json 读取协议版本 Android Pad 8.9.83.12605.
[2024-01-26 07:25:10] [INFO]: Protocol -> connect to server: 120.233.17.147:8080
[2024-01-26 07:25:11] [INFO]: token 已更新： -> 6e3058736f306851414b5842
[2024-01-26 07:25:11] [WARNING]: Protocol -> device lock is disabled. HTTP API may fail.
[2024-01-26 07:25:13] [INFO]: 正在检查协议更新...
[2024-01-26 07:25:13] [INFO]: 检测到协议更新: 8.9.83.12605 -> 8.9.63.11390
[2024-01-26 07:25:13] [INFO]: 如果登录时出现版本过低错误, 可尝试使用 -update-protocol 参数启动
[2024-01-26 07:25:13] [INFO]: 登录成功 欢迎使用: 沐云
[2024-01-26 07:25:13] [INFO]: 开始加载好友列表...
[2024-01-26 07:25:14] [INFO]: 共加载 4 个好友.
[2024-01-26 07:25:14] [INFO]: 开始加载群列表...
[2024-01-26 07:25:14] [INFO]: 共加载 8 个群.
[2024-01-26 07:25:14] [INFO]: 资源初始化完成, 开始处理信息.
[2024-01-26 07:25:14] [INFO]: HTTP POST上报器已启动: http://127.0.0.1:5701/
[2024-01-26 07:25:14] [INFO]: アトリは、高性能ですから!
[2024-01-26 07:25:14] [INFO]: CQ HTTP 服务器已启动: [::]:5700
[2024-01-26 07:25:14] [INFO]: HTTP POST上报器已启动: http://127.0.0.1:5701/
[2024-01-26 07:25:14] [INFO]: 正在检查更新.
[2024-01-26 07:25:15] [WARNING]: 检查更新失败！
[2024-01-26 07:25:15] [INFO]: 检查更新完成. 当前已运行最新版本.
[2024-01-26 07:25:15] [INFO]: 开始诊断网络情况
[2024-01-26 07:25:16] [INFO]: 网络诊断完成. 未发现问题
[2024-01-26 07:26:25] [INFO]: 收到群 Bot测试群(******) 内 校溯(******) 的消息: [CQ:at,qq=******] test (817597151)
panic: runtime error: index out of range [0] with length 0

goroutine 249 [running]:
github.com/Mrs4s/MiraiGo/client/internal/highway.(*Session).nextAddr(0xc?)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/highway/highway.go:227 +0xfd
github.com/Mrs4s/MiraiGo/client/internal/highway.(*Session).selectConn(0x0?)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/highway/highway.go:248 +0xe5
github.com/Mrs4s/MiraiGo/client/internal/highway.(*Session).uploadSingle(0xc0000d03f0, {0x1d, {0xf24ce0, 0xc0002434d0}, {0xc0003c8ff0, 0x10, 0x10}, 0x3c24, {0x0, 0x0, ...}, ...})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/highway/bdh.go:39 +0x68
github.com/Mrs4s/MiraiGo/client/internal/highway.(*Session).Upload(0xc0000d03f0, {0x1d, {0xf24ce0, 0xc0002434d0}, {0xc0003c8ff0, 0x10, 0x10}, 0x3c24, {0x0, 0x0, ...}, ...})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/highway/bdh.go:117 +0x425
github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadVoice(0xc000312000, {0xe0?, 0xc00020ffb8?, 0x9ff60b?}, {0xf273d0?, 0xc0002434d0})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/ptt.go:76 +0x358
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).uploadMedia.func2()
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:245 +0xff
github.com/Mrs4s/go-cqhttp/coolq.(*worker).do.func1()
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:142 +0x5a
created by github.com/Mrs4s/go-cqhttp/coolq.(*worker).do
        github.com/Mrs4s/go-cqhttp/coolq/bot.go:140 +0x85
```

### 补充说明（可选）

此bug在1.2.0版本中没有出现……

**Comment by xiaosuyyds** [comment]
今天突然又可以了，啥情况……
