### ISSUE TITLE
发送图片导致崩溃，处置WS命令时发生无法恢复的异常：runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by Amarillys** [Mrs4s/go-cqhttp#273]
**环境信息**
go-cqhttp版本: v0.9.24-fix2
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
无法发送图片

处置WS命令时发生无法恢复的异常：runtime error: makeslice: len out of range
通过http发送则会崩溃

**复现方法**
发送内容：
[CQ:image,file=6f67ce8f26244f9b3a04427acab01548.image]
或者
[CQ:image,file=6f67ce8f26244f9b3a04427acab01548.image,url=http://c2cpicdw.qpic.cn/offpic_new/719862760//719862760-2040665934-6F67CE8F26244F9B3A04427ACAB01548/0?term=2]

http链接：
http://localhost:5700/send_private_msg?user_id=xxx&message=[CQ:image,file=6f67ce8f26244f9b3a04427acab01548.image]
http://localhost:5700/send_private_msg?user_id=xxx&message=[CQ:image,file=6f67ce8f26244f9b3a04427acab01548.image,url=http://c2cpicdw.qpic.cn/offpic_new/719862760//719862760-2040665934-6F67CE8F26244F9B3A04427ACAB01548/0?term=2]

附带报错信息：
```
2020/09/13 11:50:14 http: panic serving [::1]:44146: runtime error: makeslice: len out of range
goroutine 45 [running]:
net/http.(*conn).serve.func1(0xc00011a000)
        /usr/local/go/src/net/http/server.go:1772 +0x140
panic(0xbbf5c0, 0xdbffd0)
        /usr/local/go/src/runtime/panic.go:973 +0x3a4
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200911100852-71bc19cd42eb/binary/reader.go:36
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadString(0xc000442748, 0xc000600000, 0x10)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200911100852-71bc19cd42eb/binary/reader.go:65 +0x5f
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).makeImageElem(0xc00000c1e0, 0xc0002ab064, 0x5, 0xc0004433d8, 0xc000442e00, 0x756ea1be0a0d86, 0x8, 0xaf13cff86f18dace, 0xc0002f65b0)
        /github/workspace/coolq/cqcode.go:585 +0x10b9
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).ToElement(0xc00000c1e0, 0xc0002ab064, 0x5, 0xc0004433d8, 0xc000443400, 0x1, 0xa, 0x44ea03, 0xc00002d520)
        /github/workspace/coolq/cqcode.go:312 +0x2911
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).ConvertStringMessage(0xc00000c1e0, 0xc0002ab060, 0x36, 0xcb3a00, 0xb, 0x1370850, 0x0)
        /github/workspace/coolq/cqcode.go:237 +0x7a3
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendPrivateMessage(0xc00000c1e0, 0x2ae83be8, 0xb72920, 0xc000443768, 0x0, 0x0)
        /github/workspace/coolq/api.go:268 +0x624
github.com/Mrs4s/go-cqhttp/server.(*httpServer).SendPrivateMessage(0x133fc20, 0xc000d90000)
        /github/workspace/server/http.go:198 +0x29a
github.com/Mrs4s/go-cqhttp/server.glob..func10(0x133fc20, 0xc000d90000)
        /github/workspace/server/http.go:424 +0x3c
github.com/Mrs4s/go-cqhttp/server.(*httpServer).HandleActions(0x133fc20, 0xc000d90000)
        /github/workspace/server/http.go:136 +0x1ac
github.com/gin-gonic/gin.(*Context).Next(0xc000d90000)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x42
github.com/Mrs4s/go-cqhttp/server.(*httpServer).Run.func1(0xc000d90000)
        /github/workspace/server/http.go:59 +0x154
github.com/gin-gonic/gin.(*Context).Next(0xc000d90000)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x42
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00007e3c0, 0xc000d90000)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x66d
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00007e3c0, 0xddf3c0, 0xc000525960, 0xc0001b8300)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x154
net/http.serverHandler.ServeHTTP(0xc000524380, 0xddf3c0, 0xc000525960, 0xc0001b8300)
        /usr/local/go/src/net/http/server.go:2807 +0xaa
net/http.(*conn).serve(0xc00011a000, 0xde1340, 0xc00003bbc0)
        /usr/local/go/src/net/http/server.go:1895 +0x873
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2933 +0x363
2020/09/13 11:50:14 http: panic serving [::1]:44147: runtime error: makeslice: len out of range
goroutine 47 [running]:
net/http.(*conn).serve.func1(0xc00011a140)
        /usr/local/go/src/net/http/server.go:1772 +0x140
panic(0xbbf5c0, 0xdbffd0)
        /usr/local/go/src/runtime/panic.go:973 +0x3a4
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200911100852-71bc19cd42eb/binary/reader.go:36
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadString(0xc0010cc748, 0xc000600000, 0x10)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200911100852-71bc19cd42eb/binary/reader.go:65 +0x5f
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).makeImageElem(0xc00000c1e0, 0xc000ad0814, 0x5, 0xc0010cd3d8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /github/workspace/coolq/cqcode.go:585 +0x10b9
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).ToElement(0xc00000c1e0, 0xc000ad0814, 0x5, 0xc0010cd3d8, 0xc0010cd400, 0x1, 0xa, 0x0, 0x0)
        /github/workspace/coolq/cqcode.go:312 +0x2911
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).ConvertStringMessage(0xc00000c1e0, 0xc000ad0810, 0x36, 0xcb3a00, 0xb, 0x1370850, 0x0)
        /github/workspace/coolq/cqcode.go:237 +0x7a3
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendPrivateMessage(0xc00000c1e0, 0x2ae83be8, 0xb72920, 0xc0010cd768, 0x0, 0x0)
        /github/workspace/coolq/api.go:268 +0x624
github.com/Mrs4s/go-cqhttp/server.(*httpServer).SendPrivateMessage(0x133fc20, 0xc00000d590)
        /github/workspace/server/http.go:198 +0x29a
github.com/Mrs4s/go-cqhttp/server.glob..func10(0x133fc20, 0xc00000d590)
        /github/workspace/server/http.go:424 +0x3c
github.com/Mrs4s/go-cqhttp/server.(*httpServer).HandleActions(0x133fc20, 0xc00000d590)
        /github/workspace/server/http.go:136 +0x1ac
github.com/gin-gonic/gin.(*Context).Next(0xc00000d590)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x42
github.com/Mrs4s/go-cqhttp/server.(*httpServer).Run.func1(0xc00000d590)
        /github/workspace/server/http.go:59 +0x154
github.com/gin-gonic/gin.(*Context).Next(0xc00000d590)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x42
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00007e3c0, 0xc00000d590)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x66d
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00007e3c0, 0xddf3c0, 0xc000ad81c0, 0xc000098e00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x154
net/http.serverHandler.ServeHTTP(0xc000524380, 0xddf3c0, 0xc000ad81c0, 0xc000098e00)
        /usr/local/go/src/net/http/server.go:2807 +0xaa
net/http.(*conn).serve(0xc00011a140, 0xde1340, 0xc000093280)
        /usr/local/go/src/net/http/server.go:1895 +0x873
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2933 +0x363
```

感激

**Comment by Amarillys** [comment]
在@nnnewb大佬帮助下，发现了问题了

以前[CQ:image]过来的文件名是[CQ:image,file=***.(jpg/png/gif)**]，我会把以原名把文件下到本地images文件夹
现在传过来是[CQ:image,file=*.**image**]导致直接覆盖了原有的.image文件

现在通过改下载的图片的拓展名规避了这个问题
