### ISSUE TITLE
获取群组成员信息超时导致的崩溃

### ISSUE THREAD

**Issue by remiliacn** [Mrs4s/go-cqhttp#31]
错误报告
```
[2020-08-05 06:41:17] [DEBUG]: 反向WS接收到API调用: get_group_member_info 参数: {"self_id":2044450237,"group_id":708157568,"user_id":1363634305,"no_cache":true}
Packet Timed out
[2020-08-05 06:41:32] [WARNING]: 刷新群 708157568 成员列表失败: time out
Packet Timed out
panic: EOF

goroutine 8 [running]:
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadBytes(...)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200804064012-e1e00ed0683b/binary/reader.go:39
github.com/Mrs4s/MiraiGo/binary.(*Reader).ReadInt32(0xc000011ed8, 0x1)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200804064012-e1e00ed0683b/binary/reader.go:58 +0x142
github.com/Mrs4s/MiraiGo/protocol/packets.ParseIncomingPacket(0x0, 0x0, 0x0, 0xc0003fb190, 0x10, 0x10, 0xc00026e320, 0x0, 0x0)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200804064012-e1e00ed0683b/protocol/packets/global.go:87 +0x90
github.com/Mrs4s/MiraiGo/client.(*QQClient).loop(0xc0001a1340)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200804064012-e1e00ed0683b/client/client.go:743 +0x18b
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).Login
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200804064012-e1e00ed0683b/client/client.go:151 +0x8d
```

**Comment by Mrs4s** [comment]
#19

**Comment by qinpersevere** [comment]
@Mrs4s 想问下，代码里没有请求get_group_member_info，框架本身会自动请求吗？使用时发现收到的每条消息都会做一次get_gr
oup_member_info，且每隔一段时间会报错一次导致退出。
![image](https://user-images.githubusercontent.com/22725102/89893325-b1438f80-dc0a-11ea-8d6c-170410564332.png)
