### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ChateauXiao** [Mrs4s/go-cqhttp#313]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.25-fix3
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**

[2020-09-22 07:03:52] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2020-09-22 07:03:57] [INFO]: 开始尝试登录并同步消息...
[2020-09-22 07:03:57] [INFO]: 使用协议: Android Pad
[2020-09-22 07:03:57] [INFO]: Protocol -> connect to server: 107.155.14.179:10001
[2020-09-22 07:05:10] [INFO]: 当前版本:v0.9.25-fix3
[2020-09-22 07:05:10] [WARNING]: 已开启Debug模式.
[2020-09-22 07:05:10] [DEBUG]: 开发交流群: 192548878
[2020-09-22 07:05:10] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2020-09-22 07:05:10] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2020-09-22 07:05:15] [INFO]: 开始尝试登录并同步消息...
[2020-09-22 07:05:15] [INFO]: 使用协议: Android Pad
[2020-09-22 07:05:15] [INFO]: Protocol -> connect to server: 107.155.14.179:10001
[2020-09-22 07:07:25] [ERROR]: Protocol -> connect server error: dial tcp 107.155.14.179:10001: connect: connection timed out
[2020-09-22 07:07:25] [INFO]: Protocol -> connect to server: 169.60.163.242:10001

[2020-09-22 07:09:35] [ERROR]: Protocol -> connect server error: dial tcp 169.60.163.242:10001: connect: connection timed out
[2020-09-22 07:09:35] [INFO]: Protocol -> connect to server: 203.205.255.224:8080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x57a055]

goroutine 12 [running]:
net.(*TCPConn).Read(0x0, 0xc0003d9544, 0x1, 0x1, 0x10, 0xb75f00, 0x1)
        <autogenerated>:1 +0x5
github.com/Mrs4s/MiraiGo/binary.(*NetworkReader).ReadByte(0xc000084f88, 0x4, 0x4, 0xc0003d9540)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200919153352-249af274638d/binary/reader.go:128 +0x7a
github.com/Mrs4s/MiraiGo/binary.(*NetworkReader).ReadBytes(0xc000084f88, 0x4, 0xc00004b738, 0x577d99, 0xdf65e0, 0xc0002a9e00, 0xc0003e81a0)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200919153352-249af274638d/binary/reader.go:141 +0x7f
github.com/Mrs4s/MiraiGo/binary.(*NetworkReader).ReadInt32(0xc00004b788, 0x11, 0x0, 0x0)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200919153352-249af274638d/binary/reader.go:151 +0x38
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop(0xc00012f340)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200919153352-249af274638d/client/client.go:1003 +0xa2
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).Login
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20200919153352-249af274638d/client/client.go:189 +0x86

**Comment by Mrs4s** [comment]
#309
