### ISSUE TITLE
    raise ApiNotAvailable when calling bot.get_group_member_list()

### ISSUE THREAD

**Issue by ChateauXiao** [Mrs4s/go-cqhttp#330]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.26
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
```
[2020-09-29 09:29:16,793] | ERROR | An exception occurred while handling event notice.group_increase.approve:
[2020-09-29 09:29:16,793] | ERROR |
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nonebot/notice_request.py", line 82, in handle_notice_or_request
    await _bus.emit(ev_name, session)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/bus.py", line 35, in emit
    results += await asyncio.gather(*coros)
  File "/root/nonebot/plugins.py", line 313, in group_increase
    await update_group_c(group_obj, session)
  File "/root/nonebot/plugins.py", line 89, in update_group_c
    mlist = await bot_.get_group_member_list(group_id=group_id, no_cache=True)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/__init__.py", line 219, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/lib/python3.8/site-packages/aiocqhttp/api_impl.py", line 199, in call_action
    raise ApiNotAvailable
aiocqhttp.exceptions.ApiNotAvailable
```

**Comment by Mrs4s** [comment]
need more detail.
