### ISSUE TITLE
panic: interface conversion: interface {} is nil, not client.LoginResponse

### ISSUE THREAD

**Issue by ChateauXiao** [Mrs4s/go-cqhttp#349]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.28
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
```
[2020-10-09 02:35:09] [INFO]: 当前版本:v0.9.28
[2020-10-09 02:35:09] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2020-10-09 02:35:09] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2020-10-09 02:35:14] [INFO]: 开始尝试登录并同步消息...
[2020-10-09 02:35:14] [INFO]: 使用协议: Android Pad
[2020-10-09 02:35:14] [INFO]: Protocol -> connect to server: 203.205.255.221:8080
[2020-10-09 02:35:14] [INFO]: Admin API 服务器已启动: 0.0.0.0:9999


panic: interface conversion: interface {} is nil, not client.LoginResponse

goroutine 1 [running]:
github.com/Mrs4s/MiraiGo/client.(*QQClient).Login(0xc0002ca300, 0x1000, 0x1000, 0xc000456000)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201008134448-b53aaceaa1b4/client/client.go:209 +0x2c0
github.com/Mrs4s/go-cqhttp/server.(*webServer).Dologin(0x13a9f20)
        /github/workspace/server/apiAdmin.go:102 +0x196
github.com/Mrs4s/go-cqhttp/server.(*webServer).Run(0x13a9f20, 0xc0003fb370, 0xc, 0xc0002ca300, 0x2)
        /github/workspace/server/apiAdmin.go:91 +0x222
main.main()
        /github/workspace/main.go:254 +0x85c
```

**Comment by 572705296** [comment]
我也遇到了 win64 .27正常 正向ws

**Comment by Mrs4s** [comment]
请尝试使用 'android phone'协议
