### ISSUE TITLE
[求指路] 在Linux上运行时发送本地图片

### ISSUE THREAD

**Issue by idlist** [Mrs4s/go-cqhttp#360]
框架使用的是koishi v1.12.0，go-cqhttp版本是0.9.28-fix1，方法是
```
let fileName = `./image_cache/${hashName(6)}.png`
meta.$send(`[CQ:image,file=${url.pathToFileURL(path.resolve(fileName))}]`)
```
这么写在Win10环境下没有问题，到了Linux上报错：
```
(node:4338) UnhandledPromiseRejectionWarning: SenderError: Error when trying to send to send_group_msg_async, args: {"groupId":（群号打码）,"message":"[CQ:image,file=file:///home/bot/qqbot/image_cache/700ecd.png]","autoEscape":false}, retcode: 100
    at Sender.get (/home/bot/qqbot/node_modules/koishi-core/dist/sender.js:55:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Sender.sendGroupMsgAsync (/home/bot/qqbot/node_modules/koishi-core/dist/sender.js:137:9)
(node:4338) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```
补充：之前没注意go-cqhttp本体有没有报错以及报错情况，正在查看。
补充：目的是利用ImageMagick生成图片并将此图片发送出去。生成图片这块没有报错，图片也正常生成了。
请问有什么解决或者绕路的方法吗？Linux新手，相关的东西不太懂，请见谅。

**Comment by idlist** [comment]
查看了一下go-cqhttp的日志：

**Comment by zangxx66** [comment]
类似`群消息发送失败: 账号可能被风控.`的提示，重新启动gocqhttp就正常了，原因不明
