### ISSUE TITLE
9.23换9.29登录后半分钟内闪退

### ISSUE THREAD

**Issue by zwa73** [Mrs4s/go-cqhttp#372]
go-cqhttp版本: 9.29
运行环境: windows server2012R2
连接方式: http

登录后半分钟内闪退

log内容
[2020-10-20 18:34:18] [INFO]: 当前版本:v0.9.29 
[2020-10-20 18:34:18] [INFO]: 将使用 device.json 内的设备信息运行Bot. 
[2020-10-20 18:34:18] [INFO]: 密码加密已启用, 请输入Key对密码进行解密以继续: (Enter 提交) 
[2020-10-20 18:34:21] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消. 
[2020-10-20 18:34:26] [INFO]: 开始尝试登录并同步消息... 
[2020-10-20 18:34:26] [INFO]: 使用协议: Android Pad 
[2020-10-20 18:34:26] [INFO]: Protocol -> connect to server: 120.232.18.228:8080 
[2020-10-20 18:34:26] [INFO]: Admin API 服务器已启动: 0.0.0.0:9999 
[2020-10-20 18:34:26] [INFO]: 登录成功 欢迎使用: 克里斯蒂·卡尼亚斯 
[2020-10-20 18:34:27] [INFO]: 开始加载好友列表... 
[2020-10-20 18:34:28] [INFO]: 共加载 164 个好友. 
[2020-10-20 18:34:28] [INFO]: 开始加载群列表... 
[2020-10-20 18:34:29] [INFO]: 收到服务器地址更新通知, 将在下一次重连时应用.  
[2020-10-20 18:34:32] [INFO]: 共加载 78 个群. 
[2020-10-20 18:34:32] [INFO]: 信息数据库初始化完成. 
[2020-10-20 18:34:32] [INFO]: 正在加载事件过滤器. 
[2020-10-20 18:34:32] [WARNING]: 事件过滤器启动失败: open filter.json: The system cannot find the file specified. 
[2020-10-20 18:34:32] [INFO]: 正在加载silk编码器... 
[2020-10-20 18:34:32] [INFO]: 资源初始化完成, 开始处理信息. 
[2020-10-20 18:34:32] [INFO]: アトリは、高性能ですから! 
[2020-10-20 18:34:32] [INFO]: HTTP POST上报器已启动: http://127.0.0.1:5800 
[2020-10-20 18:34:32] [INFO]: CQ HTTP 服务器已启动: 127.0.0.1:5700 
[2020-10-20 18:34:32] [INFO]: CQ Websocket 服务器已启动: 0.0.0.0:6700 
[2020-10-20 18:34:33] [INFO]: 收到群 xxxxxxxxxxxx(xxxxxxx) 内 【至尊滥弱萌新】日之朝(xxxxxxx) 的消息: [CQ:image,file=44e699f13745cd1d535c8a9796bae2dc.image]快进到红军直播宫刑再吊死 (-910798082) 
[2020-10-20 18:34:34] [INFO]: 收到群 xxxxxxxxxxxx(xxxxxxx) 内 伊拉克无条件(xxxxxxx) 的消息: 我贼想要狼末 (-654038384) 
[2020-10-20 18:34:36] [INFO]: 收到群 xxxxxxxxxxxx(xxxxxxx) 内 斯太木（黑绘ガチ恋勢(xxxxxxx) 的消息: 6000钻就出 (1632903034) 
[2020-10-20 18:34:38] [INFO]: 收到群 xxxxxxxxxxxx(xxxxxxx) 内 阿狸(xxxxxxx) 的消息: 生不出人 (295910025) 
[2020-10-20 18:34:39] [INFO]: 收到群 xxxxxxxxxxxx(xxxxxxx) 内 伊拉克无条件(xxxxxxx) 的消息: 给我个 (1074625322) 
[2020-10-20 18:34:40] [INFO]: 收到群 xxxxxxxxxxxx(xxxxxxx) 内 狐妖 ‮~ゃに(xxxxxxx) 的消息: [CQ:at,qq=182744096] 摸摸凡人 (1722026527) 
[2020-10-20 18:34:41] [INFO]: 收到群 xxxxxxxxxxxx(xxxxxxx) 内 暴躁感情(xxxxxxx) 的消息: [CQ:record,file=F73BDF94A94E0538F766214DF9A0E92A.amr] (-556969170)

**Comment by Mrs4s** [comment]
请使用终端打开以捕捉错误日志

**Comment by zwa73** [comment]
> 请使用终端打开以捕捉错误日志

panic: invalid argument to Intn

goroutine 248 [running]:
math/rand.(*Rand).Intn(0x12c43da0, 0x9502f900, 0x10)
        /usr/local/go/src/math/rand/rand.go:169 +0x7b
math/rand.Intn(...)
        /usr/local/go/src/math/rand/rand.go:337
github.com/guonaihong/gout/filter.(*Retry).getSleep(0x13117b60, 0x12c71700, 0x0)

        /go/pkg/mod/github.com/guonaihong/gout@v0.1.2/filter/retry.go:99 +0xed
github.com/guonaihong/gout/filter.(*Retry).Do(0x13117b60, 0x0, 0x0)
        /go/pkg/mod/github.com/guonaihong/gout@v0.1.2/filter/retry.go:155 +0x1d0

github.com/Mrs4s/go-cqhttp/server.(*httpClient).onBotPushEvent(0x131169c0, 0x131
17a80)
        /github/workspace/server/http.go:135 +0x2ae
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).dispatchEventMessage.func1(0x12e68408,
 0x13117a80)
        /github/workspace/coolq/bot.go:355 +0x38
created by github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).dispatchEventMessage
        /github/workspace/coolq/bot.go:353 +0xbf

**Comment by Mrs4s** [comment]
请检查http post的应用服务器是否正常，这个问题会在下个版本修复

**Comment by zwa73** [comment]
> 请检查http post的应用服务器是否正常，这个问题会在下个版本修复

没有开服务器，这个版本是得一直开着么？
下个版本是会像23一样可以不开着也能正常运行？
