### ISSUE TITLE
parse incoming packet error: return code unsuccessful: -10008

### ISSUE THREAD

**Issue by SK-415** [Mrs4s/go-cqhttp#384]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.29-fix2
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
请在这里详细描述bug的内容

遇到 `parse incoming packet error: return code unsuccessful: -10008` 错误后, 下一条发送的消息不会返回结果 (但是正常发出去了), 同时后端 nonebot 会产生 `WebSocket API call timeout` 报错, 之后再次发送就恢复正常了.

go-cqhttp日志 :
```
[2020-10-31 11:47:53] [ERROR]: Protocol -> parse incoming packet error: return code unsuccessful: -10008 
[2020-10-31 11:47:54] [ERROR]: Protocol -> connection dropped by server: EOF 
[2020-10-31 11:47:54] [INFO]: Protocol -> connect to server: 113.96.12.85:8080 
[2020-10-31 11:47:57] [INFO]: 收到服务器地址更新通知, 将在下一次重连时应用.  
[2020-10-31 11:47:59] [INFO]: 收到群 ***(***) 内 群要饭时不时找鹿鹿贴贴(3536839605) 的消息: 明天万圣节（指正） (101240385) 
[2020-10-31 11:48:23] [INFO]: 发送群 1080312068(1080312068)  的消息: 秋凛子Rinco发布 ... (1780151377) 
[2020-10-31 11:48:24] [INFO]: 发送群 1080312068(1080312068)  的消息: 秋凛子Rinco发布 ... (-216816149) 
```

nonebot2日志 (第一次发送后产生的报错, bot 收到报错后尝试重发正常):
```
10-31 11:48:23 [ERROR] haruka_bot | Traceback (most recent call last):
  File "src/plugins/haruka_bot/utils.py", line 148, in safe_send
    message_id = await bot.call_api('send_'+send_type+'_msg', **{
  File "/usr/local/lib/python3.8/site-packages/nonebot/adapters/cqhttp.py", line 351, in call_api
    return _handle_api_result(await ResultStore.fetch(
  File "/usr/local/lib/python3.8/site-packages/nonebot/adapters/cqhttp.py", line 252, in fetch
    raise NetworkError("WebSocket API call timeout") from None
nonebot.exception.NetworkError: WebSocket API call timeout
```

**复现方法**
请在这里分步骤的描述如何复现这个bug

正常挂着 go-cqhttp 时概率出现, 暂无稳定复现方法. 已开启 Debug 日志, 争取下次出现能提供更多信息.

**Comment by Mrs4s** [comment]
已修复此情况
