### ISSUE TITLE
set_restart 无法使用

### ISSUE THREAD

**Issue by SK-415** [Mrs4s/go-cqhttp#425]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.31-fix1
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
请在这里详细描述bug的内容

调用 `set_restart` api 报错. 内容如下: 
```
[2020-11-18 01:14:45] [INFO]: 正在重启中...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x78 pc=0x9f337e]

goroutine 1 [running]:
net/http.(*Server).Shutdown(0x0, 0x11ba260, 0xc00050ff20, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2700 +0x5e
github.com/Mrs4s/go-cqhttp/server.(*httpServer).ShutDown(0x16ae6b0)
        /github/workspace/server/http.go:526 +0xba
main.main()
        /github/workspace/main.go:331 +0xe9c
```

**复现方法**
请在这里分步骤的描述如何复现这个bug

调用 `set_restart` api

**Comment by Mrs4s** [comment]
@Ink-33

**Comment by Ink-33** [comment]
在修了在修了
