### ISSUE TITLE
输入不了验证码

### ISSUE THREAD

**Issue by JarmoHu** [Mrs4s/go-cqhttp#455]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.32
运行环境: windows_amd64
连接方式: http

**bug内容**
刚刚才申请的账号，输入不了验证码。
```shell
go-cqhttp.exe
[2020-12-01 12:14:28] [INFO]: 当前版本:v0.9.32
[2020-12-01 12:14:28] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2020-12-01 12:14:28] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2020-12-01 12:14:33] [INFO]: 开始尝试登录并同步消息...
[2020-12-01 12:14:33] [INFO]: 使用协议: iPad
[2020-12-01 12:14:33] [INFO]: Protocol -> connect to server: 109.244.128.121:8080
[2020-12-01 12:14:33] [INFO]: Protocol -> connect to server: 120.232.18.27:80

                  ....
                .*....**.
              .*..     .*.
             .*   .****  ..
            ..   .*   .*  .    .....
            *    ..    .. .......  ..                    .**...
           ..    .     .* **.  ..   ..                 .*. .....
           *     *     .:.:.  ....   .                ..  ...*..
          .*     *     .*...  .. *   .                .   .  .. .
          ..     * ********:   . .   .    ...        ..  ..   . .
          ..     * *.......:.  ...  ..    ...*...    .   .    :..
          :&&&&&&o ooo&&&&&&.  .**:oo.   ..    ..... .   .    ..
          :888888o ..*&88888. .:o&888&.  ..   ... .**.   .
          *888888o   .&88888o&&8o*&888:  .    ....  **  ..
          .&88888o   .&8888&&888o :888&  *    * ..  .ooo&o
          .&88888o   .&88888o888& *888&...   .. ..  .&888&.    ..
           o88888o   .&8888&:8888..&888:..   .. ..  .&888&.    o&:
           *88888&   .&8888&*&888* o888&o*.  *...    o8888*    o8&
           .o8888&.  .&8888&.o888: *&&o*o&&o****.   .o8888:    o8o
            .&8888o**o88888&.:888o  .. .&8888&&o*.....&888&.   o8:
             .&8888888888888.*&o:.     *&888&*:&8&&*  o8888:  :8&.
              .:&&8888&o*o&&. .        :8888&  o888o. .&8888&&8&*
                 .****.  ...           o8888:  :8888*  .o&88&&o.
                                      .&8888*  o8888:    .*:*.
                                      *8888&.  o8888:
                                      :8888&..*88888*
                                      *o&888&&&8888&.
                                        .*:&&88888&:
                                            .:o&&o:
                                               ..



panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x161ca96]

goroutine 1 [running]:
github.com/Mrs4s/go-cqhttp/server.(*webServer).Dologin(0x1ed0b20)
        /github/workspace/server/apiAdmin.go:135 +0x476
github.com/Mrs4s/go-cqhttp/server.(*webServer).Run(0x1ed0b20, 0xc000037a10, 0xc, 0xc000651200, 0x2)
        /github/workspace/server/apiAdmin.go:99 +0x1da
main.main()
        /github/workspace/main.go:323 +0xcd6
```
**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by JarmoHu** [comment]
v0.9.31就可以输入欸？

**Comment by daofeng2015** [comment]
新账号建议不要直接用,用app端挂几天再说.特别容易被检测

**Comment by JarmoHu** [comment]
20201202,突然发现linux上有同样的情况，而且无论新旧账号都会出现
