### ISSUE TITLE
panic错误导致闪退

### ISSUE THREAD

**Issue by zangxx66** [Mrs4s/go-cqhttp#456]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.33
运行环境: linux_amd64
连接方式: 反向WS

**bug内容**
``` 
root@VM-0-7-ubuntu:~/go# ./go-cqhttp
[2020-12-03 00:13:39] [INFO]: 当前版本:v0.9.33
[2020-12-03 00:13:39] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2020-12-03 00:13:39] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2020-12-03 00:13:44] [INFO]: 开始尝试登录并同步消息...
[2020-12-03 00:13:44] [INFO]: 使用协议: MacOS
[2020-12-03 00:13:46] [INFO]: Protocol -> connect to server: 203.205.255.220:8080
[2020-12-03 00:13:46] [INFO]: Admin API 服务器已启动: 127.0.0.1:9999
[2020-12-03 00:13:46] [INFO]: 登录成功 欢迎使用: 小仓唯
[2020-12-03 00:13:47] [INFO]: 开始加载好友列表...
[2020-12-03 00:13:48] [INFO]: 共加载 24 个好友.
[2020-12-03 00:13:48] [INFO]: 开始加载群列表...
[2020-12-03 00:13:48] [INFO]: 共加载 3 个群.
[2020-12-03 00:13:48] [INFO]: 信息数据库初始化完成.
[2020-12-03 00:13:48] [INFO]: 正在加载事件过滤器.
[2020-12-03 00:13:48] [INFO]: 事件过滤器启动成功.
[2020-12-03 00:13:48] [INFO]: 正在加载silk编码器...
[2020-12-03 00:13:48] [INFO]: 资源初始化完成, 开始处理信息.
[2020-12-03 00:13:48] [INFO]: アトリは、高性能ですから!
[2020-12-03 00:13:48] [INFO]: 开始尝试连接到反向Websocket Universal服务器: ws://127.0.0.1:9222/ws
[2020-12-03 00:13:48] [INFO]: 正在检查更新.
[2020-12-03 00:13:48] [INFO]: 检查更新完成. 当前已运行最新版本.
[2020-12-03 00:13:49] [INFO]: 收到服务器地址更新通知, 根据配置文件已忽略.
[2020-12-03 00:18:29] [INFO]: 收到群 墨丘利财团(719892154) 内 PicACG(444742616) 的消息: 怎么拆 布丁 空花 裁缝 水吃 深月 (-1435949689)
[2020-12-03 00:18:32] [INFO]: 发送群 719892154(719892154)  的消息: [{"type":" ... (-579988207)
[2020-12-03 00:24:38] [INFO]: 收到群 墨丘利财团(719892154) 内 PicACG(444742616) 的消息: 怎么拆 布丁 空花 铃铛 瓜忍 狼布丁 (1124761778)
[2020-12-03 00:24:40] [INFO]: 发送群 719892154(719892154)  的消息: [{"type":" ... (873312292)
[2020-12-03 00:27:22] [INFO]: 收到群 AquinLive(871545895) 内 夏色祭(444742616) 的消息: [CQ:image,file=e71ebb229d9a3b5e93c97bb46aab7704.image] (-442207359)
[2020-12-03 00:27:23] [WARNING]: ocr image error: server error, code: 100 msg: hit failed,need upload
[2020-12-03 00:27:52] [INFO]: 收到群 AquinLive(871545895) 内 鱿鱼吸猫猫(3389673573) 的消息: 66666 (-1834794217)
[2020-12-03 00:31:36] [INFO]: 收到群 墨丘利财团(719892154) 内 PicACG(444742616) 的消息: 怎么拆 羊驼 偶像 环奈 瓜忍 水黑 (-1392189026)
[2020-12-03 00:31:39] [INFO]: 发送群 719892154(719892154)  的消息: [{"type":" ... (-637284088)
[2020-12-03 00:35:54] [INFO]: 收到群 AquinLive(871545895) 内 溺‮�！了射要‭�(649960377) 的消息: 66666 (195695277)
[2020-12-03 00:44:01] [INFO]: 收到群 墨丘利财团(719892154) 内 PicACG(444742616) 的消息: 怎么拆 布丁 偶像 黄骑 狼布丁 水黑 (1253887129)
[2020-12-03 00:44:10] [INFO]: 发送群 719892154(719892154)  的消息: [{"type":" ... (1035729935)
panic: send on closed channel

goroutine 610 [running]:
github.com/Mrs4s/MiraiGo/client.(*QQClient).sendGroupMessage.func1(0xc000276300, 0xc0002fe630)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201202140458-0eb4eb738d31/client/group_msg.go:75 +0x49
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).dispatchGroupMessageReceiptEvent.func1
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201202140458-0eb4eb738d31/client/events.go:281 +0x56
root@VM-0-7-ubuntu:~/go#   
```

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by Mrs4s** [comment]
已修复
