### ISSUE TITLE
0.9.34撤回出错

### ISSUE THREAD

**Issue by corvo007** [Mrs4s/go-cqhttp#477]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: v0.9.34
运行环境: windows_amd64
连接方式: 反向WS

**bug内容**
试图调用delete_msg方法时，出现以下报错：
```
[2020-12-10 16:30:24] [INFO]: 处置WS命令时发生无法恢复的异常：runtime error: invalid memory address or nil pointer dereference
goroutine 59 [running]:
runtime/debug.Stack(0xc0003476a8, 0x1889a80, 0x2033410)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa5
github.com/Mrs4s/go-cqhttp/server.(*websocketConn).handleRequest.func1(0xc000297820)
        /github/workspace/server/websocket.go:320 +0x5e
panic(0x1889a80, 0x2033410)
        /usr/local/go/src/runtime/panic.go:969 +0x1c7
github.com/Mrs4s/MiraiGo/client.(*QQClient).RecallGroupMessage(0xc000226300, 0x277a28b2, 0xf6603477000050d6, 0xb, 0xc0001a4648)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201209180326-c07a8a9c8a83/client/recall.go:15 +0x6d
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQDeleteMessage(0xc0001308c0, 0xc0c54410c2, 0xa)
        /github/workspace/coolq/api.go:494 +0x1d5
github.com/Mrs4s/go-cqhttp/server.glob..func12(0xc0001308c0, 0x5, 0xc000034103, 0x31, 0x0, 0x0, 0x0, 0x23, 0x0)
        /github/workspace/server/websocket.go:410 +0x13f
github.com/Mrs4s/go-cqhttp/server.(*websocketConn).handleRequest(0xc000297820, 0xc0001308c0, 0xc0007b0600, 0x69, 0x600)
        /github/workspace/server/websocket.go:329 +0x639
created by github.com/Mrs4s/go-cqhttp/server.(*websocketClient).listenApi
        /github/workspace/server/websocket.go:181 +0x94

[2020-12-10 16:30:24] [WARNING]: 监听反向WS API时出现错误: read tcp 127.0.0.1:2818->127.0.0.1:8080: use of closed network connection
```

**复现方法**
调用delete_msg接口

**Comment by sam01101** [comment]
#468 ，请关闭此issuse
