### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by zangxx66** [Mrs4s/go-cqhttp#506]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: go-cqhttp-v0.9.35
运行环境: linux_amd64
连接方式: 反向ws
使用协议: macos

**bug内容**
``` 
[2020-12-20 01:02:20] [INFO]: 收到群 AquinLive(871545895) 内 Yuuki(422203957) 的消息: 融合路人 哈哈剑 (-600167780)
[2020-12-20 01:02:20] [INFO]: 群 AquinLive(871545895) 内 安夜丶(2537237629) 戳了戳 小仓唯(735742327)
[2020-12-20 01:02:21] [INFO]: 发送群 871545895(871545895)  的消息: [{"type":" ... (1113505599)
[2020-12-20 01:02:21] [INFO]: 收到群 艾琳娜，JOJO的初吻阔(439156990) 内 铁华团团长（会长不行了）(424300284) 的消息: [CQ:image,file=2b1b7f887dccecb4ef94d1de006aaabf.image] (-1941056052)
[2020-12-20 01:02:32] [INFO]: 发送群 871545895(871545895)  的消息: [{"type":" ... (895061929)
panic: send on closed channel

goroutine 16684 [running]:
github.com/Mrs4s/MiraiGo/client.(*QQClient).sendGroupMessage.func1(0xc000126300, 0xc000190cd0)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201218175143-7312c96e82f7/client/group_msg.go:84 +0x74
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).dispatchGroupMessageReceiptEvent.func1
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201218175143-7312c96e82f7/client/events.go:281 +0x56
root@VM-0-7-ubuntu:~/go#    
```

**复现方法**
请在这里分步骤的描述如何复现这个bug

**Comment by xxyy3130** [comment]
![image](https://user-images.githubusercontent.com/61443746/102703325-57ce2a00-42a8-11eb-85d0-e9a0f7627651.png)

**Comment by chenxuuu** [comment]
+1

```log
[2020-12-20 10:47:02] [INFO]: 发送群 327870xxx(327870xxx)  的消息: 我被猪@了！ (-1105049338)
[2020-12-20 10:47:16] [INFO]: 收到群 嗯？(327870xxx) 内 没有名字的二五仔(xxxxxxx) 的消息: [CQ:image,file=9e00a46aebbac689c336c617b3d55cd0.image] (-920290928)
[2020-12-20 10:49:58] [INFO]: 收到群 嗯？(327870xxx) 内 白玉京中花已发(1982451770) 的消息: 签到 (1503290369)
panic: send on closed channel

goroutine 262 [running]:
github.com/Mrs4s/MiraiGo/client.(*QQClient).sendGroupMessage.func1(0xc00021a300, 0xc000290510)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201218175143-7312c96e82f7/client/group_msg.go:84 +0x7b
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).dispatchGroupMessageReceiptEvent.func1
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201218175143-7312c96e82f7/client/events.go:281 +0x5d

D:\cat\go>
```

使用的是正向ws+正向http

**Comment by Mrs4s** [comment]
已修复
