### ISSUE TITLE
【BUG】BOT突然离线 进程挂起

### ISSUE THREAD

**Issue by Cyame** [Mrs4s/go-cqhttp#514]
**环境信息**
运行环境: CentOS 7
go-cqhttp版本: go-cqhttp-v0.9.35
连接方式: WS_Reverse

**bug内容**
BOT突然断线，似乎并不常见，偶发过2-3次（自go-cqhttp-v0.9.31-fix1开始）

日志如下
---

[2020-12-24 06:48:44] [DEBUG]: Protocol -> rev pkt: Heartbeat.Alive seq: 27406
[2020-12-24 06:49:15] [DEBUG]: Protocol -> rev pkt: Heartbeat.Alive seq: 27407
[2020-12-24 06:49:45] [DEBUG]: Protocol -> rev pkt: Heartbeat.Alive seq: 27408
[2020-12-24 06:50:15] [DEBUG]: Protocol -> rev pkt: Heartbeat.Alive seq: 27409
[2020-12-24 06:50:15] [DEBUG]: Protocol -> rev pkt: StatSvc.register seq: 27410
[2020-12-24 06:50:45] [DEBUG]: Protocol -> rev pkt: Heartbeat.Alive seq: 27411
[2020-12-24 06:51:05] [DEBUG]: WS接收到API调用: send_msg 参数: {"self_id": "***", "group_id": "***", "message": " \u53cd\u753a\u8c46\u8150\ud83d\udcdb12/27SHT\u307e\u305e\u304f22\u7684\u63a8\u7279\u66f4\u65b0\u4e86\uff1a\n\u30a2\u30cb\u30e1\u3057\u307e\u3080\u3089\u306e\u300c\u306f\uff1f\u300d\u300c\u3048\uff1f\u300d\u3063\u3066\u53f0\u8a5e\u304c\u597d\u304d\u3059\u304e\u308b\u30aa\u30bf\u30af\u3067\u3059\u3002\u79c1\u4ee5\u5916\u306b\u3082\u5c45\u308b\u306f\u305a\n3\u8a71\u306f\u305d\u306e\u53f0\u8a5e\u304c\u3044\u3063\u3071\u3044\u805e\u3051\u308b\u306e\u3067\u30aa\u30b9\u30b9\u30e1\u3067\u3059  \n\u8ddf\u63a8\u5ef6\u65f6\uff1a1.53\u5206\u949f\n\u94fe\u63a5\uff1ahttps://twitter.com/merryyy87/status/1341878641857232896\n\u4e34\u65f6\u63a8\u6587ID\uff1a#5404"}
[2020-12-24 06:51:05] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbSendMsg seq: 27413
[2020-12-24 06:51:05] [DEBUG]: Protocol -> rev pkt: OnlinePush.PbPushGroupMsg seq: 42319
[2020-12-24 06:51:05] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbSendMsg seq: 27414
[2020-12-24 06:51:05] [DEBUG]: Protocol -> rev pkt: OnlinePush.PbPushGroupMsg seq: 63281
[2020-12-24 06:51:05] [DEBUG]: Protocol -> rev pkt: MessageSvc.PbSendMsg seq: 27412
panic: send on closed channel

goroutine 104359 [running]:
github.com/Mrs4s/MiraiGo/client.(*QQClient).sendGroupMessage.func1(0xc000158300, 0xc0005ec1c0)
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201218175143-7312c96e82f7/client/group_msg.go:84 +0x74
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).dispatchGroupMessageReceiptEvent.func1
        /go/pkg/mod/github.com/!mrs4s/!mirai!go@v0.0.0-20201218175143-7312c96e82f7/client/events.go:281 +0x56

**复现方法**
未知

**Comment by Mrs4s** [comment]
更新最新版本
