### ISSUE TITLE
ws断线问题

### ISSUE THREAD

**Issue by masnn** [Mrs4s/go-cqhttp#6]
```
http: panic serving 127.0.0.1:60754: concurrent write to websocket connection
 goroutine 20021 [running]:
 net/http.(*conn).serve.func1(0xc000222a00)
     /usr/local/go/src/net/http/server.go:1772 +0x139
 panic(0xb13340, 0xd43060)
      /usr/local/go/src/runtime/panic.go:973 +0x396
 github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc000e33800, 0x1, 0x0, 0x0, 0x0, 0xc000c4d500, 0x7f8a80157130)
      /go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:610 +0x5e9
 github.com/gorilla/websocket.(*messageWriter).Close(0xc000e33800, 0xb77060, 0xc000e33710)
      /go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:724 +0x62
 github.com/gorilla/websocket.(*Conn).WriteJSON(0xc001ba26e0, 0xb77060, 0xc000e33710, 0x4, 0xc001d2b978)
     /go/pkg/mod/github.com/gorilla/websocket@v1.4.2/json.go:29 +0x12e
 github.com/Mrs4s/go-cqhttp/server.(*websocketServer).listenApi(0x128be60, 0xc001ba26e0)
     /github/workspace/server/websocket.go:276 +0x572
 github.com/Mrs4s/go-cqhttp/server.(*websocketServer).any(0x128be60, 0xd62fa0, 0xc000c69340, 0xc000167600)
      /github/workspace/server/websocket.go:256 +0x254
 net/http.HandlerFunc.ServeHTTP(0xc0006e0810, 0xd62fa0, 0xc000c69340, 0xc000167600)
     /usr/local/go/src/net/http/server.go:2012 +0x44
 net/http.(*ServeMux).ServeHTTP(0x128be20, 0xd62fa0, 0xc000c69340, 0xc000167600)
     /usr/local/go/src/net/http/server.go:2387 +0x1a5
 net/http.serverHandler.ServeHTTP(0xc0002a7880, 0xd62fa0, 0xc000c69340, 0xc000167600)
      /usr/local/go/src/net/http/server.go:2807 +0xa3
 net/http.(*conn).serve(0xc000222a00, 0xd65060, 0xc0001935c0)
      /usr/local/go/src/net/http/server.go:1895 +0x86c
 created by net/http.(*Server).Serve
      /usr/local/go/src/net/http/server.go:2933 +0x35c
```

**Comment by Mrs4s** [comment]
请问在什么条件下才能复现

**Comment by Mrs4s** [comment]
应该是没处理好并发 我加个锁

**Comment by Mrs4s** [comment]
请尝试最新的Release
