### ISSUE TITLE
撤回消息时出错，无法撤回

### ISSUE THREAD

**Issue by dlytang** [Mrs4s/go-cqhttp#609]
**环境信息**
请根据实际使用环境修改以下信息
go-cqhttp版本: go-cqhttp-v0.9.39-fix1
运行环境: linux
连接方式: 反向WS
使用协议: ipad

**bug内容**
在nonebot中使用 `await bot.delete_msg(message_id=message_id)`

gocqhttp提示
```
[2021-02-02 19:19:18] [INFO]: 收到群 群名(*********) 内 昵称(*********) 的消息: hello (7954478) 
[2021-02-02 19:19:18] [WARNING]: 获取信息时出现错误: leveldb: not found id: 1989806812 
```
nonebot则提示
```
Task exception was never retrieved
future: <Task finished coro=<CQHttp._handle_event_with_response() done, defined at /usr/local/python3/lib/python3.7/site-packages/aiocqhttp/__init__.py:581> exception=<ActionFailed, retcode=100>>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/aiocqhttp/__init__.py", line 583, in _handle_event_with_response
    response = await self._handle_event(payload)
  File "/usr/local/python3/lib/python3.7/site-packages/aiocqhttp/__init__.py", line 577, in _handle_event
    await self._bus.emit(event_name, ev)))
  File "/usr/local/python3/lib/python3.7/site-packages/aiocqhttp/bus.py", line 58, in emit
    *args, **kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/aiocqhttp/utils.py", line 41, in run_async_funcs
    results += await asyncio.gather(*coros)
  File "my_nonebot_path/nonebot_yang/plugins/test/test.py", line 41, in group_message
    await bot.delete_msg(message_id=1989806812)
  File "/usr/local/python3/lib/python3.7/site-packages/aiocqhttp/__init__.py", line 223, in call_action
    return await self._api.call_action(action=action, **params)
  File "/usr/local/python3/lib/python3.7/site-packages/aiocqhttp/api_impl.py", line 186, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "/usr/local/python3/lib/python3.7/site-packages/aiocqhttp/api_impl.py", line 162, in call_action
    await ResultStore.fetch(seq, self._timeout_sec))
  File "/usr/local/python3/lib/python3.7/site-packages/aiocqhttp/api_impl.py", line 51, in _handle_api_result
    raise ActionFailed(retcode=result.get('retcode'))
aiocqhttp.exceptions.ActionFailed: <ActionFailed, retcode=100>
```

**Comment by sam01101** [comment]
> [2021-02-02 19:19:18] [INFO]: 收到群 群名(*********) 内 昵称(*********) 的消息: hello (7954478) 
> [2021-02-02 19:19:18] [WARNING]: 获取信息时出现错误: leveldb: not found id: 1989806812

信息ID对不上, 尝试撤回`7954478`?
