### ISSUE TITLE
登录时出现Protocol -> unknown login response: xxx

### ISSUE THREAD

**Issue by corvo007** [Mrs4s/go-cqhttp#739]
**环境信息**

go-cqhttp版本: v0.9.40-fix4
运行环境: windows-amd64
连接方式: 反向ws
使用协议: Android Phone

**bug内容**
登录时有时会弹出以下的错误：
```
[2021-03-18 13:18:13] [INFO]: 当前版本:v0.9.40-fix4
[2021-03-18 13:18:13] [WARNING]: 已开启Debug模式.
[2021-03-18 13:18:13] [DEBUG]: 开发交流群: 192548878
[2021-03-18 13:18:13] [INFO]: 用户交流群: 721829413
[2021-03-18 13:18:13] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2021-03-18 13:18:13] [INFO]: 开始尝试登录并同步消息...
[2021-03-18 13:18:13] [INFO]: 使用协议: Android Phone
[2021-03-18 13:18:14] [INFO]: Protocol -> connect to server: 113.96.13.125:8080
[2021-03-18 13:18:14] [DEBUG]: pprof 性能分析服务已启动在 http://127.0.0.1:9999/debug/pprof, 如果有任何性能问题请下载报 告并提交给开发者
[2021-03-18 13:18:15] [DEBUG]: Protocol -> rev pkt: wtlogin.login seq: 13878
[2021-03-18 13:18:15] [DEBUG]: Protocol -> unknown login response: 200
[2021-03-18 13:18:15] [DEBUG]: Protocol -> Type: b0f7 Value: dcb7341a5a6796767adbb63275431d9ea0e67474a0f78545fc407c0f1e5150de32000...(省略一大串零)...00000
[2021-03-18 13:18:15] [DEBUG]: Protocol -> decode pkt wtlogin.login error: unknown login response: 200
github.com/Mrs4s/MiraiGo/client.decodeLoginResponse
        github.com/Mrs4s/MiraiGo@v0.0.0-20210308011115-8c89d62657af/client/decoders.go:180
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func2
        github.com/Mrs4s/MiraiGo@v0.0.0-20210308011115-8c89d62657af/client/client.go:933
runtime.goexit
        runtime/asm_amd64.s:1371
[2021-03-18 13:18:15] [INFO]: Protocol -> connect to server: 113.96.12.27:8080
[2021-03-18 13:18:15] [DEBUG]: Protocol -> rev pkt: wtlogin.login seq: 13879
[2021-03-18 13:18:17] [DEBUG]: Protocol -> rev pkt: wtlogin.login seq: 13880
[2021-03-18 13:18:17] [DEBUG]: Protocol -> unknown login response: 205
[2021-03-18 13:18:17] [DEBUG]: Protocol -> Type: 6998 Value: cf3af3434b8b824e583537fb71a655ab7a9d3b7dfccbff8453328262b7e600000...(省略一大串零)...000000
[2021-03-18 13:18:17] [DEBUG]: Protocol -> decode pkt wtlogin.login error: unknown login response: 205
github.com/Mrs4s/MiraiGo/client.decodeLoginResponse
        github.com/Mrs4s/MiraiGo@v0.0.0-20210308011115-8c89d62657af/client/decoders.go:180
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func2
        github.com/Mrs4s/MiraiGo@v0.0.0-20210308011115-8c89d62657af/client/client.go:933
runtime.goexit
        runtime/asm_amd64.s:1371
[2021-03-18 13:18:17] [DEBUG]: Protocol -> decode pkt wtlogin.login error: unknown login response: 205
github.com/Mrs4s/MiraiGo/client.decodeLoginResponse
        github.com/Mrs4s/MiraiGo@v0.0.0-20210308011115-8c89d62657af/client/decoders.go:180
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func2
        github.com/Mrs4s/MiraiGo@v0.0.0-20210308011115-8c89d62657af/client/client.go:933
runtime.goexit
        runtime/asm_amd64.s:1371
[2021-03-18 13:21:04] [DEBUG]: Protocol -> decode pkt wtlogin.login error: Packet timed out
github.com/Mrs4s/MiraiGo/client.(*QQClient).sendAndWait
        github.com/Mrs4s/MiraiGo@v0.0.0-20210308011115-8c89d62657af/client/client.go:846
github.com/Mrs4s/MiraiGo/client.decodeLoginResponse
        github.com/Mrs4s/MiraiGo@v0.0.0-20210308011115-8c89d62657af/client/decoders.go:152
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func2
        github.com/Mrs4s/MiraiGo@v0.0.0-20210308011115-8c89d62657af/client/client.go:933
runtime.goexit
        runtime/asm_amd64.s:1371
[2021-03-18 13:21:04] [ERROR]: Protocol -> panic on decoder wtlogin.login : send on closed channel
goroutine 240 [running]:
runtime/debug.Stack(0xc000407c30, 0x102e7a0, 0x1284020)
        runtime/debug/stack.go:24 +0xa5
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func2.1(0xc000531000, 0xc00066dc70)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210308011115-8c89d62657af/client/client.go:926 +0x78
panic(0x102e7a0, 0x1284020)
        runtime/panic.go:965 +0x1c7
github.com/Mrs4s/MiraiGo/client.(*QQClient).sendAndWait.func2(0x0, 0x0, 0x1296980, 0xc0006e42d0)
        github.com/Mrs4s/MiraiGo@v0.0.0-20210308011115-8c89d62657af/client/client.go:826 +0x7d
github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop.func2(0xc000531000, 0xc00066dc70, 0xc0000335e4, 0x45, 0x4c)

        github.com/Mrs4s/MiraiGo@v0.0.0-20210308011115-8c89d62657af/client/client.go:947 +0x20f
created by github.com/Mrs4s/MiraiGo/client.(*QQClient).netLoop
        github.com/Mrs4s/MiraiGo@v0.0.0-20210308011115-8c89d62657af/client/client.go:923 +0x538

```

**复现方法**

偶发出现的，没法稳定复现

**Comment by timi137137** [comment]
更换其他协议会出现问题吗，maybe你可以试试iPad协议？

**Comment by Ink-33** [comment]
应该是TX服务器抽风，等过几秒试试

**Comment by sam01101** [comment]
腾讯老问题了，我们也没法解决
当发生时，请等待5秒后再次登录

**Comment by Mrs4s** [comment]
老问题了 tx抽风

**Comment by timi137137** [comment]
> 应该是TX服务器抽风，等过几秒试试

论你没看见他的描述，他说偶尔出现也就是知道可以重试(光速打脸

**Comment by sam01101** [comment]
> > 应该是TX服务器抽风，等过几秒试试
> 
> 论你没看见他的描述，他说偶尔出现也就是知道可以重试(光速打脸

理论上你可以无限重试到没有（

**Comment by timi137137** [comment]
反正都用了反向ws，干脆自动重启gocq就是了
