### ISSUE TITLE
撤回消息失败,群和私聊撤回消息都会失败,配置文件里的数据库开了,测试了多次100%触发

### ISSUE THREAD

**Issue by RiotGamesU** [Mrs4s/go-cqhttp#941]
**环境信息**

go-cqhttp版本: 测试了两个版本,分别是v1.0.0-beta4和[70558dc](https://github.com/Mrs4s/go-cqhttp/actions/runs/973660200),两个版本都一样撤回失败,两个版本打印的报错信息和nonebot2打印的报错信息也一样
运行环境: win10 latest
连接方式: nonebot2 latest,nonebot2使用的adapter为cqhttp latest
使用协议: ws-reverse

**bug内容**

撤回消息失败,群和私聊撤回消息都会失败,配置文件里的数据库开了,测试了多次100%触发

1.go-cqhttp打印的信息:
`[2021-06-27 20:37:17] [WARNING]: 获取信息时出现错误: leveldb: not found id: 0`

2.nonebot2打印的信息,通过nb run的方式运行:
```
06-27 20:37:17 [ERROR] nonebot | Running matcher <Matcher from setu, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\PycharmProjects\bot0\venv\Scripts\nb.exe\__main__.py", line 7, in <module>
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\nb_cli\commands\main.py", line 26, in run
    run_bot(file, app)
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\nonebot\__init__.py", line 227, in run
    get_driver().run(host, port, *args, **kwargs)
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(app or self.server_app,
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\uvicorn\main.py", line 386, in run
    server.run()
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\uvicorn\server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\nonebot\message.py", line 126, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\nonebot\message.py", line 154, in _run_matcher
    await matcher.run(bot, event, state)
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\nonebot\matcher.py", line 544, in run
    await handler(self, bot, event, state_)
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\nonebot\handler.py", line 81, in __call__
    await self.func(
  File "C:\Users\xxx\PycharmProjects\bot0\abot\src/plugins\setu\__init__.py", line 239, in handle_first_receive
    await bot.delete_msg(message_id=message_id)
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\nonebot\adapters\cqhttp\bot.py", line 400, in call_api
    return await super().call_api(api, **data)
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\nonebot\adapters\_base.py", line 200, in call_api
    raise exception
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\nonebot\adapters\_base.py", line 183, in call_api
    result = await self._call_api(api, **data)
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\nonebot\adapters\cqhttp\bot.py", line 347, in _call_api
    return _handle_api_result(await ResultStore.fetch(
  File "c:\users\xxx\pycharmprojects\bot0\venv\lib\site-packages\nonebot\adapters\cqhttp\bot.py", line 188, in _handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.cqhttp.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 4}, msg=MESSAGE_NOT_FOUND, retcode=100, status=failed, wording=消息不存在>
```

3.机器人(nonebot2那边)的关键代码:
```
@func.handle()
async def handle_first_receive(bot: Bot, event: Event, state: T_State):
    message = [ {
                                "type": "text",
                                "data": {
                                    "text": " Success"
                                }
                            }, {
                                "type": "image",
                                "data": {
                                    "file": "https://xxx.xxx/xxx.jpg"
                                }
                            }]
    message_id = await func.send(message)
    await bot.delete_msg(message_id=message_id)
```

此处图片可以成功获取,文本+图片的消息可以成功发送

4.nonebot2的cqhttp的adapter的相关代码:
```
    async def delete_msg(self,
                         *,
                         message_id: int,
                         self_id: Optional[int] = ...) -> None:
        """
        :说明:

          撤回消息。

        :参数:

          * ``message_id``: 消息 ID
          * ``self_id``: 机器人 QQ 号
        """
        ...

```

5.配置文件相关内容:
```
database: # 数据库相关设置
  leveldb:
    # 是否启用内置leveldb数据库
    # 启用将会增加10-20MB的内存占用和一定的磁盘空间
    # 关闭将无法使用 撤回 回复 get_msg 等上下文相关功能
    enable: true
```

如果需要,可以贴上配置文件的所有内容

**复现方法**

1.运行go-cqhttp:
`go-cqhttp.exe faststart`
上述两个版本的任一版本

2.启动机器人(nonebot2构建的项目):
`nb run`

3.触发相关代码

4.go-cqhttp和机器人(nonebot2构建的项目)都会报错

**Comment by ishkong** [comment]
你的问题
请使用
`message_id = (await func.send(message))['message_id']`
来获取message_id

**Comment by sam01101** [comment]
```python
@func.handle()
async def handle_first_receive(bot: Bot, event: Event, state: T_State):
    message = [ {
                                "type": "text",
                                "data": {
                                    "text": " Success"
                                }
                            }, {
                                "type": "image",
                                "data": {
                                    "file": "https://xxx.xxx/xxx.jpg"
                                }
                            }]
    result = await func.send(message)
	message_id = result['message_id']
    await bot.delete_msg(message_id=message_id)
```

返回的并不只有 `message_id`, 返回的包含很多有用的信息, 因此不能直接获取 `message_id`

如果有需要可以手动 `print` 一次 `result` 看下 `json数组`

**Comment by RiotGamesU** [comment]
> 你的问题
> 请使用
> `message_id = (await func.send(message))['message_id']`
> 来获取message_id

好的,谢谢

**Comment by RiotGamesU** [comment]
> ```python
> @func.handle()
> async def handle_first_receive(bot: Bot, event: Event, state: T_State):
>     message = [ {
>                                 "type": "text",
>                                 "data": {
>                                     "text": " Success"
>                                 }
>                             }, {
>                                 "type": "image",
>                                 "data": {
>                                     "file": "https://xxx.xxx/xxx.jpg"
>                                 }
>                             }]
>     result = await func.send(message)
> 	message_id = result['message_id']
>     await bot.delete_msg(message_id=message_id)
> ```
> 
> 返回的并不只有 `message_id`, 返回的包含很多有用的信息, 因此不能直接获取 `message_id`
> 
> 如果有需要可以手动 `print` 一次 `result` 看下 `json数组`

好的,谢谢
