### ISSUE TITLE
使用接口发送消息都会出现下标越界

### ISSUE THREAD

**Issue by ouyanglong721** [Mrs4s/go-cqhttp#97]
**环境信息**
go-cqhttp版本: v0.9.18
运行环境: linux_arm
连接方式: http

**bug内容**
使用私聊接口或者是群聊接口发送消息,都会出如下的数组下标越界问题
````
2020/08/13 21:31:39 http: panic serving 192.168.3.8:3869: runtime error: index out of range [1] with length 1
goroutine 72 [running]:
net/http.(*conn).serve.func1(0x2292060)
	/usr/local/go/src/net/http/server.go:1772 +0xf0
panic(0x70b4e8, 0x22fe060)
	/usr/local/go/src/runtime/panic.go:973 +0x3a0
github.com/Mrs4s/go-cqhttp/server.(*httpServer).Run.func2(0x2396240)
	/github/workspace/server/http.go:62 +0x160
github.com/gin-gonic/gin.(*Context).Next(0x2396240)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x34
github.com/Mrs4s/go-cqhttp/server.(*httpServer).Run.func1(0x2396240)
	/github/workspace/server/http.go:56 +0x148
github.com/gin-gonic/gin.(*Context).Next(0x2396240)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x34
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0x239a4d0, 0x2396240)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x4a4
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0x239a4d0, 0x87dd88, 0x23961b0, 0x23c8000)
	/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x13c
net/http.serverHandler.ServeHTTP(0x2396120, 0x87dd88, 0x23961b0, 0x23c8000)
	/usr/local/go/src/net/http/server.go:2807 +0x88
net/http.(*conn).serve(0x2292060, 0x87efc8, 0x209e800)
	/usr/local/go/src/net/http/server.go:1895 +0x7d4
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2933 +0x2d0

````

**复现方法**
发送消息即可复现

**Comment by Mrs4s** [comment]
此问题为 `Authorization` 未正常配置导致, 请检查应用或将 `access_token` 设置为空.
将在下个版本加入判断

**Comment by ouyanglong721** [comment]
好的,已解决.将Authorization设置为空
